/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tenders */
        get: operations["list_tenders_tenders_get"];
        put?: never;
        /** Create Tender */
        post: operations["create_tender_tenders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenders/{tender_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tender */
        get: operations["get_tender_tenders__tender_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Connections */
        get: operations["list_connections_ai_connections_get"];
        put?: never;
        /** Add Connection */
        post: operations["add_connection_ai_connections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/connections/{connection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Connection */
        delete: operations["remove_connection_ai_connections__connection_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/connections/{connection_id}/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_ai_connections__connection_id__models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/connections/{connection_id}/checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check Model */
        post: operations["check_model_ai_connections__connection_id__checks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Settings */
        patch: operations["update_settings_settings_patch"];
        trace?: never;
    };
    "/tenders/{tender_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_tenders__tender_id__documents_get"];
        put?: never;
        /** Add Documents */
        post: operations["add_documents_tenders__tender_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenders/{tender_id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_tenders__tender_id__search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/pages/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Page */
        get: operations["get_page_documents__document_id__pages__number__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/pages/{number}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Page Image */
        get: operations["page_image_documents__document_id__pages__number__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Original File */
        get: operations["original_file_documents__document_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenders/{tender_id}/office": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Office */
        get: operations["office_tenders__tender_id__office_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenders/{tender_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Messages */
        get: operations["list_messages_tenders__tender_id__messages_get"];
        put?: never;
        /** Send Message */
        post: operations["send_message_tenders__tender_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenders/{tender_id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_tenders__tender_id__tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenders/{tender_id}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Decisions */
        get: operations["list_decisions_tenders__tender_id__decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decisions/{decision_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer Decision */
        post: operations["answer_decision_decisions__decision_id__answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenders/{tender_id}/office/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Office */
        post: operations["stop_office_tenders__tender_id__office_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenders/{tender_id}/boq": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Boq */
        get: operations["get_boq_tenders__tender_id__boq_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenders/{tender_id}/gates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gates */
        get: operations["gates_tenders__tender_id__gates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boq/{item_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide Item */
        post: operations["decide_item_boq__item_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenders/{tender_id}/boq/approve-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve All */
        post: operations["approve_all_tenders__tender_id__boq_approve_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/facts/{fact_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide Fact */
        post: operations["decide_fact_facts__fact_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenders/{tender_id}/takeoff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Takeoff */
        get: operations["get_takeoff_tenders__tender_id__takeoff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/pages/{number}/sheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sheet
         * @description Any PDF page as a sheet the engineer can measure on.
         */
        get: operations["get_sheet_documents__document_id__pages__number__sheet_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/pages/{number}/vertices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Vertices
         * @description The drawing's own corners and line ends, for snapping the engineer's clicks.
         */
        get: operations["get_vertices_documents__document_id__pages__number__vertices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenders/{tender_id}/scales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Scale */
        post: operations["set_scale_tenders__tender_id__scales_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenders/{tender_id}/measurements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Measurement */
        post: operations["add_measurement_tenders__tender_id__measurements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/measurements/{measurement_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide Measurement */
        post: operations["decide_measurement_measurements__measurement_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scales/{scale_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide Scale */
        post: operations["decide_scale_scales__scale_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/measurements/{measurement_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Measurement
         * @description The engineer removes a measurement to redo it. It is kept as rejected, not erased.
         */
        delete: operations["delete_measurement_measurements__measurement_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Added */
        Added: {
            /** Added */
            added: number;
            /** Unchanged */
            unchanged: number;
        };
        /** AnswerIn */
        AnswerIn: {
            /** Answer */
            answer: string;
        };
        /** Approved */
        Approved: {
            /** Approved */
            approved: number;
        };
        /** Body_add_documents_tenders__tender_id__documents_post */
        Body_add_documents_tenders__tender_id__documents_post: {
            /** Files */
            files: string[];
        };
        /** Boq */
        Boq: {
            /** Items */
            items: components["schemas"]["ItemOut"][];
            /** Facts */
            facts: components["schemas"]["FactOut"][];
        };
        /** CheckRequest */
        CheckRequest: {
            /** Model */
            model: string;
        };
        /** ComparisonOut */
        ComparisonOut: {
            /** Boq Item Id */
            boq_item_id: string | null;
            /** Item */
            item: string | null;
            /** Description */
            description: string;
            /** Boq Quantity */
            boq_quantity: string | null;
            /** Boq Unit */
            boq_unit: string | null;
            /** Takeoff */
            takeoff: string | null;
            /** Unit */
            unit: string;
            /** Result */
            result: string;
            /** Difference */
            difference: string | null;
        };
        /** ConnectionCreate */
        ConnectionCreate: {
            /**
             * Provider
             * @enum {string}
             */
            provider: "anthropic" | "openai" | "google" | "xai" | "openai_compatible";
            /** Api Key */
            api_key: string;
            /** Base Url */
            base_url?: string | null;
        };
        /** ConnectionOut */
        ConnectionOut: {
            /** Id */
            id: string;
            /**
             * Provider
             * @enum {string}
             */
            provider: "anthropic" | "openai" | "google" | "xai" | "openai_compatible";
            /** Label */
            label: string;
            /** Base Url */
            base_url: string | null;
            /** Key Hint */
            key_hint: string;
            /** Checks */
            checks: {
                [key: string]: components["schemas"]["ModelCheck"];
            };
        };
        /** DecisionIn */
        DecisionIn: {
            /** Approve */
            approve: boolean;
            /** Reason */
            reason?: string | null;
        };
        /** DecisionOut */
        DecisionOut: {
            /** Id */
            id: string;
            /** Raised By */
            raised_by: string;
            /** Title */
            title: string;
            /** Text */
            text: string;
            /** Options */
            options: string[];
            /** Status */
            status: string;
            /** Answer */
            answer: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DocumentOut */
        DocumentOut: {
            /** Id */
            id: string;
            /** Path */
            path: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Size */
            size: number;
            /** Status */
            status: string;
            /** Note */
            note: string | null;
            /** Page Count */
            page_count: number | null;
            /** Group Name */
            group_name: string | null;
            /** Description */
            description: string | null;
        };
        /** FactOut */
        FactOut: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Value */
            value: string;
            /** Status */
            status: string;
            /** Proposed By */
            proposed_by: string;
            source: components["schemas"]["Source"];
        };
        /** Gates */
        Gates: {
            /** Boq */
            boq: number;
            /** Facts */
            facts: number;
            /** Takeoff */
            takeoff: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ItemOut */
        ItemOut: {
            /** Id */
            id: string;
            /** Section */
            section: string | null;
            /** Item */
            item: string;
            /** Description */
            description: string;
            /** Unit */
            unit: string;
            /** Quantity */
            quantity: string | null;
            /** Status */
            status: string;
            /** Proposed By */
            proposed_by: string;
            /** Reason */
            reason: string | null;
            source: components["schemas"]["Source"];
        };
        /** MeasurementIn */
        MeasurementIn: {
            /** Document Id */
            document_id: string;
            /** Page */
            page: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "length" | "area" | "count";
            /** Label */
            label: string;
            /** Points */
            points: number[][];
            /** Unit */
            unit: string;
            /** Multiplier */
            multiplier?: number | string | null;
            /** Boq Item */
            boq_item?: string | null;
        };
        /** MeasurementOut */
        MeasurementOut: {
            /** Id */
            id: string;
            /** Document Id */
            document_id: string;
            /** Page */
            page: number;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Points */
            points: number[][];
            /** Unit */
            unit: string;
            /** Multiplier */
            multiplier: string | null;
            /** Quantity */
            quantity: string | null;
            /** Boq Item */
            boq_item: string | null;
            /** Status */
            status: string;
            /** Proposed By */
            proposed_by: string;
        };
        /** MessageIn */
        MessageIn: {
            /** Channel */
            channel: string;
            /** Text */
            text: string;
        };
        /** MessageOut */
        MessageOut: {
            /** Id */
            id: number;
            /** Sender */
            sender: string;
            /** Channel */
            channel: string;
            /** Kind */
            kind: string;
            /** Text */
            text: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ModelCheck */
        ModelCheck: {
            /** Ok */
            ok: boolean;
            /** Message */
            message: string;
            /** Checked At */
            checked_at: string;
        };
        /** OfficeAI */
        OfficeAI: {
            /** Connection Id */
            connection_id: string;
            /** Model */
            model: string;
        };
        /** OfficeOut */
        OfficeOut: {
            /**
             * State
             * @enum {string}
             */
            state: "working" | "paused" | "idle";
            /** Ai Ready */
            ai_ready: boolean;
            /** Staff */
            staff: components["schemas"]["StaffOut"][];
            /** Waiting */
            waiting: number;
        };
        /** PageOut */
        PageOut: {
            /** Number */
            number: number;
            /** Text */
            text: string;
            /** Has Text */
            has_text: boolean;
        };
        /** ScaleIn */
        ScaleIn: {
            /** Document Id */
            document_id: string;
            /** Page */
            page: number;
            /** Line */
            line: number[][];
            /** Length M */
            length_m: number;
            /** Dimension */
            dimension: string;
        };
        /** ScaleOut */
        ScaleOut: {
            /** Id */
            id: string;
            /** Metres Per Point */
            metres_per_point: number;
            /** Line */
            line: number[][];
            /** Length M */
            length_m: number;
            /** Dimension */
            dimension: string;
            /** Status */
            status: string;
            /** Proposed By */
            proposed_by: string;
        };
        /** SearchHit */
        SearchHit: {
            /** Document Id */
            document_id: string;
            /** Name */
            name: string;
            /** Page */
            page: number;
            /** Snippet */
            snippet: string;
        };
        /** Settings */
        Settings: {
            /**
             * Office Mode
             * @enum {string}
             */
            office_mode: "engineer" | "autonomous";
            office_ai: components["schemas"]["OfficeAI"] | null;
        };
        /** SettingsUpdate */
        SettingsUpdate: {
            /** Office Mode */
            office_mode?: ("engineer" | "autonomous") | null;
            office_ai?: components["schemas"]["OfficeAI"] | null;
        };
        /** Sheet */
        Sheet: {
            /** Document Id */
            document_id: string;
            /** Name */
            name: string;
            /** Page */
            page: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
            scale: components["schemas"]["ScaleOut"] | null;
        };
        /** Source */
        Source: {
            /** Document Id */
            document_id: string;
            /** Document Name */
            document_name: string;
            /** Page */
            page: number;
            /** Quote */
            quote: string;
        };
        /** StaffOut */
        StaffOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Is Manager */
            is_manager: boolean;
            /** Profile */
            profile: {
                [key: string]: unknown;
            };
            /** Status */
            status: string;
            /** Now */
            now: string | null;
        };
        /** Takeoff */
        Takeoff: {
            /** Sheets */
            sheets: components["schemas"]["Sheet"][];
            /** Measurements */
            measurements: components["schemas"]["MeasurementOut"][];
            /** Comparison */
            comparison: components["schemas"]["ComparisonOut"][];
        };
        /** TaskOut */
        TaskOut: {
            /** Id */
            id: string;
            /** Staff Id */
            staff_id: string;
            /** Title */
            title: string;
            /** Brief */
            brief: string;
            /** Status */
            status: string;
            /** Result */
            result: string | null;
        };
        /** TenderCreate */
        TenderCreate: {
            /** Name */
            name: string;
            /** Due Date */
            due_date?: string | null;
        };
        /** TenderOut */
        TenderOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Due Date
             * @description Submission deadline, when known
             */
            due_date: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_tenders_tenders_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenderOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_tender_tenders_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tender_tenders__tender_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_connections_ai_connections_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_connection_ai_connections_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_connection_ai_connections__connection_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_ai_connections__connection_id__models_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_model_ai_connections__connection_id__checks_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_settings_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_settings_settings_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_tenders__tender_id__documents_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_documents_tenders__tender_id__documents_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_add_documents_tenders__tender_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Added"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_tenders__tender_id__search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_page_documents__document_id__pages__number__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                document_id: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    page_image_documents__document_id__pages__number__image_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                document_id: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    original_file_documents__document_id__file_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    office_tenders__tender_id__office_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfficeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_tenders__tender_id__messages_get: {
        parameters: {
            query?: {
                channel?: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_tenders__tender_id__messages_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_tenders__tender_id__tasks_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_decisions_tenders__tender_id__decisions_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_decision_decisions__decision_id__answer_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                decision_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_office_tenders__tender_id__office_stop_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_boq_tenders__tender_id__boq_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Boq"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gates_tenders__tender_id__gates_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Gates"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_item_boq__item_id__decision_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_all_tenders__tender_id__boq_approve_all_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Approved"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_fact_facts__fact_id__decision_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                fact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_takeoff_tenders__tender_id__takeoff_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Takeoff"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sheet_documents__document_id__pages__number__sheet_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                document_id: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sheet"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vertices_documents__document_id__pages__number__vertices_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                document_id: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number[][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_scale_tenders__tender_id__scales_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScaleIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScaleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_measurement_tenders__tender_id__measurements_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeasurementIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasurementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_measurement_measurements__measurement_id__decision_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                measurement_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_scale_scales__scale_id__decision_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                scale_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_measurement_measurements__measurement_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                measurement_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
