import { MicroButton } from "@/components/ui/micro-button";
import { FieldError } from "../components/FieldError";
import { useCallback, useState } from "react";
import { prepareSignInBrowser } from "../browser";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useApi, useRefresh, useResource, type Schema } from "../api";
import { ErrorNotice, Loading, Modal, Status } from "../components/common";
import { ExternalLink, webLink as safeUrl } from "../components/ExternalLink";


const protocolLabels: Record<Schema<"ConnectionRecord">["protocol"], string> = {
  openai_responses: "OpenAI Responses", openai_chat: "OpenAI-compatible Chat", anthropic: "Anthropic Messages", google: "Google Gemini", bedrock: "Amazon Bedrock", mistral: "Mistral", cohere: "Cohere", codex: "Original Codex client", copilot: "Original Copilot client", gemini_cli: "Original Gemini CLI", grok_build: "Original Grok client", claude_agent: "Claude Agent SDK", claude_code: "Original Claude Code · attended use",
};
const authLabels: Record<Schema<"ConnectionRecord">["auth_type"], string> = { api_key: "API key", environment: "Environment variable", azure_identity: "Azure identity", aws_identity: "AWS identity", google_identity: "Google identity", client_login: "Original client sign-in", none: "No authentication" };
const credentialLabels: Record<Schema<"ConnectionRecord">["credential_state"], string> = { stored: "Credentials saved in the operating system store", session: "Credentials available for this session only", environment: "Environment or identity credentials configured", runtime: "Sign-in managed by the original client", missing: "Credentials not available", not_required: "No credentials required" };
const settingLabels: Record<string, string> = { region: "Service region", project: "Cloud project", location: "Cloud location", aws_profile: "AWS profile", billing_product: "Billing product or plan", tenant_id: "Azure tenant ID", client_id: "Azure application ID", executable_path: "Original client executable path", node_path: "Node.js executable path", terminal_path: "Terminal executable path", runtime_timeout_seconds: "Client time limit (seconds)", max_turns: "Maximum client turns", upstream_providers: "Approved upstream provider IDs", allow_fallbacks: "Allow provider-side fallback", data_collection: "Upstream data collection", zdr: "Require zero data retention" };
const directProviderIds = new Set(["openai", "anthropic", "google", "xai", "custom"]);
const directProtocols: Record<string, Schema<"ConnectionRecord">["protocol"][]> = {
  openai: ["openai_responses", "openai_chat"],
  anthropic: ["anthropic"],
  google: ["google"],
  xai: ["openai_responses", "openai_chat"],
  custom: ["openai_chat", "openai_responses"],
};

export function withoutAutomaticFallback(providerId: string, settings: Record<string, unknown>) {
  return providerId === "openrouter" ? { ...settings, allow_fallbacks: false } : settings;
}

export function AdvancedAIConnections() {
  const connections = useResource<Schema<"ConnectionRecord">[]>("/ai/connections"), providers = useResource<Schema<"ProviderPreset">[]>("/ai/providers");
  const [editing, setEditing] = useState<Schema<"ConnectionRecord"> | "new" | null>(null), [models, setModels] = useState<Schema<"ConnectionRecord"> | null>(null), [deleting, setDeleting] = useState<Schema<"ConnectionRecord"> | null>(null);
  const closeEditor = useCallback(() => setEditing(null), []), closeModels = useCallback(() => setModels(null), []), closeDelete = useCallback(() => setDeleting(null), []);
  return <section className="ai-connections" aria-labelledby="ai-connections-heading"><div className="section-heading"><h2 id="ai-connections-heading">AI connections</h2><button type="button" className="button" disabled={!providers.data?.length} onClick={() => setEditing("new")}>Add AI connection</button></div><p className="muted">Save named accounts and endpoints, then approve the connections and models separately for each tender.</p><ErrorNotice error={connections.error || providers.error} />{connections.isPending || providers.isPending ? <Loading>Loading AI connections…</Loading> : null}
    {connections.data?.length === 0 ? <p className="field-help">No AI connections are saved. Add an API, local model server or supported original client.</p> : null}
    {connections.data?.map(connection => <article className="ai-connection-card" key={connection.id}><div className="section-heading"><div><h3>{connection.name}</h3><p className="field-help">{providers.data?.find(provider => provider.id === connection.provider_id)?.name ?? connection.provider_id} · {protocolLabels[connection.protocol]} · {connection.billing} billing</p></div><Status value={connection.enabled ? connection.status : "disabled"} /></div><p className="field-help">{connection.base_url ?? "Original client runtime"}</p><p className="field-help">{credentialLabels[connection.credential_state]}. Configuration does not establish model access.</p>{connection.last_error ? <ErrorNotice error={new Error(connection.last_error)} /> : null}<div className="inline-actions"><button type="button" className="button" onClick={() => setEditing(connection)}>Edit connection</button><button type="button" className="button" onClick={() => setModels(connection)}>Models and client setup</button><MicroButton kind="delete" onClick={() => setDeleting(connection)}>Remove connection</MicroButton></div></article>)}
    {editing && providers.data ? <ConnectionForm connection={editing === "new" ? undefined : editing} providers={providers.data} onClose={closeEditor} /> : null}
    {models ? <ConnectionModels connection={connections.data?.find(connection => connection.id === models.id) ?? models} provider={providers.data?.find(provider => provider.id === models.provider_id)} onClose={closeModels} /> : null}
    {deleting ? <RemoveConnection connection={deleting} onClose={closeDelete} /> : null}
  </section>;
}

export function ConnectionForm({ connection, providers, onClose, onSave }: { connection?: Schema<"ConnectionRecord">; providers: Schema<"ProviderPreset">[]; onClose: () => void; onSave?: (values: Schema<"ConnectionInput">) => Promise<void> }) {
  const api = useApi(), refresh = useRefresh();
  const availableProviders = providers.filter(provider => directProviderIds.has(provider.id));
  const initial = availableProviders.find(provider => provider.id === connection?.provider_id) ?? availableProviders[0] ?? providers[0];
  const initialProtocols = directProtocols[initial.id] ?? initial.protocols;
  const initialAuth: Schema<"ConnectionInput">["auth_type"] = connection?.auth_type === "environment" && initial.auth_methods.includes("environment") ? "environment" : "api_key";
  const initialBilling: Schema<"ConnectionInput">["billing"] = initial.id === "custom" && connection?.billing === "metered" ? "metered" : initial.id === "custom" ? "unknown" : "metered";
  const [name, setName] = useState(connection?.name ?? ""), [providerId, setProviderId] = useState(initial.id), [protocol, setProtocol] = useState<Schema<"ConnectionInput">["protocol"]>(connection && initialProtocols.includes(connection.protocol) ? connection.protocol : initialProtocols[0]), [auth, setAuth] = useState<Schema<"ConnectionInput">["auth_type"]>(initialAuth), [billing, setBilling] = useState<Schema<"ConnectionInput">["billing"]>(initialBilling), [endpoint, setEndpoint] = useState(connection?.base_url ?? initial.base_url ?? "");
  const [enabled, setEnabled] = useState(connection?.enabled ?? true), [environmentKey, setEnvironmentKey] = useState(connection?.environment_key ?? ""), [settings, setSettings] = useState<Record<string, unknown>>(withoutAutomaticFallback(initial.id, connection?.settings ?? {})), [secrets, setSecrets] = useState<Record<string, string>>({}), [sessionOnly, setSessionOnly] = useState(false), [clearSecrets, setClearSecrets] = useState(false), [insecure, setInsecure] = useState(connection?.allow_insecure_http ?? false), [credentialFile, setCredentialFile] = useState("");
  const [busy, setBusy] = useState(false), [error, setError] = useState<unknown>(null);
  const provider = availableProviders.find(item => item.id === providerId) ?? initial;
  const protocols = directProtocols[provider.id] ?? provider.protocols.filter(value => directProtocols[provider.id]?.includes(value));
  const authMethods = provider.auth_methods.filter(value => value === "api_key" || value === "environment");
  const billingOptions = provider.id === "custom" ? (["unknown", "metered"] as const) : (["metered"] as const);
  const credentialNames = auth === "api_key" ? [["api_key", "API key"]] : [];
  return <Modal title={connection ? "Edit AI connection" : "Add AI connection"} onClose={onClose}><form className="ai-form" onSubmit={async event => {
    event.preventDefault(); if (busy) return; setBusy(true); setError(null);
    const entered = Object.fromEntries(Object.entries(secrets).filter(([, value]) => value.trim()));
    const values: Schema<"ConnectionInput"> = { name: name.trim(), provider_id: providerId, protocol, auth_type: auth, billing, enabled, base_url: provider.kind === "runtime" ? null : endpoint.trim() || null, environment_key: auth === "environment" ? environmentKey.trim() : null, settings: withoutAutomaticFallback(providerId, Object.fromEntries(Object.entries(settings).filter(([, value]) => value !== "" && value !== undefined))), session_only: sessionOnly, allow_insecure_http: insecure, ...(clearSecrets ? { credentials: {} } : Object.keys(entered).length ? { credentials: entered } : {}) };
    try { if (onSave) await onSave(values); else if (connection) await api.put<Schema<"ConnectionRecord">>(`/ai/connections/${connection.id}`, values); else await api.post<Schema<"ConnectionRecord">>("/ai/connections", values); setSecrets({}); setCredentialFile(""); await refresh(); onClose(); }
    catch (failure) { setError(failure); } finally { setBusy(false); }
  }}><fieldset disabled={busy}>
    <label>Connection name<input required maxLength={150} value={name} onChange={event => setName(event.target.value)} placeholder="Name this account or local server" /><FieldError error={error} name="name" /></label>
    <label>Provider<select value={providerId} onChange={event => { const next = availableProviders.find(item => item.id === event.target.value)!; const nextProtocols = directProtocols[next.id] ?? next.protocols; setProviderId(next.id); setProtocol(nextProtocols[0]); setAuth(next.auth_methods.includes("api_key") ? "api_key" : "environment"); setBilling(next.id === "custom" ? "unknown" : "metered"); setEndpoint(next.base_url ?? ""); setSettings({}); setSecrets({}); setCredentialFile(""); setEnvironmentKey(""); setInsecure(false); }} >{availableProviders.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
    <div className="ai-form-grid"><label>Connection protocol<select value={protocol} onChange={event => { setProtocol(event.target.value as typeof protocol); setEndpoint(""); }}>{protocols.map(value => <option key={value} value={value}>{protocolLabels[value]}</option>)}</select></label><label>Authentication<select value={auth} onChange={event => { setAuth(event.target.value as typeof auth); setSecrets({}); setCredentialFile(""); }}>{authMethods.map(value => <option key={value} value={value}>{authLabels[value]}</option>)}</select></label></div>
    <label>API endpoint<input required={provider.id === "custom"} type="url" maxLength={2000} value={endpoint} onChange={event => setEndpoint(event.target.value)} placeholder="Provider default, or the exact documented endpoint" /><FieldError error={error} name="base_url" /></label><label className="checkbox-label"><input type="checkbox" checked={insecure} onChange={event => setInsecure(event.target.checked)} />Allow unencrypted HTTP to a trusted remote endpoint</label><p className="field-help">Local loopback servers may use HTTP. Review the endpoint for the chosen protocol.</p>
    <label>Billing basis<select value={billing} onChange={event => setBilling(event.target.value as typeof billing)}>{billingOptions.map(value => <option key={value} value={value}>{value === "metered" ? "Metered API usage" : "Cost not established"}</option>)}</select></label>
    {provider.notes?.map(note => <p className="field-help" key={note}>{note}</p>)}{safeUrl(provider.docs_url) ? <p><ExternalLink className="text-button" href={safeUrl(provider.docs_url)!}>Provider setup and data terms</ExternalLink></p> : null}
    {provider.settings_fields?.length ? <div className="ai-provider-settings"><h3>Provider settings</h3>{provider.settings_fields.map(field => <ProviderSetting key={field} field={field} value={settings[field]} onChange={value => setSettings(current => ({ ...current, [field]: value }))} />)}</div> : null}
    {auth === "environment" ? <label>API key environment variable<input required pattern="[A-Za-z_][A-Za-z0-9_]*" maxLength={150} value={environmentKey} onChange={event => setEnvironmentKey(event.target.value)} placeholder="Name of the existing environment variable" /><FieldError error={error} name="environment_key" /></label> : null}
    {credentialNames.map(([field, label]) => <label key={field}>{label}<input type="password" autoComplete="new-password" maxLength={4000} disabled={clearSecrets} value={secrets[field] ?? ""} onChange={event => setSecrets(current => ({ ...current, [field]: event.target.value }))} placeholder={connection ? "Leave blank to retain the current credential" : "Enter a credential only if this account requires it"} /><FieldError error={error} path={["credentials", field]} /></label>)}
    {auth === "google_identity" ? <label>Google service-account credential file (optional)<input type="file" accept=".json,application/json" disabled={clearSecrets} onChange={async event => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 30000) { setError(new Error("Choose a credential file under 30 KB.")); return; } try { const content = await file.text(); setSecrets(current => ({ ...current, service_account_json: content })); setCredentialFile(file.name); } catch { setError(new Error("The selected credential file could not be read.")); } }} />{credentialFile ? <span className="field-help">Credential file selected for this save. Its content is hidden.</span> : null}</label> : null}
    {["api_key", "aws_identity", "azure_identity", "google_identity"].includes(auth) ? <><p className="field-help">Credentials are write-only. Blank fields retain saved credentials; newly entered credential fields replace the saved credential set. Identity authentication may use your existing system account configuration.</p><label className="checkbox-label"><input type="checkbox" checked={sessionOnly} onChange={event => setSessionOnly(event.target.checked)} />Keep newly entered credentials for this service session only</label></> : null}
    {connection ? <><label className="checkbox-label"><input type="checkbox" checked={clearSecrets} onChange={event => { setClearSecrets(event.target.checked); if (event.target.checked) { setSecrets({}); setCredentialFile(""); } }} />Remove this connection's saved API credentials</label><p className="field-help">Changing an endpoint or account destination requires newly entered credentials or explicit credential removal.</p></> : null}
    <label className="checkbox-label"><input type="checkbox" checked={enabled} onChange={event => setEnabled(event.target.checked)} />Enable this connection for tender selection</label>
  </fieldset><ErrorNotice error={error} /><div className="form-actions"><button type="button" className="button" disabled={busy} onClick={onClose}>Cancel</button><button className="button primary" disabled={busy || !name.trim()}>{busy ? "Saving…" : "Save connection"}</button></div></form></Modal>;
}

function ProviderSetting({ field, value, onChange }: { field: string; value: unknown; onChange: (value: unknown) => void }) {
  const label = settingLabels[field] ?? field.replaceAll("_", " ");
  if (field === "allow_provider_managed_extras") return <p className="field-help">Grok spending: {value === true ? "Provider-managed extras allowed" : "Subscription allowance only"}. Change this using Subscription spending in the account setup panel, where a valid model check can be retained. Other account changes can require another check.</p>;
  if (field === "allow_fallbacks") return <p className="field-help">Automatic provider switching is off. Quantix pauses if the selected AI cannot continue, so you can choose and approve a different AI.</p>;
  if (field === "zdr") return <label className="checkbox-label"><input type="checkbox" checked={value === true} onChange={event => onChange(event.target.checked)} />{label}</label>;
  if (field === "data_collection") return <label>{label}<select value={typeof value === "string" ? value : "deny"} onChange={event => onChange(event.target.value)}><option value="deny">Deny</option><option value="allow">Allow</option></select></label>;
  if (field === "upstream_providers") return <label>{label}<textarea rows={2} value={Array.isArray(value) ? value.join("\n") : ""} onChange={event => onChange(event.target.value.split(/\r?\n/).map(item => item.trim()).filter(Boolean))} placeholder="One provider ID per line" /></label>;
  if (["runtime_timeout_seconds", "max_turns"].includes(field)) return <label>{label}<input type="number" min={1} max={field === "max_turns" ? 32 : 1800} step={1} value={typeof value === "number" ? value : ""} onChange={event => onChange(event.target.value === "" ? undefined : Number(event.target.value))} /></label>;
  return <label>{label}<input value={typeof value === "string" ? value : ""} maxLength={field.endsWith("_path") ? 2000 : 300} onChange={event => onChange(event.target.value)} placeholder={field.endsWith("_path") ? "Optional absolute executable path on this device" : "Optional provider setting"} /></label>;
}

function RemoveConnection({ connection, onClose }: { connection: Schema<"ConnectionRecord">; onClose: () => void }) {
  const api = useApi(), refresh = useRefresh(); const [confirmed, setConfirmed] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState<unknown>(null);
  return <Modal title="Remove AI connection" onClose={onClose}><form className="ai-form" onSubmit={async event => { event.preventDefault(); if (!confirmed || busy) return; setBusy(true); setError(null); try { await api.delete<Schema<"MutationReceipt">>(`/ai/connections/${connection.id}`); await refresh(); onClose(); } catch (failure) { setError(failure); } finally { setBusy(false); } }}><p className="muted">Remove “{connection.name}” and its saved model entries and credentials. Tender routes using it will need another approved connection.</p><label className="checkbox-label"><input type="checkbox" required checked={confirmed} disabled={busy} onChange={event => setConfirmed(event.target.checked)} />I want to remove this connection.</label><ErrorNotice error={error} /><div className="form-actions"><button type="button" className="button" disabled={busy} onClick={onClose}>Cancel</button><MicroButton kind="delete" type="submit" disabled={busy || !confirmed}>{busy ? "Removing…" : "Remove connection"}</MicroButton></div></form></Modal>;
}

export function ConnectionModels({ connection, provider, onClose }: { connection: Schema<"ConnectionRecord">; provider?: Schema<"ProviderPreset">; onClose: () => void }) {
  const api = useApi(), client = useQueryClient(); const path = `/ai/connections/${connection.id}/models`;
  const models = useResource<Schema<"ModelRecord">[]>(path);
  const [editing, setEditing] = useState<Schema<"ModelRecord"> | "new" | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState<unknown>(null);
  const closeEditor = useCallback(() => setEditing(null), []);
  return <Modal drawer title={`${connection.name} · Models and setup`} onClose={onClose}><div className="ai-model-panel">
    <p className="muted">Discover the provider's model names, or record a documented model manually. A discovered name alone does not establish its capabilities.</p>
    {provider?.kind === "runtime" ? <RuntimeControls connection={connection} /> : null}
    <div className="inline-actions"><button type="button" className="button" disabled={busy || !connection.enabled} onClick={async () => { setBusy(true); setError(null); try { const records = await api.post<Schema<"ModelRecord">[]>(`/ai/connections/${connection.id}/discover`); client.setQueryData([path], records); } catch (failure) { setError(failure); } finally { setBusy(false); } }}>{busy ? "Requesting model list…" : "Discover models"}</button><button type="button" className="button" onClick={() => setEditing("new")}>Add documented model</button></div>
    <p className="field-help">Discover models explicitly contacts this connection for metadata. It does not approve sending any tender content.</p><ErrorNotice error={models.error || error} />{models.isPending ? <Loading>Loading saved models…</Loading> : null}
    {models.data?.length === 0 ? <p className="field-help">No models are recorded for this connection.</p> : null}
    {models.data?.map(model => <article className="ai-model-row" key={model.model_id}><h3>{model.display_name}</h3><p className="field-help">{model.model_id} · {model.source}</p><div className="ai-model-capabilities">{(["tools", "structured_output", "images", "pdf", "web_search"] as const).map(capability => <span key={capability}>{capability.replaceAll("_", " ")}: {model.capabilities?.[capability] === true ? "Supported" : model.capabilities?.[capability] === false ? "Not supported" : "Not established"}</span>)}</div><p className="field-help">Reasoning: {model.capabilities?.reasoning?.length ? model.capabilities.reasoning.join(", ") : "Not recorded"} · Context: {model.capabilities?.context_window?.toLocaleString() ?? "Not established"} · Output: {model.capabilities?.max_output_tokens?.toLocaleString() ?? "Not established"}</p>{model.pricing ? <p className="field-help">USD per million tokens: input {model.pricing.input_per_million}, output {model.pricing.output_per_million}. Reference: {model.pricing.source} · {model.pricing.as_of}</p> : <p className="field-help">No price card recorded. Metered work requires documented prices.</p>}<button type="button" className="text-button" onClick={() => setEditing(model)}>Edit capabilities and prices</button></article>)}
    {editing ? <ModelForm connectionId={connection.id} model={editing === "new" ? undefined : editing} onClose={closeEditor} /> : null}
  </div></Modal>;
}

function RuntimeControls({ connection }: { connection: Schema<"ConnectionRecord"> }) {
  const api = useApi(), client = useQueryClient(), path = `/ai/connections/${connection.id}/runtime`;
  const clientLogin = connection.auth_type === "client_login";
  const credentialDescription = connection.protocol === "copilot" ? "a GitHub token" : "an API key";
  const status = useQuery({ queryKey: [path, connection.revision], queryFn: () => api.get<Schema<"RuntimeStatus">>(path), refetchInterval: query => ["installing", "login_pending"].includes(query.state.data?.state ?? "") ? 2000 : false });
  const [busy, setBusy] = useState(false), [error, setError] = useState<unknown>(null);
  async function act(action: "install" | "login" | "logout") {
    if (busy || (action !== "install" && !clientLogin)) return;
    setBusy(true); setError(null);
    try {
      if (action === "login") await prepareSignInBrowser(connection.protocol);
      const result = await api.post<Schema<"RuntimeStatus">>(`/ai/connections/${connection.id}/${action}`);
      client.setQueryData([path, connection.revision], result);
    } catch (failure) { setError(failure); }
    finally { setBusy(false); }
  }
  return <section className="ai-runtime"><h3>Original client setup</h3><ErrorNotice error={status.error || error} />{status.isPending ? <Loading>Reading client setup state…</Loading> : null}{status.data ? <><Status value={status.data.state} /><p className="field-help">{status.data.detail}</p>{clientLogin && status.data.user_code ? <p>Sign-in code: <strong>{status.data.user_code}</strong></p> : null}{clientLogin && safeUrl(status.data.login_url) ? <p><ExternalLink className="text-button" href={safeUrl(status.data.login_url)!}>Open the original provider sign-in page</ExternalLink></p> : null}{safeUrl(status.data.docs_url) ? <p><ExternalLink className="text-button" href={safeUrl(status.data.docs_url)!}>Original client setup instructions</ExternalLink></p> : null}</> : null}
    {!clientLogin ? <p className="field-help">This profile uses {credentialDescription}{connection.auth_type === "environment" ? " from its configured environment variable" : ""}. Manage that credential or environment-variable name through Edit connection.</p> : null}
    <div className="inline-actions"><button type="button" className="button" disabled={busy || status.data?.state === "installing"} onClick={() => void act("install")}>Install client</button>{clientLogin ? <><button type="button" className="button" disabled={busy || !status.data?.installed || status.data?.state === "login_pending"} onClick={() => void act("login")}>Sign in</button><button type="button" className="text-button" disabled={busy || !status.data?.installed} onClick={() => void act("logout")}>Sign out</button></> : null}<button type="button" className="text-button" disabled={busy} onClick={() => void status.refetch()}>Refresh client status</button></div>
  </section>;
}

function ModelForm({ connectionId, model, onClose }: { connectionId: string; model?: Schema<"ModelRecord">; onClose: () => void }) {
  const api = useApi(), refresh = useRefresh();
  const [id, setId] = useState(model?.model_id ?? ""), [name, setName] = useState(model?.display_name ?? ""), [capabilities, setCapabilities] = useState<Schema<"ModelCapabilities">>(model?.capabilities ?? { tools: null, structured_output: null, images: null, pdf: null, web_search: null, reasoning: [], context_window: null, max_output_tokens: null });
  const [reasoning, setReasoning] = useState(model?.capabilities?.reasoning?.join(", ") ?? ""), [priced, setPriced] = useState(!!model?.pricing), [inputPrice, setInputPrice] = useState(model?.pricing?.input_per_million.toString() ?? ""), [outputPrice, setOutputPrice] = useState(model?.pricing?.output_per_million.toString() ?? ""), [cachePrice, setCachePrice] = useState(model?.pricing?.cached_input_per_million?.toString() ?? ""), [searchPrice, setSearchPrice] = useState(model?.pricing?.web_search_per_call?.toString() ?? ""), [priceSource, setPriceSource] = useState(model?.pricing?.source ?? ""), [priceDate, setPriceDate] = useState(model?.pricing?.as_of ?? "");
  const [codePrice, setCodePrice] = useState(model?.pricing?.code_execution_per_session?.toString() ?? "");
  const [codeSource, setCodeSource] = useState(model?.pricing?.code_execution_source ?? "");
  const [codeDate, setCodeDate] = useState(model?.pricing?.code_execution_as_of ?? "");
  const [busy, setBusy] = useState(false), [error, setError] = useState<unknown>(null);
  const pricesValid = !priced || (inputPrice !== "" && outputPrice !== "" && !!priceSource.trim() && !!priceDate.trim() && [inputPrice, outputPrice, ...(cachePrice ? [cachePrice] : []), ...(searchPrice ? [searchPrice] : [])].every(value => Number.isFinite(Number(value)) && Number(value) >= 0));
  return <Modal title={model ? "Edit recorded model" : "Add documented model"} onClose={onClose}><form className="ai-form" onSubmit={async event => {
    event.preventDefault(); if (busy || !pricesValid) return; setBusy(true); setError(null);
    try { await api.post<Schema<"ModelRecord">>(`/ai/connections/${connectionId}/models`, { model_id: id.trim(), display_name: name.trim(), capabilities: { ...capabilities, reasoning: [...new Set(reasoning.split(/[,\n]/).map(value => value.trim()).filter(Boolean))] }, pricing: priced ? { input_per_million: Number(inputPrice), output_per_million: Number(outputPrice), cached_input_per_million: cachePrice === "" ? null : Number(cachePrice), web_search_per_call: searchPrice === "" ? null : Number(searchPrice), source: priceSource.trim(), as_of: priceDate.trim(), ...(codePrice ? { code_execution_per_session: Number(codePrice), code_execution_source: codeSource.trim(), code_execution_as_of: codeDate } : {}) } : null } satisfies Schema<"ModelInput">); await refresh(); onClose(); }
    catch (failure) { setError(failure); } finally { setBusy(false); }
  }}><p className="muted">Record the exact model or deployment ID and its documented capabilities. Leave unsupported or unknown capabilities explicit.</p><fieldset disabled={busy}>
    <label>Model or deployment ID<input required readOnly={!!model} maxLength={300} value={id} onChange={event => setId(event.target.value)} /></label><label>Display name<input required maxLength={300} value={name} onChange={event => setName(event.target.value)} /></label>
    <div className="ai-form-grid">{([ ["tools", "Tender Office tools"], ["structured_output", "Structured output"], ["images", "Image input"], ["pdf", "PDF input"], ["web_search", "Hosted web search"] ] as const).map(([field, label]) => <label key={field}>{label}<select value={capabilities[field] === true ? "yes" : capabilities[field] === false ? "no" : "unknown"} onChange={event => setCapabilities(current => ({ ...current, [field]: event.target.value === "unknown" ? null : event.target.value === "yes" }))}><option value="unknown">Not established</option><option value="yes">Supported</option><option value="no">Not supported</option></select></label>)}</div>
    <label>Documented reasoning settings<input value={reasoning} onChange={event => setReasoning(event.target.value)} placeholder="Comma-separated settings from the model documentation" /></label><div className="ai-form-grid"><label>Context window (tokens)<input type="number" min={1} step={1} value={capabilities.context_window ?? ""} onChange={event => setCapabilities(current => ({ ...current, context_window: event.target.value ? Number(event.target.value) : null }))} /></label><label>Maximum model output tokens<input type="number" min={1} step={1} value={capabilities.max_output_tokens ?? ""} onChange={event => setCapabilities(current => ({ ...current, max_output_tokens: event.target.value ? Number(event.target.value) : null }))} /></label></div>
    <label className="checkbox-label"><input type="checkbox" checked={priced} onChange={event => setPriced(event.target.checked)} />Record a model price card in USD</label>
    <details><summary>More options</summary><div className="ai-form-grid"><label>Response streaming<select value={capabilities.streaming === true ? "yes" : capabilities.streaming === false ? "no" : "unknown"} onChange={event => setCapabilities(current => ({ ...current, streaming: event.target.value === "unknown" ? null : event.target.value === "yes" }))}><option value="unknown">Not established</option><option value="yes">Supported</option><option value="no">Completed responses only</option></select></label>{priced && <><label>Hosted code per 20-minute session (USD)<input type="number" min={0.03} step="any" value={codePrice} onChange={event => setCodePrice(event.target.value)} /></label><label>Hosted-code pricing page<input type="url" required={!!codePrice} value={codeSource} onChange={event => setCodeSource(event.target.value)} placeholder="https://developers.openai.com/api/docs/pricing" /></label><label>Hosted-code price checked on<input type="date" required={!!codePrice} max={new Date().toISOString().slice(0, 10)} value={codeDate} onChange={event => setCodeDate(event.target.value)} /></label><p className="field-help">The supported OpenAI container uses 1 GB. Record its full session rate and dated source. Each Tender separately reviews exact uploaded files and a charge allowance; this is an estimate, not an invoice ceiling.</p></>}</div></details>
    {priced ? <><div className="ai-form-grid"><label>Input per million tokens<input type="number" required min={0} step="any" value={inputPrice} onChange={event => setInputPrice(event.target.value)} /></label><label>Output per million tokens<input type="number" required min={0} step="any" value={outputPrice} onChange={event => setOutputPrice(event.target.value)} /></label><label>Cached input per million (optional)<input type="number" min={0} step="any" value={cachePrice} onChange={event => setCachePrice(event.target.value)} /></label><label>Hosted search per call (optional)<input type="number" min={0} step="any" value={searchPrice} onChange={event => setSearchPrice(event.target.value)} /></label></div><label>Pricing reference<input required maxLength={1000} value={priceSource} onChange={event => setPriceSource(event.target.value)} placeholder="Published source or account pricing reference" /></label><label>Price date or source version<input required maxLength={50} value={priceDate} onChange={event => setPriceDate(event.target.value)} /></label><p className="field-help">These prices support usage estimates and budget reservations. They are not an invoice or a connection test.</p></> : null}
  </fieldset><ErrorNotice error={error} /><div className="form-actions"><button type="button" className="button" disabled={busy} onClick={onClose}>Cancel</button><button className="button primary" disabled={busy || !id.trim() || !name.trim() || !pricesValid}>{busy ? "Saving…" : "Save model record"}</button></div></form></Modal>;
}
