// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentTaskInputReference } from "./AgentTaskInputReference";
import type { DataClassification } from "./DataClassification";

export type AccessRequest = { request_id: string, run_id: string, exact_inputs: Array<AgentTaskInputReference>, data_scopes: Array<string>, data_classifications: Array<DataClassification>, allowed_actions: Array<string>, allowed_tools: Array<string>, purpose: string, recurring: boolean, };
