// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActivateTenderProductionCommand = { tender_id: string, plan_id: string, plan_version: number, plan_manifest_sha256: string, };
