// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentRunPermissions = { data_scopes: Array<string>, allowed_actions: Array<string>, allowed_tools: Array<string>, network_allowed: boolean, workspace_write_allowed: boolean, };
