// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentAccessRequestView } from "./AgentAccessRequestView";
import type { AgentProfileVersionView } from "./AgentProfileVersionView";
import type { AgentRunRecoveryDecision } from "./AgentRunRecoveryDecision";
import type { AgentRunState } from "./AgentRunState";
import type { PermissionGrant } from "./PermissionGrant";
import type { ProposedAgentResult } from "./ProposedAgentResult";
import type { ProviderEvent } from "./ProviderEvent";
import type { ProviderFailure } from "./ProviderFailure";
import type { ProviderUsage } from "./ProviderUsage";
import type { TenderTaskView } from "./TenderTaskView";

export type AgentRunInspection = { run_id: string, retry_of_run_id: string | null, state: AgentRunState, profile: AgentProfileVersionView, task: TenderTaskView, permission_grant: PermissionGrant, access_requests: Array<AgentAccessRequestView>, provider_thread_ref: string | null, provider_turn_ref: string | null, events: Array<ProviderEvent>, usage: ProviderUsage, failure: ProviderFailure | null, proposed_result: ProposedAgentResult | null, recovery_decision: AgentRunRecoveryDecision | null, started_at: string, completed_at: string | null, };
