// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRunSummary } from "./AgentRunSummary";

export type AgentRunHistoryItem = { run_sequence: bigint, run: AgentRunSummary, };
