// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccessRequest } from "./AccessRequest";
import type { AgentAccessRequestStatus } from "./AgentAccessRequestStatus";
import type { OneRunAccessGrant } from "./OneRunAccessGrant";
import type { PermissionDenialReason } from "./PermissionDenialReason";

export type AgentAccessRequestView = { request: AccessRequest, status: AgentAccessRequestStatus, one_run_grant: OneRunAccessGrant | null, denial_reason: PermissionDenialReason | null, requested_at: string, decided_at: string | null, };
