// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentTaskInputReference } from "./AgentTaskInputReference";
import type { TenderQueryTreatmentProposalInput } from "./TenderQueryTreatmentProposalInput";

export type AgentTenderQueryUpdate = { query_id: string, base_version: number, added_evidence: Array<AgentTaskInputReference>, proposed_treatments: Array<TenderQueryTreatmentProposalInput>, response: string | null, response_evidence: Array<AgentTaskInputReference>, };
