// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRunHistoryItem } from "./AgentRunHistoryItem";

export type AgentRunHistoryPage = { items: Array<AgentRunHistoryItem>, next_before_sequence: bigint | null, total_count: bigint, };
