// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRunRecoveryDecision } from "./AgentRunRecoveryDecision";
import type { AgentRunState } from "./AgentRunState";
import type { ProviderFailure } from "./ProviderFailure";
import type { ProviderUsage } from "./ProviderUsage";

export type AgentRunSummary = { run_id: string, retry_of_run_id: string | null, has_linked_retry: boolean, linked_retry_supported: boolean, state: AgentRunState, profile_identity: string, profile_profession: string, profile_version: number, task_id: string, provider_thread_ref: string | null, provider_turn_ref: string | null, usage: ProviderUsage, failure: ProviderFailure | null, has_proposed_result: boolean, recovery_decision: AgentRunRecoveryDecision | null, started_at: string, completed_at: string | null, };
