// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentAccessRequestStatus = "blocked" | "approved" | "denied" | "expired" | "superseded" | "revoked";
