// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentResourceBudget = { provider_turns: number, duration_seconds: number, output_bytes: number, };
