// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputValidationIssue } from "./OutputValidationIssue";

export type AgentRepairFeedback = { rejected_run_id: string, rejected_payload_sha256: string, validation_issues: Array<OutputValidationIssue>, };
