// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentRunWorkspaceManifest = { workspace_id: string, read_only_inputs: string, working_area: string, staged_outputs: string, };
