// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentResourceBudget } from "./AgentResourceBudget";
import type { AgentRunPermissions } from "./AgentRunPermissions";

export type AgentProfileVersionView = { profile_id: string, version: number, identity: string, profession: string, capabilities: Array<string>, instructions: string, output_contract_json: string, review_policy: string, permissions: AgentRunPermissions, resource_budget: AgentResourceBudget, };
