// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentTaskInputReference } from "./AgentTaskInputReference";
import type { TenderQueryTreatmentProposalInput } from "./TenderQueryTreatmentProposalInput";
import type { TenderQueryType } from "./TenderQueryType";
import type { TenderRecordVersionReference } from "./TenderRecordVersionReference";

export type AgentTenderQueryProposal = { query_type: TenderQueryType, question: string, ambiguity_or_gap: string, evidence: Array<AgentTaskInputReference>, affected_records: Array<TenderRecordVersionReference>, affected_task_keys: Array<string>, due_at: string, material: boolean, release_blocking: boolean, proposed_treatments: Array<TenderQueryTreatmentProposalInput>, };
