// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentResourceBudget } from "./AgentResourceBudget";
import type { AgentRunPermissions } from "./AgentRunPermissions";

export type AgentProfileVersionView = { profile_id: string, version: number, identity: string, profession: string, seniority: string, capabilities: Array<string>, objective: string, behavior: string, skepticism: string, risk_tolerance: string, instructions: string, output_contract_json: string, review_policy: string, permissions: AgentRunPermissions, prohibited_actions: Array<string>, resource_budget: AgentResourceBudget, };
