// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiProviderKind } from "./AiProviderKind";
import type { ProviderReasoningSelection } from "./ProviderReasoningSelection";

export type AiExecutionApproval = { connection_id: string, provider: AiProviderKind, account_fingerprint: string, model_id: string, reasoning: ProviderReasoningSelection, data_destination: string, approved_at: string, };
