// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiProviderKind } from "./AiProviderKind";
import type { ProviderReasoningSelection } from "./ProviderReasoningSelection";

export type AiExecutionSelection = { connection_id: string, provider: AiProviderKind, model_id: string, reasoning: ProviderReasoningSelection, catalogue_fetched_at: string, adapter_version: string, };
