// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiProviderView } from "./AiProviderView";

export type AiProviderSettingsView = { connections: Array<AiProviderView>, active_id: string | null, 
/**
 * Surfaced in the interface so the storage trade-off is never a surprise.
 */
file_path: string, };
