// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which client speaks to the endpoint. These match the AI worker's `route` values.
 */
export type AiProviderRoute = "openai" | "openai_compatible" | "anthropic" | "anthropic_compatible" | "google" | "xai";
