// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a probe tells the Engineer. Deliberately not the raw driver error: the
 * message is shown in the interface, so it must never carry request material.
 */
export type AiProviderProbeResult = { reached: boolean, summary: string, };
