// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiProviderRoute } from "./AiProviderRoute";

/**
 * What the interface sees: everything except the key, plus whether one is stored.
 */
export type AiProviderView = { id: string, display_name: string, route: AiProviderRoute, base_url: string | null, model_id: string, has_api_key: boolean, is_active: boolean, };
