// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiExecutionSelection } from "./AiExecutionSelection";
import type { ProviderConnectionView } from "./ProviderConnectionView";
import type { ProviderLoginView } from "./ProviderLoginView";

export type ApplicationSettingsView = { ai_execution_selection: AiExecutionSelection | null, provider_connections: Array<ProviderConnectionView>, active_provider_login: ProviderLoginView | null, };
