// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApplicationStorageFacts = { application_home: string, tender_backups_are_preserved: boolean, trash_requires_explicit_purge: boolean, };
