// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApplicationDiagnostics = { quantix_version: string, installation_schema_version: bigint, tender_schema_version: bigint, };
