// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiExecutionApproval } from "./AiExecutionApproval";
import type { AiExecutionSelection } from "./AiExecutionSelection";
import type { ApplicationDiagnostics } from "./ApplicationDiagnostics";
import type { ApplicationStorageFacts } from "./ApplicationStorageFacts";
import type { GeneralApplicationPreferences } from "./GeneralApplicationPreferences";
import type { ProviderConnectionView } from "./ProviderConnectionView";
import type { ProviderLoginView } from "./ProviderLoginView";

export type ApplicationSettingsView = { general_preferences: GeneralApplicationPreferences, ai_execution_selection: AiExecutionSelection | null, ai_execution_approval: AiExecutionApproval | null, provider_connections: Array<ProviderConnectionView>, active_provider_login: ProviderLoginView | null, storage: ApplicationStorageFacts, diagnostics: ApplicationDiagnostics, };
