// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApprovePricingAdjustmentCommand = { tender_id: string, adjustment_id: string, version: number, manifest_sha256: string, rationale: string, };
