// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApprovePackageFindingExceptionCommand = { tender_id: string, package_id: string, package_version: number, package_manifest_sha256: string, review_id: string, finding_id: string, rationale: string, };
