// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApproveAgentAccessCommand = { tender_id: string, request_id: string, run_id: string, expires_at: string, };
