// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApprovedTenderPrice = { approval_id: string, amount: string, currency: string, calculation_manifest_sha256: string, rationale: string, approved_by: string, acting_role: string, current: boolean, manifest_sha256: string, created_at: string, };
