// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApproveCommercialStrategyCommand = { tender_id: string, strategy_id: string, manifest_sha256: string, rationale: string, };
