// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApproveSubmissionReleaseCommand = { tender_id: string, package_id: string, package_version: number, package_manifest_sha256: string, readiness_report_id: string, readiness_report_version: number, readiness_report_manifest_sha256: string, rationale: string, conditions: Array<string>, exceptions: Array<string>, };
