// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApproveProductionFindingExceptionCommand = { tender_id: string, production_task_id: string, finding_id: string, review_id: string, artifact_id: string, artifact_version: number, payload_sha256: string, rationale: string, consequence: string, };
