// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactVersionSummary } from "./ArtifactVersionSummary";

export type ArtifactVersionHistory = { versions: Array<ArtifactVersionSummary>, };
