// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ArtifactVersionSummary = { artifact_id: string, version: number, digest: string | null, created_at: string, };
