// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AssembleCoordinatedBidBaselineCommand = { tender_id: string, base_version: number | null, };
