// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AssembleSubmissionPackageCommand = { tender_id: string, generation_id: string, generation_manifest_sha256: string, };
