// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BasisOfEstimateApproval = { approval_id: string, basis_id: string, basis_version: number, basis_manifest_sha256: string, review_id: string, rationale: string, approved_by: string, acting_role: string, manifest_sha256: string, created_at: string, };
