// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BasisOfEstimateReviewFinding } from "./BasisOfEstimateReviewFinding";
import type { BasisOfEstimateReviewOutcome } from "./BasisOfEstimateReviewOutcome";

export type BasisOfEstimateReview = { review_id: string, reviewer_run_id: string, reviewer_profile_id: string, reviewer_profile_version: number, outcome: BasisOfEstimateReviewOutcome, findings: Array<BasisOfEstimateReviewFinding>, manifest_sha256: string, created_at: string, };
