// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BasisOfEstimateReviewFinding = { code: string, summary: string, affected_boq_row_keys: Array<string>, };
