// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BasisOfEstimateApproval } from "./BasisOfEstimateApproval";
import type { BasisOfEstimateReview } from "./BasisOfEstimateReview";
import type { BoqAccountRow } from "./BoqAccountRow";
import type { CostBreakdownComponent } from "./CostBreakdownComponent";
import type { EstimateAggregateCalculationRun } from "./EstimateAggregateCalculationRun";
import type { EstimateAllowance } from "./EstimateAllowance";
import type { EstimateMaterialAssumption } from "./EstimateMaterialAssumption";
import type { EstimateQueryObservation } from "./EstimateQueryObservation";
import type { EstimateQuotation } from "./EstimateQuotation";
import type { EstimateResourceBuildUp } from "./EstimateResourceBuildUp";

export type BasisOfEstimateVersion = { basis_id: string, version: number, tender_revision: number, author_run_id: string, author_profile_id: string, author_profile_version: number, scope: string, pricing_date: string, currencies: Array<string>, taxes: Array<string>, rate_sources: Array<string>, productivity: Array<string>, design_maturity: string, gaps: Array<string>, exclusions: Array<string>, supersedes_basis_manifest_sha256: string | null, remediates_review_manifest_sha256: string | null, boq_inventory_sha256: string, query_inventory_sha256: string, query_inventory: Array<EstimateQueryObservation>, boq_rows: Array<BoqAccountRow>, cbs_components: Array<CostBreakdownComponent>, resource_build_ups: Array<EstimateResourceBuildUp>, quotations: Array<EstimateQuotation>, allowances: Array<EstimateAllowance>, material_assumptions: Array<EstimateMaterialAssumption>, comparison_total_calculation_run_id: string, aggregate_calculation: EstimateAggregateCalculationRun, total_amount: string, total_currency: string, complete: boolean, reconciled: boolean, blockers: Array<string>, current: boolean, relied_upon: boolean, review: BasisOfEstimateReview | null, approval: BasisOfEstimateApproval | null, manifest_sha256: string, created_at: string, };
