// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRunInspection } from "./AgentRunInspection";
import type { BasisOfEstimateVersion } from "./BasisOfEstimateVersion";

export type BasisOfEstimateReviewResult = { run: AgentRunInspection, basis: BasisOfEstimateVersion, };
