// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BidDecisionPackageReviewFinding } from "./BidDecisionPackageReviewFinding";
import type { BidDecisionPackageReviewOutcome } from "./BidDecisionPackageReviewOutcome";

export type BidDecisionPackageReview = { review_id: string, reviewer_run_id: string, outcome: BidDecisionPackageReviewOutcome, findings: Array<BidDecisionPackageReviewFinding>, created_at: string, };
