// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BidDecisionReturnReworkItem } from "./BidDecisionReturnReworkItem";

export type BidDecisionReturnReworkDisposition = { disposition_id: string, approval_id: string, approval_sha256: string, items: Array<BidDecisionReturnReworkItem>, resolved_by: string, manifest_sha256: string, created_at: string, };
