// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BidDecisionApprovalInvalidation } from "./BidDecisionApprovalInvalidation";
import type { BidDecisionPackageInspection } from "./BidDecisionPackageInspection";

export type BidDecisionApprovalInvalidationResult = { invalidation: BidDecisionApprovalInvalidation, package: BidDecisionPackageInspection, };
