// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BidDecisionPackageInspection } from "./BidDecisionPackageInspection";
import type { BidDecisionReturnReworkDisposition } from "./BidDecisionReturnReworkDisposition";

export type BidDecisionReturnReworkResult = { disposition: BidDecisionReturnReworkDisposition, package: BidDecisionPackageInspection, };
