// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BidDecisionPackageRecordBinding } from "./BidDecisionPackageRecordBinding";

export type BidDecisionPackageRecordPage = { records: Array<BidDecisionPackageRecordBinding>, next_ordinal: number | null, };
