// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BidDecisionPackageRecordCategory } from "./BidDecisionPackageRecordCategory";
import type { TenderRecordInspection } from "./TenderRecordInspection";

export type BidDecisionPackageRecordBinding = { ordinal: number, category: BidDecisionPackageRecordCategory, record: TenderRecordInspection, };
