// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BidDecisionPackageChangeSummary = { prior_version: number | null, added_record_count: number, removed_record_count: number, changed_compliance_row_count: number, capability_demands_changed: boolean, resource_implications_changed: boolean, };
