// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BidDecisionApprovalDecision } from "./BidDecisionApprovalDecision";
import type { BidDecisionApprovalInvalidation } from "./BidDecisionApprovalInvalidation";
import type { TenderLifecyclePhase } from "./TenderLifecyclePhase";

export type BidDecisionApprovalRecord = { approval_sequence: number, approval_id: string, package_id: string, package_version: number, package_manifest_sha256: string, tender_revision: number, decision: BidDecisionApprovalDecision, decided_by: string, acting_role: string, rationale: string, evidence_count: number, evidence_sha256: string, conditions: Array<string>, exceptions: Array<string>, required_rework: Array<string>, lifecycle_before: TenderLifecyclePhase, lifecycle_after: TenderLifecyclePhase, consequence: string, preceding_approval_hash: string, approval_sha256: string, created_at: string, invalidation: BidDecisionApprovalInvalidation | null, };
