// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BidDecisionGateBlocker } from "./BidDecisionGateBlocker";
import type { BidDecisionPackageReview } from "./BidDecisionPackageReview";
import type { BidRecommendation } from "./BidRecommendation";
import type { CapabilityDemand } from "./CapabilityDemand";
import type { ResourceImplication } from "./ResourceImplication";

export type BidDecisionPackageInspection = { package_id: string, version: number, tender_revision: number, manifest_sha256: string, compliance_row_count: number, compliance_blocker_count: number, project_fingerprint_count: number, risk_count: number, opportunity_count: number, assumption_count: number, unresolved_query_count: number, capability_demands: Array<CapabilityDemand>, capability_gap_count: number, resource_implications: Array<ResourceImplication>, recommendation: BidRecommendation, blocker_count: number, blockers: Array<BidDecisionGateBlocker>, review: BidDecisionPackageReview | null, decision_gate_ready: boolean, current: boolean, created_by: string, created_at: string, };
