// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BidDecisionApprovalInvalidation } from "./BidDecisionApprovalInvalidation";
import type { BidDecisionApprovalRecord } from "./BidDecisionApprovalRecord";
import type { BidDecisionGateBlocker } from "./BidDecisionGateBlocker";
import type { BidDecisionPackageChangeSummary } from "./BidDecisionPackageChangeSummary";
import type { BidDecisionPackageReview } from "./BidDecisionPackageReview";
import type { BidDecisionReturnReworkDisposition } from "./BidDecisionReturnReworkDisposition";
import type { BidRecommendation } from "./BidRecommendation";
import type { CapabilityDemand } from "./CapabilityDemand";
import type { ResourceImplication } from "./ResourceImplication";
import type { TenderLifecyclePhase } from "./TenderLifecyclePhase";

export type BidDecisionPackageInspection = { package_id: string, version: number, tender_revision: number, manifest_sha256: string, compliance_row_count: number, compliance_blocker_count: number, project_fingerprint_count: number, risk_count: number, opportunity_count: number, assumption_count: number, unresolved_query_count: number, capability_demands: Array<CapabilityDemand>, capability_gap_count: number, resource_implications: Array<ResourceImplication>, recommendation: BidRecommendation, blocker_count: number, blockers: Array<BidDecisionGateBlocker>, review: BidDecisionPackageReview | null, approval: BidDecisionApprovalRecord | null, return_rework: BidDecisionReturnReworkDisposition | null, return_rework_basis: BidDecisionReturnReworkDisposition | null, material_change_basis: BidDecisionApprovalInvalidation | null, prior_approval_count: number, change_summary: BidDecisionPackageChangeSummary, lifecycle_phase: TenderLifecyclePhase, decision_gate_ready: boolean, current: boolean, created_by: string, created_at: string, };
