// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BidDecisionApprovalRecord } from "./BidDecisionApprovalRecord";
import type { BidDecisionPackageInspection } from "./BidDecisionPackageInspection";

export type BidDecisionApprovalResult = { approval: BidDecisionApprovalRecord, package: BidDecisionPackageInspection, };
