// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BidDecisionApprovalRecord } from "./BidDecisionApprovalRecord";

export type BidDecisionApprovalHistoryPage = { approvals: Array<BidDecisionApprovalRecord>, next_sequence: number | null, };
