// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderLifecyclePhase } from "./TenderLifecyclePhase";
import type { TenderRecordVersionReference } from "./TenderRecordVersionReference";

export type BidDecisionApprovalInvalidation = { invalidation_id: string, approval_id: string, approval_sha256: string, material_change_summary: string, affected_areas: Array<string>, changed_records: Array<TenderRecordVersionReference>, invalidated_by: string, acting_role: string, lifecycle_before: TenderLifecyclePhase, lifecycle_after: TenderLifecyclePhase, manifest_sha256: string, created_at: string, };
