// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BidRecommendationOutcome } from "./BidRecommendationOutcome";
import type { TenderRecordVersionReference } from "./TenderRecordVersionReference";

export type BidRecommendation = { outcome: BidRecommendationOutcome, rationale: string, evidence_records: Array<TenderRecordVersionReference>, };
