// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BootstrapRole = "tendering_manager" | "document_controller" | "tender_analyst" | "independent_reviewer";
