// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentProfileVersionView } from "./AgentProfileVersionView";
import type { BootstrapAuthority } from "./BootstrapAuthority";
import type { BootstrapRole } from "./BootstrapRole";

export type BootstrapTeamMember = { role: BootstrapRole, authority: BootstrapAuthority, active: boolean, profile: AgentProfileVersionView, };
