// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoqRowDisposition } from "./BoqRowDisposition";
import type { EstimateQueryReference } from "./EstimateQueryReference";
import type { TenderEvidenceReference } from "./TenderEvidenceReference";

export type BoqAccountRow = { row_key: string, description: string, disposition: BoqRowDisposition, evidence: Array<TenderEvidenceReference>, calculation_run_id: string | null, affected_queries: Array<EstimateQueryReference>, };
