// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderEvidenceReference } from "./TenderEvidenceReference";

export type BoqInventoryRow = { row_key: string, evidence: Array<TenderEvidenceReference>, };
