// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BoqRowDisposition = "priced" | "excluded" | "provisional" | "duplicated" | "missing" | "not_applicable" | "blocked";
