// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoqTableDesignation } from "./BoqTableDesignation";

export type BoqTableCandidate = { artifact_id: string, artifact_version: number, table_number: number, document_name: string, row_count: number, sample_text: string, designation: BoqTableDesignation | null, };
