// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BoqTableDesignation = { designation_id: string, artifact_id: string, artifact_version: number, table_number: number, header_row_count: number, row_count: number, manifest_sha256: string, created_at: string, };
