// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CalculationRunApproval = { approval_id: string, calculation_run_id: string, run_manifest_sha256: string, rationale: string, approved_by: string, acting_role: string, manifest_sha256: string, created_at: string, };
