// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CalculationRoundingMode = "midpoint_away_from_zero" | "midpoint_nearest_even";
