// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentTaskInputReference } from "./AgentTaskInputReference";
import type { CalculationInputState } from "./CalculationInputState";

export type CalculationDecimalInput = { state: CalculationInputState, value: string | null, evidence: Array<AgentTaskInputReference>, };
