// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CalculationRuleTestResult = { case_name: string, expected_final_amount: string, actual_final_amount: string, passed: boolean, };
