// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalculationDecimalInput } from "./CalculationDecimalInput";
import type { CalculationRoundingMode } from "./CalculationRoundingMode";
import type { ExchangeRateType } from "./ExchangeRateType";

export type CalculationScenarioVersion = { scenario_id: string, version: number, name: string, quantity_unit: string, rate_basis_unit: string, rate_currency: string, exchange_rate_id: string, exchange_rate_version: number, exchange_rate: CalculationDecimalInput, exchange_rate_effective_date: string | null, pricing_date: string, exchange_rate_type: ExchangeRateType | null, output_currency: string, rounding_policy_id: string, rounding_policy_version: number, precision: number, rounding_mode: CalculationRoundingMode, rationale: string, approved_by: string, acting_role: string, manifest_sha256: string, created_at: string, };
