// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalculationRuleReviewFinding } from "./CalculationRuleReviewFinding";
import type { CalculationRuleReviewOutcome } from "./CalculationRuleReviewOutcome";

export type CalculationRuleReview = { review_id: string, reviewer_run_id: string, reviewer_profile_id: string, reviewer_profile_version: number, outcome: CalculationRuleReviewOutcome, findings: Array<CalculationRuleReviewFinding>, manifest_sha256: string, created_at: string, };
