// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalculationRuleVersion } from "./CalculationRuleVersion";
import type { CalculationScenarioVersion } from "./CalculationScenarioVersion";
import type { ControlledBoqCalculationRun } from "./ControlledBoqCalculationRun";

export type CalculationWorkspaceInspection = { rule: CalculationRuleVersion | null, recent_scenarios: Array<CalculationScenarioVersion>, recent_runs: Array<ControlledBoqCalculationRun>, total_scenario_count: number, total_run_count: number, scenario_offset: number, run_offset: number, has_older_scenarios: boolean, has_older_runs: boolean, };
