// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalculationRoundingMode } from "./CalculationRoundingMode";
import type { CalculationRuleApproval } from "./CalculationRuleApproval";
import type { CalculationRuleReview } from "./CalculationRuleReview";
import type { CalculationRuleTestResult } from "./CalculationRuleTestResult";

export type CalculationRuleVersion = { rule_id: string, version: number, name: string, formula: string, engine_version: string, supported_units: Array<string>, supported_currencies: Array<string>, supported_rounding: Array<CalculationRoundingMode>, change_rationale: string, deterministic_tests: Array<CalculationRuleTestResult>, review: CalculationRuleReview | null, approval: CalculationRuleApproval | null, current: boolean, active: boolean, manifest_sha256: string, created_at: string, };
