// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityDemandClassification } from "./CapabilityDemandClassification";
import type { TenderRecordVersionReference } from "./TenderRecordVersionReference";

export type CapabilityDemand = { capability: string, classification: CapabilityDemandClassification, supported: boolean, rationale: string, triggering_record: TenderRecordVersionReference | null, };
