// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CapabilityDemandClassification = "policy_required" | "tender_required" | "risk_recommended" | "manager_added";
