// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChangeAssessmentEvidenceExcerpt = { ordinal: number, kind: string, structural_path: string, original_text: string, translated_text: string | null, language: string, text_sha256: string, truncated: boolean, };
