// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeAssessmentApprovalConsequence } from "./ChangeAssessmentApprovalConsequence";
import type { ChangeAssessmentDecision } from "./ChangeAssessmentDecision";
import type { ChangeAssessmentImpact } from "./ChangeAssessmentImpact";
import type { ChangeAssessmentSource } from "./ChangeAssessmentSource";
import type { ChangeAssessmentStatus } from "./ChangeAssessmentStatus";
import type { SourceRelationshipKind } from "./SourceRelationshipKind";
import type { TenderLifecyclePhase } from "./TenderLifecyclePhase";

export type ChangeAssessment = { assessment_sequence: number, assessment_id: string, relationship_id: string, relationship_kind: SourceRelationshipKind, prior_source: ChangeAssessmentSource, replacement_source: ChangeAssessmentSource, lifecycle_before: TenderLifecyclePhase, status: ChangeAssessmentStatus, baseline_id: string | null, baseline_version: number | null, baseline_manifest_sha256: string | null, impacts: Array<ChangeAssessmentImpact>, affected_commitments: Array<string>, proposed_rework: Array<string>, unchanged_scope: Array<string>, deadline_effect: string, approval_consequences: Array<ChangeAssessmentApprovalConsequence>, decision: ChangeAssessmentDecision | null, resolution_baseline_id: string | null, resolution_baseline_version: number | null, manifest_sha256: string, created_at: string, };
