// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChangeAssessmentObjectKind = "source_artifact" | "tender_record" | "work_plan" | "production_task" | "agent_run" | "production_artifact" | "tender_query" | "calculation_run" | "estimate" | "pricing_decision" | "review" | "coordinated_baseline" | "package" | "approval";
