// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeAssessmentDependencyReference } from "./ChangeAssessmentDependencyReference";
import type { ChangeAssessmentImpactConsequence } from "./ChangeAssessmentImpactConsequence";
import type { ChangeAssessmentImpactKind } from "./ChangeAssessmentImpactKind";

export type ChangeAssessmentImpact = { kind: ChangeAssessmentImpactKind, object_id: string, object_version: number, dependencies: Array<ChangeAssessmentDependencyReference>, consequence: ChangeAssessmentImpactConsequence, summary: string, };
