// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeAssessmentClassification } from "./ChangeAssessmentClassification";
import type { TenderLifecyclePhase } from "./TenderLifecyclePhase";

export type ChangeAssessmentDecision = { classification: ChangeAssessmentClassification, rationale: string, decided_by: string, acting_role: string, lifecycle_after: TenderLifecyclePhase, manifest_sha256: string, created_at: string, };
