// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChangeAssessmentDependencyKind = "source_evidence" | "record_membership" | "task_input" | "run_execution" | "artifact_output" | "query_evidence" | "calculation_input" | "review_target" | "baseline_binding" | "package_binding" | "approval_target";
