// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeAssessmentDependencyKind } from "./ChangeAssessmentDependencyKind";
import type { ChangeAssessmentObjectKind } from "./ChangeAssessmentObjectKind";

export type ChangeAssessmentDependencyReference = { kind: ChangeAssessmentObjectKind, object_id: string, object_version: number, dependency_kind: ChangeAssessmentDependencyKind, };
