// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeAssessment } from "./ChangeAssessment";

export type ChangeAssessmentPage = { active: ChangeAssessment | null, items: Array<ChangeAssessment>, next_before_sequence: number | null, };
