// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeAssessmentEvidenceExcerpt } from "./ChangeAssessmentEvidenceExcerpt";

export type ChangeAssessmentSource = { artifact_id: string, version: number, package_path: string, document_type: string, sha256: string, evidence_count: number, evidence_preview: Array<ChangeAssessmentEvidenceExcerpt>, };
