// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatGptConnectionState } from "./ChatGptConnectionState";

export type ChatGptConnectionStatus = { state: ChatGptConnectionState, account_id: string | null, plan_type: string | null, expires_at_ms: bigint | null, };
