// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChatGptPortHolders = { port_1455: number | null, port_1457: number | null, };
