// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderPackageSourceKind } from "./TenderPackageSourceKind";

export type ChooseTenderPackageCommand = { tender_id: string, source_kind: TenderPackageSourceKind, };
