// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CodexProductionAssuranceEvidence = { production_supported: boolean, evidence_reference: string, evidence_sha256: string, verified_by: string, verified_at: string, expires_at: string, };
