// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommercialStrategyApproval } from "./CommercialStrategyApproval";
import type { PricingAdjustmentReference } from "./PricingAdjustmentReference";

export type CommercialStrategy = { strategy_id: string, tender_revision: number, baseline_id: string, baseline_version: number, reviewed_input: PricingAdjustmentReference, input_review_id: string, input_approval_id: string, commercial_appetite: string, exclusions: Array<string>, qualifications: Array<string>, current: boolean, approval: CommercialStrategyApproval | null, manifest_sha256: string, created_at: string, };
