// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComplianceDisposition } from "./ComplianceDisposition";
import type { TenderRecordVersionReference } from "./TenderRecordVersionReference";

export type ComplianceDispositionUpdate = { record: TenderRecordVersionReference, disposition: ComplianceDisposition, responsibility: string, planned_treatment: string, affected_work: Array<string>, uncertainty: string | null, related_records: Array<TenderRecordVersionReference>, };
