// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComplianceMatrixRow } from "./ComplianceMatrixRow";

export type ComplianceMatrixPage = { rows: Array<ComplianceMatrixRow>, next_ordinal: number | null, };
