// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ComplianceDisposition = "comply" | "comply_with_qualification" | "deviation" | "not_applicable" | "unresolved";
