// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderReasoningSelection } from "./ProviderReasoningSelection";

export type ConfirmAiExecutionSelectionCommand = { connection_id: string, model_id: string, reasoning: ProviderReasoningSelection, };
