// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContentVersionSummary = { logical_id: string, revision: number, sha256: string, size_bytes: bigint, media_type: string, };
