// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControlledBoqCalculationStatus = "completed" | "missing_input" | "unavailable_input" | "ambiguous_input" | "invalid_input" | "dimension_mismatch";
