// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CoordinatedBidBaselineBlockerCode = "production_task_not_ready" | "open_critical_finding" | "open_major_finding" | "open_material_query" | "stale_input" | "unverified_input" | "capability_gap" | "unreconciled_calculation" | "priced_cost_baseline_missing" | "approved_tender_price_missing" | "workstream_evidence_missing" | "contradiction_open";
