// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoordinatedBidBaselineContradictionCategory } from "./CoordinatedBidBaselineContradictionCategory";

export type CoordinatedBidBaselineContradiction = { category: CoordinatedBidBaselineContradictionCategory, key: string, summary: string, references: Array<string>, };
