// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CoordinatedBidBaselineBindingKind = "production_artifact_version" | "tender_record_version" | "tender_query_version" | "external_rfi_version" | "priced_cost_baseline" | "approved_tender_price" | "calculation_manifest" | "commercial_strategy";
