// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoordinatedBidBaselineDecision } from "./CoordinatedBidBaselineDecision";
import type { TenderLifecyclePhase } from "./TenderLifecyclePhase";

export type CoordinatedBidBaselineApproval = { approval_id: string, baseline_id: string, baseline_version: number, baseline_manifest_sha256: string, decision: CoordinatedBidBaselineDecision, rationale: string, conditions: Array<string>, exceptions: Array<string>, supporting_reviews_sha256: string, decided_by: string, acting_role: string, lifecycle_before: TenderLifecyclePhase, lifecycle_after: TenderLifecyclePhase, preceding_approval_hash: string, approval_sha256: string, created_at: string, };
