// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoordinatedBidBaseline } from "./CoordinatedBidBaseline";
import type { TenderLifecyclePhase } from "./TenderLifecyclePhase";

export type CoordinatedBidBaselinePage = { items: Array<CoordinatedBidBaseline>, next_before_version: number | null, lifecycle_phase: TenderLifecyclePhase, };
