// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoordinatedBidBaselineBlockerCode } from "./CoordinatedBidBaselineBlockerCode";

export type CoordinatedBidBaselineBlocker = { code: CoordinatedBidBaselineBlockerCode, summary: string, references: Array<string>, };
