// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoordinatedBidBaselineBindingKind } from "./CoordinatedBidBaselineBindingKind";
import type { CoordinatedBidBaselineCategory } from "./CoordinatedBidBaselineCategory";

export type CoordinatedBidBaselineBinding = { category: CoordinatedBidBaselineCategory, kind: CoordinatedBidBaselineBindingKind, reference_id: string, version: number, manifest_sha256: string, source: string, summary: string, supporting_review_id: string | null, approval_id: string | null, };
