// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoordinatedBidBaselineApproval } from "./CoordinatedBidBaselineApproval";
import type { CoordinatedBidBaselineBinding } from "./CoordinatedBidBaselineBinding";
import type { CoordinatedBidBaselineBlocker } from "./CoordinatedBidBaselineBlocker";
import type { CoordinatedBidBaselineContradiction } from "./CoordinatedBidBaselineContradiction";

export type CoordinatedBidBaseline = { baseline_id: string, version: number, tender_revision: number, activation_id: string, plan_id: string, plan_version: number, plan_manifest_sha256: string, coordinator_profile_id: string, coordinator_profile_version: number, bindings: Array<CoordinatedBidBaselineBinding>, contradictions: Array<CoordinatedBidBaselineContradiction>, blockers: Array<CoordinatedBidBaselineBlocker>, explanation: string, preceding_version_manifest_sha256: string | null, approval: CoordinatedBidBaselineApproval | null, current: boolean, manifest_sha256: string, created_at: string, };
