// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CostComponentCategory } from "./CostComponentCategory";

export type CostBreakdownComponent = { component_id: string, cost_code: string, work_package: string, category: CostComponentCategory, description: string, boq_row_keys: Array<string>, resource_build_up_ids: Array<string>, };
