// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRunInspection } from "./AgentRunInspection";
import type { ControlledBoqCalculationRun } from "./ControlledBoqCalculationRun";

export type CostEstimatorCalculationResult = { run: AgentRunInspection, calculation: ControlledBoqCalculationRun | null, };
