// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatePricedCostBaselineCommand = { tender_id: string, basis_id: string, basis_version: number, basis_manifest_sha256: string, rationale: string, };
