// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PricingAdjustmentReference } from "./PricingAdjustmentReference";

export type CreatePricingScenarioCommand = { tender_id: string, name: string, baseline_id: string, baseline_version: number, baseline_manifest_sha256: string, strategy_id: string, strategy_manifest_sha256: string, adjustments: Array<PricingAdjustmentReference>, };
