// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComplianceDispositionUpdate } from "./ComplianceDispositionUpdate";
import type { ManagerCapabilityDemandInput } from "./ManagerCapabilityDemandInput";

export type CreateBidDecisionPackageCommand = { tender_id: string, base_version: number | null, disposition_updates: Array<ComplianceDispositionUpdate>, manager_capability_demands: Array<ManagerCapabilityDemandInput>, };
