// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PricingAdjustmentDirection } from "./PricingAdjustmentDirection";
import type { PricingAdjustmentKind } from "./PricingAdjustmentKind";
import type { PricingAdjustmentReference } from "./PricingAdjustmentReference";

export type CreatePricingAdjustmentCommand = { tender_id: string, baseline_id: string, baseline_version: number, baseline_manifest_sha256: string, calculation_run_id: string, calculation_manifest_sha256: string, kind: PricingAdjustmentKind, direction: PricingAdjustmentDirection, scope: string, rationale: string, commercial_appetite: string | null, exclusions: Array<string>, qualifications: Array<string>, remediates: Array<PricingAdjustmentReference>, };
