// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalculationDecimalInput } from "./CalculationDecimalInput";
import type { CalculationRoundingMode } from "./CalculationRoundingMode";
import type { ExchangeRateType } from "./ExchangeRateType";

export type CreateCalculationScenarioCommand = { tender_id: string, name: string, quantity_unit: string, rate_basis_unit: string, rate_currency: string, exchange_rate: CalculationDecimalInput, exchange_rate_effective_date: string | null, pricing_date: string, exchange_rate_type: ExchangeRateType | null, output_currency: string, precision: number, rounding_mode: CalculationRoundingMode, rationale: string, };
