// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentTaskInputReference } from "./AgentTaskInputReference";
import type { DataClassification } from "./DataClassification";

export type DataViewManifest = { view_id: string, schema_version: number, relative_path: string, sha256: string, data_scope: string, data_classification: DataClassification, exact_inputs: Array<AgentTaskInputReference>, };
