// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DecisionFactKind = "agent_recommendation" | "verified_fact" | "approved_assumption" | "deterministic_result" | "unresolved_gap" | "prior_engineer_decision";
