// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecisionEvidence } from "./DecisionEvidence";
import type { DecisionFactKind } from "./DecisionFactKind";

export type DecisionFact = { kind: DecisionFactKind, label: string, value: string, evidence: Array<DecisionEvidence>, };
