// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderQueryTreatment } from "./TenderQueryTreatment";

export type DecideTenderQueryTreatmentCommand = { tender_id: string, query_id: string, query_version: number, treatment: TenderQueryTreatment, rationale: string, treatment_details: string, closes_query: boolean, };
