// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoordinatedBidBaselineDecision } from "./CoordinatedBidBaselineDecision";

export type DecideCoordinatedBidBaselineCommand = { tender_id: string, baseline_id: string, version: number, manifest_sha256: string, decision: CoordinatedBidBaselineDecision, rationale: string, conditions: Array<string>, exceptions: Array<string>, };
