// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeAssessmentClassification } from "./ChangeAssessmentClassification";

export type DecideChangeAssessmentCommand = { tender_id: string, assessment_id: string, assessment_manifest_sha256: string, classification: ChangeAssessmentClassification, rationale: string, };
