// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecisionTargetKind } from "./DecisionTargetKind";

export type DecisionTarget = { kind: DecisionTargetKind, object_id: string, version: number, manifest_sha256: string | null, };
