// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BidDecisionApprovalDecision } from "./BidDecisionApprovalDecision";

export type DecideBidDecisionPackageCommand = { tender_id: string, package_id: string, version: number, manifest_sha256: string, decision: BidDecisionApprovalDecision, rationale: string, conditions: Array<string>, exceptions: Array<string>, required_rework: Array<string>, };
