// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateDecision } from "./UpdateDecision";

export type DecideUpdateCommand = { update_id: string, decision: UpdateDecision, rationale: string, };
