// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecisionResponsibleKind } from "./DecisionResponsibleKind";

export type DecisionResponsible = { kind: DecisionResponsibleKind, label: string, profile_id: string | null, profile_version: number | null, };
