// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DecisionAction = "accept" | "approve" | "return" | "reject" | "verify" | "approve_assumption" | "apply_treatment" | "classify_irrelevant" | "classify_material" | "select" | "approve_exception" | "retry_task" | "close_task" | "approve_replacement";
