// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DecisionEvidence = { artifact_id: string, version: number, location_ordinal: number | null, label: string, original_text: string | null, translated_text: string | null, };
