// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkPlanDecision } from "./WorkPlanDecision";

export type DecideWorkPlanProposalCommand = { tender_id: string, plan_id: string, version: number, decision: WorkPlanDecision, rationale: string, };
