// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecisionDependencyStatus } from "./DecisionDependencyStatus";
import type { DecisionTarget } from "./DecisionTarget";

export type DecisionDependency = { target: DecisionTarget, label: string, status: DecisionDependencyStatus, };
