// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PendingDecision } from "./PendingDecision";
import type { TenderLifecyclePhase } from "./TenderLifecyclePhase";

export type DecisionCockpit = { tender_id: string, tender_revision: number, lifecycle_phase: TenderLifecyclePhase, pending_decisions: Array<PendingDecision>, };
