// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DecisionLifecycleGate = "evidence_governance" | "bid_decision" | "work_plan_approval" | "query_control" | "external_issue" | "calculation_governance" | "estimate_approval" | "commercial_approval" | "production_assurance" | "integrated_review" | "change_assessment" | "access_control" | "recovery";
