// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecisionStatus } from "./DecisionStatus";
import type { DecisionTarget } from "./DecisionTarget";

export type DecisionGroupMember = { target: DecisionTarget, condition: string, status: DecisionStatus, };
