// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderRecordEngineerDecisionKind } from "./TenderRecordEngineerDecisionKind";

export type DecideTenderRecordCommand = { tender_id: string, record_id: string, version: number, decision: TenderRecordEngineerDecisionKind, rationale: string, };
