// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeepDiagnosticsSession = { session_id: string, tender_id: string, started_at: string, expires_at: string, bytes_written: bigint, cap_bytes: bigint, active: boolean, };
