// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeletionReceipt = { receipt_id: string, deletion_id: string, tender_id: string, audit_event_count: bigint, audit_chain_head: string, purged_by: string, acting_role: string, purged_at: string, manifest_sha256: string, };
