// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErasedTenderCopyClass } from "./ErasedTenderCopyClass";
import type { ProviderCleanupStatus } from "./ProviderCleanupStatus";

export type DeletionReceipt = { receipt_id: string, deletion_id: string, tender_id: string, audit_event_count: bigint, audit_chain_head: string, local_deletion_completed: boolean, erased_copy_classes: Array<ErasedTenderCopyClass>, provider_cleanup_status: ProviderCleanupStatus, provider_thread_count: number, confirmed_provider_thread_deletions: number, external_copy_exclusions: Array<string>, purged_by: string, acting_role: string, purged_at: string, manifest_sha256: string, };
