// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticTimelineEvent } from "./DiagnosticTimelineEvent";

export type DiagnosticTimelinePage = { events: Array<DiagnosticTimelineEvent>, next_cursor: string | null, has_more: boolean, snapshot: string, };
