// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticsDeepState } from "./DiagnosticsDeepState";

export type DiagnosticsDeepStatus = { state: DiagnosticsDeepState, session_id: string | null, started_at: string | null, ends_at: string | null, remaining_seconds: bigint | null, detail: string | null, };
