// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticScope } from "./DiagnosticScope";
import type { DiagnosticSeverity } from "./DiagnosticSeverity";

/**
 * Renderer-facing timeline projection. Raw journal records stay private to
 * the host and are converted to this safe display shape at the boundary.
 */
export type DiagnosticTimelineEvent = { event_id: string, occurred_at: string, severity: DiagnosticSeverity, component: string, title: string, detail: string | null, scope: DiagnosticScope, operation_id: string | null, parent_operation_id: string | null, outcome: string | null, error_code: string | null, };
