// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticScope } from "./DiagnosticScope";
import type { DiagnosticsDeepStatus } from "./DiagnosticsDeepStatus";
import type { DiagnosticsStatusState } from "./DiagnosticsStatusState";

export type DiagnosticsStatus = { scope: DiagnosticScope, tender_id: string | null, state: DiagnosticsStatusState, retention_days: number | null, retained_bytes: bigint, retention_limit_bytes: bigint, retained_event_count: number | null, dropped_event_count: number, degraded_reason: string | null, checked_at: string, deep: DiagnosticsDeepStatus, component: string | null, };
