// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiagnosticSupportBundleResult = { path: string, sha256: string, contains_deep_events: boolean, sensitive_data: boolean, truncated: boolean, };
