// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticComponent } from "./DiagnosticComponent";
import type { DiagnosticScope } from "./DiagnosticScope";
import type { DiagnosticSeverity } from "./DiagnosticSeverity";

export type DiagnosticTimelineFilter = { scope: DiagnosticScope | null, severity: DiagnosticSeverity | null, component: DiagnosticComponent | null, tender_id: string | null, };
