// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiagnosticHealth = { enabled: boolean, degraded: boolean, writer_error: string | null, dropped_normal: bigint, dropped_critical: bigint, retained_bytes: bigint, retained_files: bigint, deep_active_tender: string | null, deep_remaining_seconds: bigint | null, deep_bytes: bigint, };
