// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiagnosticCorrelation = { operation_id: string | null, parent_operation_id: string | null, tender_id: string | null, run_id: string | null, task_id: string | null, };
