// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticComponent } from "./DiagnosticComponent";
import type { DiagnosticCorrelation } from "./DiagnosticCorrelation";
import type { DiagnosticScope } from "./DiagnosticScope";
import type { DiagnosticSeverity } from "./DiagnosticSeverity";

export type DiagnosticEvent = { schema_version: number, timestamp: string, severity: DiagnosticSeverity, scope: DiagnosticScope, component: DiagnosticComponent, event_name: string, summary: string, session_sequence: bigint, correlation: DiagnosticCorrelation, duration_ms: bigint | null, outcome: string | null, error_code: string | null, deep: boolean, request_id: string | null, size_bytes: bigint | null, redaction_count: number, original_error_event: string | null, initiated_by: string | null, action: string | null, success: boolean | null, };
