// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentRegisterEntry } from "./DocumentRegisterEntry";

export type DocumentRegister = { query_register_open: boolean, documents: Array<DocumentRegisterEntry>, };
