// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IntakeExceptionCode } from "./IntakeExceptionCode";
import type { RegistrationState } from "./RegistrationState";
import type { SupersessionState } from "./SupersessionState";

export type DocumentRegisterEntry = { artifact_id: string, version: number, package_path: string, language: string, document_type: string, media_type: string | null, sha256: string | null, size_bytes: bigint, registration_state: RegistrationState, supersession_state: SupersessionState, exception: IntakeExceptionCode | null, };
