// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvidenceLanguage } from "./EvidenceLanguage";
import type { ParseExceptionCode } from "./ParseExceptionCode";
import type { ParseState } from "./ParseState";
import type { TextDirection } from "./TextDirection";

export type DocumentParseResult = { attempt_id: string, artifact_id: string, version: number, state: ParseState, exception: ParseExceptionCode | null, location_count: number, language: EvidenceLanguage, direction: TextDirection, docling_schema_version: string | null, docling_json_sha256: string | null, };
