// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ErasedTenderCopyClass = "tender_store" | "tender_backup" | "portable_tender_archive" | "delivery_export" | "agent_run_workspace" | "staging_item" | "quarantine_item" | "tender_log";
