// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EstimateAggregateCalculationInput = { build_up_id: string, cbs_component_id: string, calculation_run_id: string, calculation_manifest_sha256: string, amount: string, currency: string, };
