// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalculationRoundingMode } from "./CalculationRoundingMode";
import type { EstimateAggregateCalculationInput } from "./EstimateAggregateCalculationInput";

export type EstimateAggregateCalculationRun = { aggregate_run_id: string, author_run_id: string, comparison_total_calculation_run_id: string, comparison_total_manifest_sha256: string, comparison_total_amount: string, rule_id: string, rule_version: number, rule_approval_id: string, scenario_id: string, scenario_version: number, precision: number, rounding_mode: CalculationRoundingMode, engine_version: string, inputs: Array<EstimateAggregateCalculationInput>, final_amount: string, currency: string, manifest_sha256: string, approved_for_reliance: boolean, };
