// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EstimateQuotationKind } from "./EstimateQuotationKind";
import type { TenderEvidenceReference } from "./TenderEvidenceReference";

export type EstimateQuotation = { quotation_id: string, kind: EstimateQuotationKind, counterparty: string, exact_scope: string, quotation_date: string, currency: string, exclusions: Array<string>, valid_until: string, evidence: TenderEvidenceReference, normalization_calculation_run_id: string, covered_boq_row_keys: Array<string>, comparison_assumptions: Array<string>, };
