// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderEvidenceReference } from "./TenderEvidenceReference";

export type EstimateAllowance = { allowance_id: string, description: string, cbs_component_id: string, resource_build_up_id: string, query_id: string, query_version: number, decision_id: string, evidence: Array<TenderEvidenceReference>, rationale: string, };
