// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BasisOfEstimateVersion } from "./BasisOfEstimateVersion";
import type { BoqTableCandidate } from "./BoqTableCandidate";

export type EstimateWorkspaceInspection = { basis: BasisOfEstimateVersion | null, boq_table_candidates: Array<BoqTableCandidate>, boq_table_candidate_next_cursor: string | null, basis_offset: number, total_basis_version_count: number, has_newer_basis: boolean, has_older_basis: boolean, };
