// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CostComponentCategory } from "./CostComponentCategory";

export type EstimateResourceBuildUp = { build_up_id: string, cbs_component_id: string, category: CostComponentCategory, description: string, calculation_run_id: string, };
