// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderQueryTreatment } from "./TenderQueryTreatment";

export type EstimateMaterialAssumption = { query_id: string, query_version: number, decision_id: string, treatment: TenderQueryTreatment, rationale: string, treatment_details: string, manifest_sha256: string, };
