// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcceptanceArtifactHash } from "./AcceptanceArtifactHash";
import type { CodexProductionAssuranceEvidence } from "./CodexProductionAssuranceEvidence";
import type { IntegrationTermsDecision } from "./IntegrationTermsDecision";
import type { LicenseDistributionReview } from "./LicenseDistributionReview";
import type { NativePlatformQualificationRecord } from "./NativePlatformQualificationRecord";
import type { TechnicalRiskAcceptance } from "./TechnicalRiskAcceptance";

export type EvaluatePublicReleaseGateCommand = { release_candidate_manifest_sha256: string, private_windows_candidate_binary_sha256: string, private_qualification_sha256: string, native_platforms: Array<NativePlatformQualificationRecord>, license_review: LicenseDistributionReview, codex_production_assurance: CodexProductionAssuranceEvidence, integration_terms: IntegrationTermsDecision, technical_risks: Array<TechnicalRiskAcceptance>, release_artifacts: Array<AcceptanceArtifactHash>, approver: string, };
