// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvidenceBoundingBox } from "./EvidenceBoundingBox";

export type EvidenceRegion = { page_number: number, char_start: number | null, char_end: number | null, bounding_box: EvidenceBoundingBox | null, };
