// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvidenceSearchHit } from "./EvidenceSearchHit";

export type EvidenceSearchResult = { query: string, matches: Array<EvidenceSearchHit>, };
