// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvidenceSemanticSearchHit } from "./EvidenceSemanticSearchHit";

export type EvidenceSemanticSearchResult = { query: string, matches: Array<EvidenceSemanticSearchHit>, };
