// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvidenceLanguage } from "./EvidenceLanguage";
import type { EvidenceLocationKind } from "./EvidenceLocationKind";
import type { EvidenceRegion } from "./EvidenceRegion";
import type { TextDirection } from "./TextDirection";

export type EvidenceLocation = { ordinal: number, kind: EvidenceLocationKind, structural_path: string, provenance: Array<EvidenceRegion>, section: string | null, paragraph_number: number | null, table_number: number | null, sheet_name: string | null, cell_range: string | null, original_text: string, translated_text: string | null, language: EvidenceLanguage, direction: TextDirection, };
