// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvidenceLocation } from "./EvidenceLocation";

export type EvidenceSearchHit = { artifact_id: string, version: number, package_path: string, location: EvidenceLocation, };
