// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EvidenceBoundingBox = { left: number, top: number, right: number, bottom: number, coordinate_origin: string, };
