// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExportReleaseCopyCommand = { tender_id: string, approval_id: string, approval_manifest_sha256: string, };
