// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticScope } from "./DiagnosticScope";

export type ExportDiagnosticsSupportBundleCommand = { scope: DiagnosticScope, tender_id: string | null, include_deep: boolean, policy_revision: number, };
