// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalRfiDraft } from "./ExternalRfiDraft";

export type ExternalRfiPage = { items: Array<ExternalRfiDraft>, next_cursor: string | null, total_current_count: number, approved_for_issue_count: number, };
