// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExternalRfiExportRecord = { export_id: string, approval_id: string, path: string, bytes_sha256: string, size_bytes: bigint, bytes_verified: boolean, manifest_sha256: string, created_at: string, };
