// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExternalRfiQuestion = { query_id: string, query_version: number, question: string, ambiguity_or_gap: string, };
