// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentTaskInputReference } from "./AgentTaskInputReference";
import type { ExternalRfiApproval } from "./ExternalRfiApproval";
import type { ExternalRfiExportRecord } from "./ExternalRfiExportRecord";
import type { ExternalRfiQueryReference } from "./ExternalRfiQueryReference";
import type { ExternalRfiQuestion } from "./ExternalRfiQuestion";
import type { ExternalRfiRecipient } from "./ExternalRfiRecipient";
import type { ExternalRfiResponseInterpretation } from "./ExternalRfiResponseInterpretation";
import type { ExternalRfiResponseLink } from "./ExternalRfiResponseLink";
import type { ExternalRfiReview } from "./ExternalRfiReview";

export type ExternalRfiDraft = { rfi_id: string, version: number, query_refs: Array<ExternalRfiQueryReference>, current_query_refs: Array<ExternalRfiQueryReference>, questions: Array<ExternalRfiQuestion>, source_evidence: Array<AgentTaskInputReference>, contractual_context: string, response_need: string, attachments: Array<AgentTaskInputReference>, due_at: string, recipient: ExternalRfiRecipient, affected_task_keys: Array<string>, affected_commitments: Array<string>, review: ExternalRfiReview | null, approval: ExternalRfiApproval | null, exports: Array<ExternalRfiExportRecord>, responses: Array<ExternalRfiResponseLink>, interpretations: Array<ExternalRfiResponseInterpretation>, current: boolean, evidence_current: boolean, revision_allowed: boolean, approved_for_issue: boolean, manifest_sha256: string, created_at: string, };
