// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExternalRfiResponseCandidate = { source_artifact_id: string, source_artifact_version: number, package_path: string, };
