// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExternalRfiResponseInterpretation = { interpretation_id: string, response_link_id: string, query_id: string, source_query_version: number, base_query_version: number, resulting_query_version: number, query_decision_id: string, material: boolean, interpretation: string, decided_by: string, acting_role: string, manifest_sha256: string, created_at: string, };
