// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalRfiEligibleQuery } from "./ExternalRfiEligibleQuery";

export type ExternalRfiEligibleQueryPage = { items: Array<ExternalRfiEligibleQuery>, next_cursor: string | null, total_count: number, };
