// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExternalRfiResponseLink = { response_link_id: string, rfi_id: string, rfi_version: number, approval_id: string, source_artifact_id: string, source_artifact_version: number, registered_by: string, manifest_sha256: string, created_at: string, };
