// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExternalRfiApproval = { approval_id: string, rfi_id: string, rfi_version: number, rfi_manifest_sha256: string, review_id: string, review_manifest_sha256: string, rationale: string, approved_by: string, acting_role: string, approval_sha256: string, created_at: string, };
