// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentTaskInputReference } from "./AgentTaskInputReference";
import type { ExternalRfiFindingSeverity } from "./ExternalRfiFindingSeverity";

export type ExternalRfiReviewFinding = { severity: ExternalRfiFindingSeverity, code: string, summary: string, evidence_references: Array<AgentTaskInputReference>, };
