// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalRfiReviewFinding } from "./ExternalRfiReviewFinding";
import type { ExternalRfiReviewOutcome } from "./ExternalRfiReviewOutcome";

export type ExternalRfiReview = { review_id: string, rfi_id: string, rfi_version: number, rfi_manifest_sha256: string, reviewer_run_id: string, reviewer_profile_id: string, reviewer_profile_version: number, outcome: ExternalRfiReviewOutcome, findings: Array<ExternalRfiReviewFinding>, manifest_sha256: string, created_at: string, };
