// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalRfiQueryReference } from "./ExternalRfiQueryReference";

export type ExternalRfiEligibleQuery = { query_ref: ExternalRfiQueryReference, question: string, ambiguity_or_gap: string, due_at: string, affected_task_keys: Array<string>, };
