// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalRfiResponseCandidate } from "./ExternalRfiResponseCandidate";

export type ExternalRfiResponseCandidatePage = { items: Array<ExternalRfiResponseCandidate>, next_cursor: string | null, };
