// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExternalRfiQueryReference = { query_id: string, version: number, manifest_sha256: string, };
