// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FinalReviewReviewer } from "./FinalReviewReviewer";
import type { SubmissionPackageDependency } from "./SubmissionPackageDependency";
import type { SubmissionProfileVersionReference } from "./SubmissionProfileVersionReference";

export type FinalReviewAssignment = { assignment_id: string, section_key: string, envelope_key: string, language: string, item_ids: Array<string>, required_capability: string, risk_references: Array<SubmissionPackageDependency>, author_profile_versions: Array<SubmissionProfileVersionReference>, reviewer: FinalReviewReviewer | null, criteria: Array<string>, };
