// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoordinatedBidBaselineBinding } from "./CoordinatedBidBaselineBinding";
import type { FinalReviewDecisionEvidenceCategory } from "./FinalReviewDecisionEvidenceCategory";

export type FinalReviewDecisionEvidence = { category: FinalReviewDecisionEvidenceCategory, binding: CoordinatedBidBaselineBinding, question: string | null, ambiguity_or_gap: string | null, treatment: string | null, rationale: string | null, treatment_details: string | null, closed: boolean | null, };
