// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FinalReviewPlan } from "./FinalReviewPlan";
import type { PackageFindingExceptionApproval } from "./PackageFindingExceptionApproval";
import type { PackageManualVerification } from "./PackageManualVerification";
import type { PackageValidationPolicy } from "./PackageValidationPolicy";
import type { PackageValidationRun } from "./PackageValidationRun";
import type { ReleaseReadinessBlocker } from "./ReleaseReadinessBlocker";
import type { ReleaseReadinessReport } from "./ReleaseReadinessReport";
import type { SubmissionPackageCurrentnessFact } from "./SubmissionPackageCurrentnessFact";
import type { SubmissionPackageVersion } from "./SubmissionPackageVersion";
import type { SubmissionSectionReview } from "./SubmissionSectionReview";

export type FinalReviewInspection = { package: SubmissionPackageVersion, policy: PackageValidationPolicy, validation_run: PackageValidationRun, manual_verifications: Array<PackageManualVerification>, review_plan: FinalReviewPlan, reviews: Array<SubmissionSectionReview>, exceptions: Array<PackageFindingExceptionApproval>, report: ReleaseReadinessReport, current: boolean, ready: boolean, live_blockers: Array<ReleaseReadinessBlocker>, live_changes: Array<SubmissionPackageCurrentnessFact>, };
