// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FinalReviewAssignment } from "./FinalReviewAssignment";

export type FinalReviewPlan = { plan_id: string, package_id: string, package_version: number, package_manifest_sha256: string, validation_run_id: string, policy_manifest_sha256: string, assignments: Array<FinalReviewAssignment>, manifest_sha256: string, created_at: string, };
