// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GenerationAuthoringMode = "docx" | "xlsx" | "unchanged_source" | "unsupported";
