// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GenerationRequirementKind = "mandatory_requirement" | "deliverable" | "addendum_instruction" | "signature" | "form_field" | "execution_requirement" | "required_file";
