// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GenerateSubmissionSectionsCommand = { tender_id: string, baseline_id: string, baseline_version: number, baseline_manifest_sha256: string, };
