// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenerationAuthoringMode } from "./GenerationAuthoringMode";
import type { GenerationRequirementKind } from "./GenerationRequirementKind";
import type { GenerationRequirementRecordReference } from "./GenerationRequirementRecordReference";
import type { SubmissionGeneratedArtifactReference } from "./SubmissionGeneratedArtifactReference";
import type { SubmissionSourceArtifactReference } from "./SubmissionSourceArtifactReference";
import type { TenderRecordEvidence } from "./TenderRecordEvidence";
import type { TenderRecordField } from "./TenderRecordField";

export type GenerationRequirement = { requirement_id: string, kind: GenerationRequirementKind, record: GenerationRequirementRecordReference, evidence: Array<TenderRecordEvidence>, authored_fields: Array<TenderRecordField>, mandatory: boolean, section_key: string, package_path: string, envelope_key: string, language: string, authoring_mode: GenerationAuthoringMode, generated_artifact: SubmissionGeneratedArtifactReference | null, unchanged_source_artifact: SubmissionSourceArtifactReference | null, content_sha256: string, size_bytes: bigint, calculation_references: Array<string>, review_references: Array<string>, decision_references: Array<string>, manifest_sha256: string, };
