// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppearancePreference } from "./AppearancePreference";

export type GeneralApplicationPreferences = { appearance: AppearancePreference, reduced_motion: boolean, high_contrast: boolean, larger_text: boolean, notify_when_attention_needed: boolean, };
