// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BidDecisionPackageRecordCategory } from "./BidDecisionPackageRecordCategory";

export type InspectBidDecisionPackageRecordsCommand = { tender_id: string, package_id: string, version: number, category: BidDecisionPackageRecordCategory, after_ordinal: number | null, limit: number, };
