// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InspectChangeAssessmentsCommand = { tender_id: string, before_sequence: number | null, limit: number, };
