// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InspectEstimateWorkspaceCommand = { tender_id: string, basis_offset: number, boq_candidate_cursor: string | null, };
