// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InspectCalculationWorkspaceCommand = { tender_id: string, scenario_offset: number, run_offset: number, };
