// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticScope } from "./DiagnosticScope";
import type { DiagnosticSeverity } from "./DiagnosticSeverity";

export type InspectDiagnosticTimelineCommand = { scope: DiagnosticScope, tender_id: string | null, cursor: string | null, limit: number | null, severity: DiagnosticSeverity | null, component: string | null, };
