// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InspectTenderRecordCommand = { tender_id: string, record_id: string, version: number, };
