// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InspectAgentRunHistoryCommand = { tender_id: string, before_sequence: bigint | null, limit: number, };
