// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InspectTenderQueriesCommand = { tender_id: string, cursor: string | null, limit: number, };
