// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IntakeExceptionCode = "corrupt" | "disk_space_insufficient" | "duplicate_path" | "duration_exceeded" | "encrypted" | "entry_count_exceeded" | "expansion_ratio_exceeded" | "file_size_exceeded" | "macro_bearing" | "memory_limit_exceeded" | "nested_archive" | "nesting_exceeded" | "path_too_long" | "registration_failed" | "total_size_exceeded" | "unsafe_link" | "unsafe_path" | "unsupported";
