// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IntegrationTermsDecision = { third_party_subscription_integration_authorized: boolean, terms_reference: string, terms_sha256: string, decided_by: string, decided_at: string, expires_at: string, };
