// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderQueryTreatment } from "./TenderQueryTreatment";

export type InterpretExternalRfiResponseCommand = { tender_id: string, response_link_id: string, query_id: string, issued_query_version: number, base_query_version: number, base_query_manifest_sha256: string, material: boolean, interpretation: string, treatment: TenderQueryTreatment, rationale: string, treatment_details: string, closes_query: boolean, };
