// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InvalidateBidDecisionApprovalCommand = { tender_id: string, approval_id: string, approval_sha256: string, material_change_summary: string, affected_areas: Array<string>, };
