// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LicenseDistributionReview = { inventory_sha256: string, reviewed_categories: Array<string>, passed: boolean, findings: Array<string>, reviewed_by: string, reviewed_at: string, expires_at: string, };
