// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LiveQualificationMetrics = { critical_recall_percent: number, unsupported_critical_count: number, boq_accounting_percent: number, calculation_reproduction_percent: number, material_provenance_percent: number, non_critical_recall_percent: number, hard_gate_violations: number, };
