// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManagedCodexRuntimeState } from "./ManagedCodexRuntimeState";

export type ManagedCodexRuntimeStatus = { state: ManagedCodexRuntimeState, version: string | null, summary: string, };
