// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderLifecyclePhase } from "./TenderLifecyclePhase";

export type ManagerWorkspaceTender = { tender_id: string, name: string, revision: number, phase: TenderLifecyclePhase, needs_engineer: boolean, available: boolean, last_activity_at: string | null, };
