// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ManagedWorkerRuntimeState = "ready" | "not_installed" | "interrupted_preparation" | "outdated" | "install_failed";
