// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ManagerIntakeStage = "waiting_for_local_tools" | "waiting_for_provider_approval" | "waiting_for_provider" | "package_registered" | "reading_documents" | "extracting_tender_facts" | "reviewing_tender_facts" | "preparing_first_decision" | "waiting_for_engineer" | "bid_decision_ready" | "failed";
