// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManagerIntakeStage } from "./ManagerIntakeStage";
import type { ManagerIntakeStatusKind } from "./ManagerIntakeStatusKind";

export type ManagerIntakeStatus = { intake_run_id: string, stage: ManagerIntakeStage, status: ManagerIntakeStatusKind, label: string, summary: string, parseable_document_count: number, parsed_document_count: number, extraction_run_count: number, };
