// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderOfficeMessage } from "./TenderOfficeMessage";

export type ManagerConversation = { conversation_id: string, messages: Array<TenderOfficeMessage>, latest_meaningful_message_id: string | null, };
