// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManagedWorkerRuntimeState } from "./ManagedWorkerRuntimeState";

export type ManagedWorkerRuntimeStatus = { state: ManagedWorkerRuntimeState, lock_sha256: string | null, summary: string, };
