// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderRecordVersionReference } from "./TenderRecordVersionReference";

export type ManagerCapabilityDemandInput = { capability: string, rationale: string, triggering_record: TenderRecordVersionReference | null, };
