// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NativePlatformQualificationEvidence } from "./NativePlatformQualificationEvidence";

export type NativePlatformQualificationRecord = { record_id: string, evidence: NativePlatformQualificationEvidence, blockers: Array<string>, passed: boolean, manifest_sha256: string, created_at: string, };
