// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenerationRequirement } from "./GenerationRequirement";
import type { SubmissionArtifactVersion } from "./SubmissionArtifactVersion";

export type PackageProductionGeneration = { generation_id: string, sequence: number, baseline_id: string, baseline_version: number, baseline_manifest_sha256: string, artifact_versions: Array<SubmissionArtifactVersion>, requirements: Array<GenerationRequirement>, manifest_sha256: string, created_at: string, };
