// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PackageIntakeStage = "checking_source" | "reading_package" | "recording_documents" | "opening_workspace";
