// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProductionFindingSeverity } from "./ProductionFindingSeverity";

export type PackageReviewFinding = { finding_id: string, review_id: string, sequence: number, severity: ProductionFindingSeverity, policy_rule_id: string, summary: string, evidence_references: Array<string>, created_at: string, };
