// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageValidationRule } from "./PackageValidationRule";

export type PackageValidationPolicy = { policy_id: string, version: number, fixed_rules: Array<PackageValidationRule>, tender_rules: Array<PackageValidationRule>, manifest_sha256: string, created_at: string, };
