// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PackageFindingExceptionApproval = { approval_id: string, finding_id: string, package_id: string, package_version: number, package_manifest_sha256: string, decided_by: string, acting_role: string, rationale: string, manifest_sha256: string, created_at: string, };
