// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageValidationResult } from "./PackageValidationResult";

export type PackageValidationRun = { run_id: string, package_id: string, package_version: number, package_manifest_sha256: string, policy_id: string, policy_version: number, policy_manifest_sha256: string, validator_version: number, renderer_version: number, context_sha256: string, results: Array<PackageValidationResult>, manifest_sha256: string, created_at: string, };
