// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageValidationCheckCategory } from "./PackageValidationCheckCategory";
import type { PackageValidationOutcome } from "./PackageValidationOutcome";

export type PackageValidationResult = { result_id: string, item_id: string | null, content_sha256: string | null, validation_context_sha256: string, check_id: string, check_version: number, category: PackageValidationCheckCategory, outcome: PackageValidationOutcome, detail: string, evidence_references: Array<string>, reused_from_result_id: string | null, };
