// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageValidationCheckCategory } from "./PackageValidationCheckCategory";
import type { ProductionFindingSeverity } from "./ProductionFindingSeverity";
import type { SubmissionValidationContextInput } from "./SubmissionValidationContextInput";

export type PackageValidationRule = { rule_id: string, category: PackageValidationCheckCategory, severity: ProductionFindingSeverity, deterministic: boolean, source: SubmissionValidationContextInput | null, manual_checklist: Array<string>, major_exception_allowed: boolean, };
