// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManualVerificationResult } from "./ManualVerificationResult";

export type PackageManualVerification = { verification_id: string, validation_result_id: string, package_id: string, package_version: number, package_manifest_sha256: string, item_id: string, content_sha256: string, verifier_identity: string, capability: string, checks: Array<string>, evidence_references: Array<string>, result: ManualVerificationResult, limitations: Array<string>, manifest_sha256: string, created_at: string, };
