// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PackageValidationCheckCategory = "file_structure" | "rendering" | "calculation" | "cross_artifact_consistency" | "hidden_content" | "information_boundary" | "filename" | "hash" | "package_wide";
