// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The operation identity and progress contract shared by the native intake
 * worker and the renderer.  Progress is deliberately a snapshot rather than
 * an event stream so a renderer that was suspended can resume by polling the
 * same authoritative state.
 */
export type PackageIntakeOperationKind = "start_tender" | "add_package";
