// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageIntakeOperationKind } from "./PackageIntakeOperationKind";
import type { PackageIntakeStage } from "./PackageIntakeStage";
import type { TenderPackageSourceKind } from "./TenderPackageSourceKind";

export type PackageIntakeProgress = { operation_id: string, kind: PackageIntakeOperationKind, stage: PackageIntakeStage, source_kind: TenderPackageSourceKind, source_name: string, current_relative_path: string | null, discovered_count: number, processed_count: number, registered_count: number, exception_count: number, total_count: number | null, cancellation_requested: boolean, cancellable: boolean, started_at_epoch_ms: bigint, updated_at_epoch_ms: bigint, };
