// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ParseState = "not_requested" | "running" | "parsed" | "failed" | "interrupted" | "quarantined" | "unsupported";
