// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ParseExceptionCode = "unsupported" | "process_failed" | "publication_failed" | "interrupted" | "malformed_output" | "output_limit_exceeded" | "loss_detected";
