// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecisionAction } from "./DecisionAction";
import type { DecisionDependency } from "./DecisionDependency";
import type { DecisionEvidence } from "./DecisionEvidence";
import type { DecisionFact } from "./DecisionFact";
import type { DecisionGroupMember } from "./DecisionGroupMember";
import type { DecisionKind } from "./DecisionKind";
import type { DecisionLifecycleGate } from "./DecisionLifecycleGate";
import type { DecisionResponsible } from "./DecisionResponsible";
import type { DecisionStatus } from "./DecisionStatus";
import type { DecisionTarget } from "./DecisionTarget";
import type { DecisionUrgency } from "./DecisionUrgency";

export type PendingDecision = { decision_id: string, kind: DecisionKind, title: string, summary: string, target: DecisionTarget, responsible: DecisionResponsible, lifecycle_gate: DecisionLifecycleGate, urgency: DecisionUrgency, urgency_reason: string, deadline: string | null, status: DecisionStatus, ready: boolean, blocking_consequences: Array<string>, allowed_actions: Array<DecisionAction>, facts: Array<DecisionFact>, evidence: Array<DecisionEvidence>, changes_since_prior_review: Array<string>, dependencies: Array<DecisionDependency>, unresolved_queries: Array<DecisionDependency>, assumptions: Array<DecisionFact>, calculations: Array<DecisionFact>, findings: Array<DecisionFact>, exceptions: Array<DecisionFact>, independent_review: DecisionFact | null, group_members: Array<DecisionGroupMember>, };
