// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentResourceBudget } from "./AgentResourceBudget";
import type { AgentRunWorkspaceManifest } from "./AgentRunWorkspaceManifest";
import type { DataClassification } from "./DataClassification";
import type { DataViewManifest } from "./DataViewManifest";
import type { PermissionCeiling } from "./PermissionCeiling";
import type { ThreadExposureSet } from "./ThreadExposureSet";
import type { TypedToolDefinition } from "./TypedToolDefinition";

export type PermissionGrant = { grant_id: string, policy_version: number, capability_catalogue_version: number, work_plan_version: number, profile_id: string, profile_version: number, task_id: string, purpose: string, data_scopes: Array<string>, data_classifications: Array<DataClassification>, allowed_actions: Array<string>, typed_tools: Array<TypedToolDefinition>, network_allowed: boolean, workspace_write_allowed: boolean, data_views: Array<DataViewManifest>, thread_exposure: ThreadExposureSet, workspace: AgentRunWorkspaceManifest, access_ceiling: PermissionCeiling, resource_budget: AgentResourceBudget, issued_at: string, expires_at: string, };
