// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PermissionDenialReason = "default_deny" | "prohibited_action" | "grant_expired" | "secret_data" | "outside_ceiling" | "work_plan_amendment_required" | "tool_not_granted" | "thread_exposure_incompatible" | "engineer_denied" | "superseded" | "access_revoked";
