// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderSummary } from "./TenderSummary";

export type PortableTenderArchiveRecord = { archive_id: string, tender_id: string, backup_id: string, relative_path: string, source: TenderSummary, database_sha256: string, content_object_count: bigint, audit_event_count: bigint, audit_chain_head: string, tender_schema_version: bigint, quantix_version: string, manifest_sha256: string, archive_size_bytes: bigint, created_at: string, };
