// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PricedCostBaselineReview } from "./PricedCostBaselineReview";
import type { PricingAdjustmentApproval } from "./PricingAdjustmentApproval";
import type { PricingAdjustmentDirection } from "./PricingAdjustmentDirection";
import type { PricingAdjustmentKind } from "./PricingAdjustmentKind";

export type PricingAdjustmentVersion = { adjustment_id: string, version: number, tender_revision: number, baseline_id: string, baseline_version: number, calculation_run_id: string, calculation_manifest_sha256: string, amount: string, currency: string, kind: PricingAdjustmentKind, direction: PricingAdjustmentDirection, scope: string, rationale: string, commercial_appetite: string | null, exclusions: Array<string>, qualifications: Array<string>, supersedes_adjustment_manifest_sha256: string | null, remediates_review_manifest_sha256: string | null, current: boolean, review: PricedCostBaselineReview | null, approval: PricingAdjustmentApproval | null, manifest_sha256: string, created_at: string, };
