// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PricedCostBaselineApproval } from "./PricedCostBaselineApproval";
import type { PricedCostBaselineReview } from "./PricedCostBaselineReview";

export type PricedCostBaselineVersion = { baseline_id: string, version: number, tender_revision: number, basis_id: string, basis_version: number, basis_manifest_sha256: string, aggregate_calculation_run_id: string, aggregate_calculation_manifest_sha256: string, amount: string, currency: string, rationale: string, supersedes_baseline_manifest_sha256: string | null, remediates_review_manifest_sha256: string | null, current: boolean, approved_for_commercial_pricing: boolean, review: PricedCostBaselineReview | null, approval: PricedCostBaselineApproval | null, manifest_sha256: string, created_at: string, };
