// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PricingScenarioSelection = { selection_id: string, supersedes_selection_id: string | null, rationale: string, selected_by: string, acting_role: string, current: boolean, manifest_sha256: string, created_at: string, };
