// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PricedCostBaselineReviewFinding } from "./PricedCostBaselineReviewFinding";
import type { PricedCostBaselineReviewOutcome } from "./PricedCostBaselineReviewOutcome";

export type PricedCostBaselineReview = { review_id: string, reviewer_run_id: string, reviewer_profile_id: string, reviewer_profile_version: number, outcome: PricedCostBaselineReviewOutcome, findings: Array<PricedCostBaselineReviewFinding>, manifest_sha256: string, created_at: string, };
