// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommercialStrategy } from "./CommercialStrategy";
import type { PricedCostBaselineVersion } from "./PricedCostBaselineVersion";
import type { PricingAdjustmentVersion } from "./PricingAdjustmentVersion";
import type { PricingDecisionHistoryEntry } from "./PricingDecisionHistoryEntry";
import type { PricingScenarioVersion } from "./PricingScenarioVersion";

export type PricingWorkspaceInspection = { baseline: PricedCostBaselineVersion | null, adjustments: Array<PricingAdjustmentVersion>, strategies: Array<CommercialStrategy>, scenarios: Array<PricingScenarioVersion>, decision_history: Array<PricingDecisionHistoryEntry>, };
