// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalculationRoundingMode } from "./CalculationRoundingMode";
import type { PricingCalculationAdjustmentInput } from "./PricingCalculationAdjustmentInput";

export type PricingCalculationRun = { pricing_calculation_run_id: string, tender_revision: number, baseline_aggregate_run_id: string, baseline_aggregate_manifest_sha256: string, baseline_amount: string, adjustments: Array<PricingCalculationAdjustmentInput>, rule_id: string, rule_version: number, rule_approval_id: string, scenario_id: string, scenario_version: number, precision: number, rounding_mode: CalculationRoundingMode, engine_version: string, final_amount: string, currency: string, manifest_sha256: string, created_at: string, };
