// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovedTenderPrice } from "./ApprovedTenderPrice";
import type { PricingScenarioSelection } from "./PricingScenarioSelection";

export type PricingDecisionHistoryEntry = { pricing_scenario_id: string, pricing_scenario_version: number, scenario_name: string, selection: PricingScenarioSelection, approved_tender_price: ApprovedTenderPrice | null, };
