// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovedTenderPrice } from "./ApprovedTenderPrice";
import type { PricingAdjustmentReference } from "./PricingAdjustmentReference";
import type { PricingCalculationRun } from "./PricingCalculationRun";
import type { PricingScenarioSelection } from "./PricingScenarioSelection";

export type PricingScenarioVersion = { pricing_scenario_id: string, version: number, tender_revision: number, name: string, baseline_id: string, baseline_version: number, baseline_manifest_sha256: string, strategy_id: string, strategy_manifest_sha256: string, adjustments: Array<PricingAdjustmentReference>, calculation: PricingCalculationRun, current: boolean, selection: PricingScenarioSelection | null, approved_tender_price: ApprovedTenderPrice | null, manifest_sha256: string, created_at: string, };
