// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PricingAdjustmentDirection } from "./PricingAdjustmentDirection";

export type PricingCalculationAdjustmentInput = { adjustment_id: string, adjustment_version: number, adjustment_manifest_sha256: string, calculation_run_id: string, calculation_manifest_sha256: string, direction: PricingAdjustmentDirection, amount: string, currency: string, };
