// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcceptanceArtifactHash } from "./AcceptanceArtifactHash";
import type { AcceptanceStageTiming } from "./AcceptanceStageTiming";
import type { LiveQualificationMetrics } from "./LiveQualificationMetrics";

export type PrivateQualificationRecord = { record_id: string, release_candidate_sha256: string, run_ids: Array<string>, exact_artifact_hashes: Array<AcceptanceArtifactHash>, findings: Array<string>, exceptions: Array<string>, metrics: Array<LiveQualificationMetrics>, timings: Array<AcceptanceStageTiming>, authorization_scope: string, approved_by: string, manifest_sha256: string, created_at: string, };
