// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProductionIntegrationReadiness = { readiness_id: string, artifact_id: string, artifact_version: number, payload_sha256: string, review_id: string | null, output_validation_passed: boolean, evidence_verified: boolean, dependencies_satisfied: boolean, approval_gates: Array<string>, finding_dispositions_sha256: string, created_at: string, };
