// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcceptanceStageTiming } from "./AcceptanceStageTiming";
import type { ProductAcceptanceOutcome } from "./ProductAcceptanceOutcome";

export type ProductAcceptanceRecord = { record_id: string, source_revision: string, run_ids: Array<string>, outcome: ProductAcceptanceOutcome, hard_gate_failures: Array<string>, measured_stage_timings: Array<AcceptanceStageTiming>, manifest_sha256: string, created_at: string, };
