// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcceptanceArtifactHash } from "./AcceptanceArtifactHash";
import type { AcceptanceCheckResult } from "./AcceptanceCheckResult";
import type { AcceptanceStageTiming } from "./AcceptanceStageTiming";
import type { ProductAcceptanceOutcome } from "./ProductAcceptanceOutcome";

export type ProductAcceptanceRun = { run_id: string, suite: string, outcome: ProductAcceptanceOutcome, source_revision: string, fixture_sha256: string, oracle_sha256: string, application_version: string, application_artifact_sha256: string, tender_schema_version: bigint, installation_schema_version: bigint, dependency_lock_sha256: string, rust_version: string, node_version: string, platform: string, checks: Array<AcceptanceCheckResult>, artifacts: Array<AcceptanceArtifactHash>, timings: Array<AcceptanceStageTiming>, hard_gate_failures: Array<string>, manifest_sha256: string, created_at: string, };
