// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProductionCoordinationObservationValue = { "kind": "text", text: string, } | { "kind": "amount", value: string, currency: string, } | { "kind": "text_set", values: Array<string>, };
