// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProductionFindingDisposition } from "./ProductionFindingDisposition";
import type { ProductionFindingSeverity } from "./ProductionFindingSeverity";

export type ProductionReviewFinding = { finding_id: string, review_id: string, sequence: number, severity: ProductionFindingSeverity, summary: string, evidence_references: Array<string>, disposition: ProductionFindingDisposition | null, created_at: string, };
