// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentTaskInputReference } from "./AgentTaskInputReference";
import type { ProductionReviewFinding } from "./ProductionReviewFinding";
import type { ProductionReviewResult } from "./ProductionReviewResult";

export type ProductionReview = { review_id: string, target_artifact_id: string, target_version: number, target_payload_sha256: string, reviewer_run_id: string, reviewer_profile_id: string, reviewer_profile_version: number, capability: string, scope: Array<string>, criteria: Array<string>, inputs: Array<AgentTaskInputReference>, result: ProductionReviewResult, resolved_finding_ids: Array<string>, findings: Array<ProductionReviewFinding>, created_at: string, };
