// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderQueryTreatment } from "./TenderQueryTreatment";

export type ProductionQueryTreatmentApplication = { decision_id: string, query_id: string, query_version: number, treatment: TenderQueryTreatment, application: string, evidence_references: Array<string>, };
