// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProductionCoordinationObservationSubject } from "./ProductionCoordinationObservationSubject";
import type { ProductionCoordinationObservationValue } from "./ProductionCoordinationObservationValue";

export type ProductionCoordinationObservation = { subject: ProductionCoordinationObservationSubject, value: ProductionCoordinationObservationValue, evidence_references: Array<string>, };
