// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentTenderQueryProposal } from "./AgentTenderQueryProposal";
import type { AgentTenderQueryUpdate } from "./AgentTenderQueryUpdate";
import type { ProductionQueryTreatmentApplication } from "./ProductionQueryTreatmentApplication";
import type { ProductionRemediation } from "./ProductionRemediation";

export type ProductionArtifactPayload = { summary: string, evidence_references: Array<string>, gaps: Array<string>, remediations?: Array<ProductionRemediation>, query_treatment_applications?: Array<ProductionQueryTreatmentApplication>, query_proposals?: Array<AgentTenderQueryProposal>, query_updates?: Array<AgentTenderQueryUpdate>, };
