// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProductionRemediation = { finding_id: string, treatment: string, evidence_references: Array<string>, };
