// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProductionRemediation } from "./ProductionRemediation";

export type ProductionArtifactPayload = { summary: string, evidence_references: Array<string>, gaps: Array<string>, remediations?: Array<ProductionRemediation>, };
