// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProductionArtifactVersion } from "./ProductionArtifactVersion";
import type { ProductionIntegrationReadiness } from "./ProductionIntegrationReadiness";
import type { ProductionReview } from "./ProductionReview";

export type ProductionTaskReviewInspection = { production_task_id: string, artifact_versions: Array<ProductionArtifactVersion>, reviews: Array<ProductionReview>, readiness: ProductionIntegrationReadiness | null, };
