// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataClassification } from "./DataClassification";

export type ProductionTaskOutput = { output_id: string, run_id: string, reviewer_run_id: string, payload_sha256: string, data_scopes: Array<string>, data_classifications: Array<DataClassification>, created_at: string, };
