// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProductionTaskOutput } from "./ProductionTaskOutput";
import type { ProductionTaskState } from "./ProductionTaskState";
import type { WorkPlanTask } from "./WorkPlanTask";

export type ProductionTaskInspection = { production_task_id: string, plan_manifest_sha256: string, task: WorkPlanTask, state: ProductionTaskState, run_ids: Array<string>, registered_outputs: Array<ProductionTaskOutput>, created_at: string, updated_at: string, };
