// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataClassification } from "./DataClassification";
import type { ProductionArtifactPayload } from "./ProductionArtifactPayload";

export type ProductionArtifactVersion = { payload: ProductionArtifactPayload, artifact_id: string, version: number, author_run_id: string, prior_version: number | null, remediation_review_id: string | null, payload_sha256: string, output_validation_passed: boolean, evidence_verified: boolean, data_scopes: Array<string>, data_classifications: Array<DataClassification>, created_at: string, };
