// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProductionFindingDispositionKind } from "./ProductionFindingDispositionKind";

export type ProductionFindingDisposition = { disposition_id: string, kind: ProductionFindingDispositionKind, target_artifact_id: string, target_version: number, verifying_review_id: string | null, decided_by: string, acting_role: string, rationale: string, consequence: string, created_at: string, };
