// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProductionCoordinationObservationSubject = "submission_deadline" | "responsible_party" | "scope_qualification" | "scope_exclusion" | "expected_delivery_cost" | "approved_tender_price" | "commercial_appetite" | "technical_commitment" | "programme_commitment" | "procurement_commitment" | "contractual_commitment" | "risk_commitment" | "submission_commitment" | "query_treatment";
