// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRunInspection } from "./AgentRunInspection";
import type { ProductionTaskInspection } from "./ProductionTaskInspection";

export type ProductionTaskRunResult = { run: AgentRunInspection, task: ProductionTaskInspection, };
