// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProductionTaskState = "blocked" | "ready" | "running" | "review_ready" | "reviewing" | "remediation_ready" | "ready_for_integration" | "attempt_limit_reached" | "failed" | "cancelled" | "indeterminate" | "suspended";
