// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VerificationStatus } from "./VerificationStatus";

export type ProposedAgentResult = { result_id: string, verification_status: VerificationStatus, payload_json: string, };
