// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalculationRoundingMode } from "./CalculationRoundingMode";

export type ProposeBoqCalculationRuleCommand = { tender_id: string, supported_rounding: Array<CalculationRoundingMode>, change_rationale: string, };
