// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiProviderKind } from "./AiProviderKind";
import type { ProviderConnectionStatus } from "./ProviderConnectionStatus";
import type { ProviderModelOption } from "./ProviderModelOption";

export type ProviderConnectionView = { connection_id: string, provider: AiProviderKind, display_name: string, status: ProviderConnectionStatus, account_label: string | null, account_plan: string | null, models: Array<ProviderModelOption>, catalogue_fetched_at: string | null, adapter_version: string, status_summary: string, };
