// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderEventKind } from "./ProviderEventKind";

export type ProviderEvent = { sequence: number, kind: ProviderEventKind, summary: string, opaque_reference: string | null, };
