// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderRateLimitState } from "./ProviderRateLimitState";
import type { ProviderRateLimitWindow } from "./ProviderRateLimitWindow";

export type ProviderRateLimit = { state: ProviderRateLimitState, primary: ProviderRateLimitWindow | null, secondary: ProviderRateLimitWindow | null, };
