// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderRateLimitWindow = { used_percent: number, window_minutes: bigint | null, resets_at_epoch_seconds: bigint | null, };
