// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderReasoningOption } from "./ProviderReasoningOption";

export type ProviderModelOption = { model_id: string, display_name: string, description: string, is_default: boolean, input_modalities: Array<string>, reasoning_options: Array<ProviderReasoningOption>, };
