// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderRateLimit } from "./ProviderRateLimit";

export type ProviderUsage = { input_tokens: bigint | null, cached_input_tokens: bigint | null, output_tokens: bigint | null, reasoning_output_tokens: bigint | null, total_tokens: bigint | null, context_window: bigint | null, elapsed_milliseconds: bigint | null, rate_limit: ProviderRateLimit | null, };
