// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderFailureCategory = "protocol_invalid" | "process_failed" | "rate_limited" | "output_invalid" | "interrupted" | "outcome_unknown" | "permission_denied";
