// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderReasoningSelection = { "kind": "provider_default" } | { "kind": "codex_effort", "value": string } | { "kind": "anthropic_effort", "value": string };
