// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderEventKind = "run_started" | "thread_established" | "thread_resumed" | "turn_started" | "usage_observed" | "control_request_denied" | "warning" | "terminal";
