// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionDenialReason } from "./PermissionDenialReason";
import type { ProviderEventKind } from "./ProviderEventKind";

export type ProviderEvent = { sequence: number, kind: ProviderEventKind, summary: string, correlation_id: string | null, request_fingerprint: string | null, denial_reason: PermissionDenialReason | null, opaque_reference: string | null, };
