// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderLoginMethod } from "./ProviderLoginMethod";
import type { ProviderLoginStatus } from "./ProviderLoginStatus";

export type ProviderLoginView = { connection_id: string, login_id: string, method: ProviderLoginMethod, status: ProviderLoginStatus, user_code: string | null, status_summary: string, };
