// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputValidationIssue } from "./OutputValidationIssue";
import type { ProviderFailureCategory } from "./ProviderFailureCategory";

export type ProviderFailure = { category: ProviderFailureCategory, retry_safe: boolean, required_user_action: string, redacted_detail: string | null, retry_after_milliseconds: bigint | null, validation_issues: Array<OutputValidationIssue>, };
