// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderConnectionStatus = "ready" | "authentication_required" | "subscription_required" | "temporarily_unavailable" | "incompatible";
