// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderReasoningSelection } from "./ProviderReasoningSelection";

export type ProviderReasoningOption = { selection: ProviderReasoningSelection, label: string, description: string, is_default: boolean, };
