// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcceptanceArtifactHash } from "./AcceptanceArtifactHash";
import type { ChatGptProductionAssuranceEvidence } from "./ChatGptProductionAssuranceEvidence";
import type { IntegrationTermsDecision } from "./IntegrationTermsDecision";
import type { LicenseDistributionReview } from "./LicenseDistributionReview";
import type { NativePlatformQualificationRecord } from "./NativePlatformQualificationRecord";
import type { PublicReleaseGateOutcome } from "./PublicReleaseGateOutcome";
import type { TechnicalRiskAcceptance } from "./TechnicalRiskAcceptance";

export type PublicReleaseGateRecord = { gate_id: string, release_candidate_manifest_sha256: string, private_windows_candidate_binary_sha256: string, private_qualification_sha256: string, native_platforms: Array<NativePlatformQualificationRecord>, license_review: LicenseDistributionReview, chatgpt_production_assurance: ChatGptProductionAssuranceEvidence, integration_terms: IntegrationTermsDecision, technical_risks: Array<TechnicalRiskAcceptance>, release_artifacts: Array<AcceptanceArtifactHash>, blockers: Array<string>, outcome: PublicReleaseGateOutcome, supported_platform_claims: Array<string>, public_production_ready: boolean, approver: string, manifest_sha256: string, created_at: string, };
