// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PurgeRecoveryRequiredTenderCommand = { tender_id: string, rationale: string, confirmation_tender_name: string, };
