// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuantixDoctorRepairAction } from "./QuantixDoctorRepairAction";
import type { QuantixDoctorRepairTarget } from "./QuantixDoctorRepairTarget";

export type QuantixDoctorRepairCommand = { report_revision: string, code: string, action: QuantixDoctorRepairAction, target: QuantixDoctorRepairTarget, tender_id: string | null, };
