// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuantixDoctorFinding } from "./QuantixDoctorFinding";

export type QuantixDoctorReport = { revision: string, healthy: boolean, findings: Array<QuantixDoctorFinding>, };
