// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuantixDoctorArea } from "./QuantixDoctorArea";
import type { QuantixDoctorRepairAction } from "./QuantixDoctorRepairAction";
import type { QuantixDoctorSeverity } from "./QuantixDoctorSeverity";

export type QuantixDoctorFinding = { code: string, area: QuantixDoctorArea, severity: QuantixDoctorSeverity, title: string, cause: string, affected_capability: string, impact: string, safe_remediation: string, repair_action: QuantixDoctorRepairAction | null, };
