// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostCommandInterface } from "./HostCommandInterface";
import type { HostConnectionState } from "./HostConnectionState";
import type { HostRuntime } from "./HostRuntime";
import type { RendererAssetSource } from "./RendererAssetSource";

export type QuantixHostStatus = { connection: HostConnectionState, runtime: HostRuntime, command_interface: HostCommandInterface, renderer_assets: RendererAssetSource, };
