// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QuantixDoctorRepairAction = "prepare_document_tools" | "retry_document_tools" | "refresh_ai_provider" | "rebind_tender_ai_selection" | "retry_update_inspection" | "inspect_tender_integrity" | "retry_diagnostics";
