// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QuantixDoctorArea = "setup" | "document_tools" | "default_ai" | "update" | "tender_integrity" | "diagnostics";
