// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcceptanceArtifactHash } from "./AcceptanceArtifactHash";
import type { AcceptanceStageTiming } from "./AcceptanceStageTiming";
import type { LiveQualificationMetrics } from "./LiveQualificationMetrics";

export type RecordLiveQualificationRunCommand = { opted_in: boolean, platform: string, release_candidate_sha256: string, fixture_sha256: string, oracle_sha256: string, codex_version: string, app_server_version: string, docling_runtime_sha256: string, model_observations: Array<string>, evaluation_policy_sha256: string, deterministic_acceptance_record_sha256: string, metrics: LiveQualificationMetrics, installed_checks: Array<string>, artifacts: Array<AcceptanceArtifactHash>, findings: Array<string>, exceptions: Array<string>, timings: Array<AcceptanceStageTiming>, };
