// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManualVerificationResult } from "./ManualVerificationResult";

export type RecordPackageManualVerificationCommand = { tender_id: string, package_id: string, package_version: number, package_manifest_sha256: string, validation_run_id: string, validation_result_id: string, item_id: string, content_sha256: string, capability: string, checks: Array<string>, evidence_references: Array<string>, result: ManualVerificationResult, limitations: Array<string>, };
