// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceMessageReference } from "./WorkspaceMessageReference";

export type RecordEngineerWorkspaceMessageCommand = { tender_id: string, body: string, attachment_refs: Array<WorkspaceMessageReference>, context_refs: Array<WorkspaceMessageReference>, };
