// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RendererDiagnosticKind } from "./RendererDiagnosticKind";

export type RecordRendererDiagnosticCommand = { kind: RendererDiagnosticKind, };
