// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecordLiveQualificationRunCommand = { opted_in: boolean, application_artifact_path: string, application_resource_directory_path: string, application_uninstaller_path: string, deterministic_acceptance_record_sha256: string, };
