// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecordEngineerWorkspaceMessageCommand = { tender_id: string, body: string, };
