// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RegisterTenderContentCommand = { tender_id: string, logical_id: string, media_type: string, bytes: Array<number>, };
