// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReleaseReadinessBlockerCode = "package_incomplete" | "validation_failed" | "manual_verification_missing" | "manual_verification_failed" | "reviewer_unqualified" | "review_missing" | "critical_finding" | "major_finding" | "stale_input";
