// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReleaseReadinessBlocker } from "./ReleaseReadinessBlocker";
import type { ReleaseReadinessCategorySummary } from "./ReleaseReadinessCategorySummary";
import type { SubmissionPackageCurrentnessFact } from "./SubmissionPackageCurrentnessFact";
import type { SubmissionPackageDependency } from "./SubmissionPackageDependency";

export type ReleaseReadinessReport = { report_id: string, version: number, package_id: string, package_version: number, package_manifest_sha256: string, policy_manifest_sha256: string, validation_run_id: string, validation_manifest_sha256: string, review_plan_id: string, review_plan_manifest_sha256: string, review_ids: Array<string>, manual_verification_ids: Array<string>, exception_approval_ids: Array<string>, through_event_sequence: bigint, summaries: Array<ReleaseReadinessCategorySummary>, deadline: SubmissionPackageDependency | null, changes: Array<SubmissionPackageCurrentnessFact>, blockers: Array<ReleaseReadinessBlocker>, current: boolean, ready: boolean, manifest_sha256: string, created_at: string, };
