// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReleaseReadinessBlockerCode } from "./ReleaseReadinessBlockerCode";

export type ReleaseReadinessBlocker = { code: ReleaseReadinessBlockerCode, reference_id: string, detail: string, };
