// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReleaseCopyItem = { package_path: string, content_sha256: string, size_bytes: bigint, };
