// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReleaseCopyItem } from "./ReleaseCopyItem";

export type ReleaseCopyExport = { export_id: string, approval_id: string, relative_path: string, items: Array<ReleaseCopyItem>, verified: boolean, created_at: string, manifest_sha256: string, };
