// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderRecoveryDecision } from "./TenderRecoveryDecision";

export type ResolveTenderRecoveryCommand = { tender_id: string, recovery_id: string, decision: TenderRecoveryDecision, rationale: string, };
