// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRunRecoveryDisposition } from "./AgentRunRecoveryDisposition";

export type ResolveIndeterminateAgentRunCommand = { tender_id: string, run_id: string, disposition: AgentRunRecoveryDisposition, rationale: string, };
