// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentAccessResolution } from "./AgentAccessResolution";

export type ResolveAgentAccessCommand = { tender_id: string, request_id: string, run_id: string, resolution: AgentAccessResolution, };
