// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderRecordVersionReference } from "./TenderRecordVersionReference";

export type ResourceImplication = { affected_work: Array<string>, responsibility: string, planned_treatment: string, uncertainty: string | null, triggering_record: TenderRecordVersionReference, };
