// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkPlanRevisionAction } from "./WorkPlanRevisionAction";

export type ReviseWorkPlanProposalCommand = { tender_id: string, plan_id: string, base_version: number, actions: Array<WorkPlanRevisionAction>, };
