// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentTaskInputReference } from "./AgentTaskInputReference";
import type { ExternalRfiQueryReference } from "./ExternalRfiQueryReference";
import type { ExternalRfiRecipient } from "./ExternalRfiRecipient";

export type ReviseExternalRfiDraftCommand = { tender_id: string, rfi_id: string, base_version: number, query_refs: Array<ExternalRfiQueryReference>, additional_evidence: Array<AgentTaskInputReference>, contractual_context: string, response_need: string, attachments: Array<AgentTaskInputReference>, due_at: string, recipient: ExternalRfiRecipient, affected_commitments: Array<string>, };
