// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RunBasisOfEstimateReviewCommand = { tender_id: string, basis_id: string, version: number, };
