// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderEvidenceReference } from "./TenderEvidenceReference";

export type RunCostEstimatorBasisCommand = { tender_id: string, quotation_evidence: Array<TenderEvidenceReference>, calculation_run_ids: Array<string>, };
