// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentTaskInputReference } from "./AgentTaskInputReference";

export type RunCostEstimatorCalculationCommand = { tender_id: string, scenario_id: string, scenario_version: number, description: string, quantity_evidence: Array<AgentTaskInputReference>, unit_rate_evidence: Array<AgentTaskInputReference>, };
