// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RunDeterministicAcceptanceCommand = { source_revision: string, application_artifact_path: string, application_resource_directory_path: string, dependency_lock_path: string, };
