// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcceptanceArtifactHash } from "./AcceptanceArtifactHash";
import type { AcceptanceCheckResult } from "./AcceptanceCheckResult";
import type { AcceptanceStageTiming } from "./AcceptanceStageTiming";

export type RunDeterministicAcceptanceCommand = { source_revision: string, application_artifact_path: string, dependency_lock_path: string, checks: Array<AcceptanceCheckResult>, artifacts: Array<AcceptanceArtifactHash>, timings: Array<AcceptanceStageTiming>, };
