// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RunExternalRfiReviewCommand = { tender_id: string, rfi_id: string, version: number, };
