// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RunPricedCostBaselineReviewCommand = { tender_id: string, baseline_id: string, version: number, };
