// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RunProductionTaskCommand = { tender_id: string, production_task_id: string, };
