// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RunSubmissionSectionReviewCommand = { tender_id: string, package_id: string, package_version: number, package_manifest_sha256: string, plan_id: string, plan_manifest_sha256: string, assignment_id: string, };
