// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RuntimeReadinessIssue = "setup_incomplete" | "uv_executable_missing" | "ocr_executable_missing" | "uv_version_incompatible" | "ocr_version_incompatible" | "runtime_resource_integrity_failed" | "ocr_environment_invalid" | "ocr_models_missing" | "runtime_preparation_active" | "runtime_preparation_interrupted" | "runtime_preparation_cancelled" | "insufficient_disk_space" | "runtime_preparation_failed" | "runtime_probe_failed";
