// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RuntimePreparationStep = "validate_resources" | "verify_bundled_tools" | "reset_environment" | "synchronize_environment" | "verify_docling" | "prepare_document_models" | "run_document_check" | "publish_runtime" | "final_runtime_check";
