// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RuntimeReadinessState = "ready" | "preparing" | "missing_executable" | "incompatible_version" | "missing_model" | "authentication_required" | "interrupted_preparation" | "repair_required";
