// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimePreparationActivity } from "./RuntimePreparationActivity";
import type { RuntimePreparationStatus } from "./RuntimePreparationStatus";

export type RuntimePreparationProgress = { status: RuntimePreparationStatus, activities: Array<RuntimePreparationActivity>, started_at_epoch_ms: bigint | null, updated_at_epoch_ms: bigint | null, model_files_written: bigint | null, model_bytes_written: bigint | null, };
