// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeReadinessIssue } from "./RuntimeReadinessIssue";
import type { RuntimeReadinessState } from "./RuntimeReadinessState";

export type RuntimeReadiness = { state: RuntimeReadinessState, issues: Array<RuntimeReadinessIssue>, codex_version: string | null, uv_version: string | null, docling_version: string | null, repair_available: boolean, };
