// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimePreparationActivityStatus } from "./RuntimePreparationActivityStatus";
import type { RuntimePreparationStep } from "./RuntimePreparationStep";

export type RuntimePreparationActivity = { step: RuntimePreparationStep, title: string, detail: string, status: RuntimePreparationActivityStatus, started_at_epoch_ms: bigint | null, finished_at_epoch_ms: bigint | null, };
