// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiProviderRoute } from "./AiProviderRoute";

export type SaveAiProviderCommand = { id: string, display_name: string, route: AiProviderRoute, base_url: string | null, model_id: string, 
/**
 * Absent means "keep the stored key", so editing a connection never requires the
 * interface to hold a secret it should not have.
 */
api_key: string | null, };
