// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SetupState = "ready" | "warning" | "missing_capability" | "unsupported_version" | "repair_required";
