// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SetupIssue = "application_home_unavailable" | "installation_catalogue_corrupt" | "storage_not_writable" | "storage_permissions_unverified" | "unrecognized_application_home" | "unsafe_storage_location" | "unsafe_storage_permissions" | "unsupported_installation_version" | "update_installation_active";
