// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SetupIssue } from "./SetupIssue";
import type { SetupState } from "./SetupState";

export type SetupOutcome = { state: SetupState, setup_performed: boolean, issues: Array<SetupIssue>, };
