// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StartupReconciliationReport = { removed_tender_candidates: number, interrupted_backup_operations: number, interrupted_recovery_operations: number, completed_retention_operations: number, };
