// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderPackageSourceKind } from "./TenderPackageSourceKind";

export type StartManagerTenderCommand = { source_kind: TenderPackageSourceKind, local_only: boolean, };
