// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StartChatGptDeviceLoginResult = { verification_url: string, user_code: string, };
