// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StopTenderDeepDiagnosticsCommand = { tender_id: string, session_id: string, };
