// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenerationAuthoringMode } from "./GenerationAuthoringMode";
import type { GenerationRequirementKind } from "./GenerationRequirementKind";

export type SubmissionArtifactVersion = { artifact_id: string, version: number, baseline_id: string, baseline_version: number, baseline_manifest_sha256: string, section_key: string, package_path: string, envelope_key: string, language: string, authoring_mode: GenerationAuthoringMode, media_type: string, classifications: Array<GenerationRequirementKind>, scope_record_ids: Array<string>, content_sha256: string, size_bytes: bigint, exact_inputs: Array<string>, generation_policy_id: string, generation_policy_version: number, generation_policy_sha256: string, provenance: Array<string>, manifest_sha256: string, created_at: string, };
