// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubmissionContributionKind } from "./SubmissionContributionKind";
import type { SubmissionValidationContextInput } from "./SubmissionValidationContextInput";

export type SubmissionAuthorshipProvenance = { "kind": "agent_contribution", run_id: string, profile_id: string, profile_version: number, contribution_kind: SubmissionContributionKind, exact_source: SubmissionValidationContextInput, } | { "kind": "external_source", artifact_id: string, version: number, content_sha256: string, };
