// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FinalReviewInspection } from "./FinalReviewInspection";
import type { ReleaseCopyExport } from "./ReleaseCopyExport";
import type { SubmissionReleaseApproval } from "./SubmissionReleaseApproval";
import type { SubmissionReleaseState } from "./SubmissionReleaseState";

export type SubmissionReleaseInspection = { final_review: FinalReviewInspection, approval: SubmissionReleaseApproval | null, state: SubmissionReleaseState, exports: Array<ReleaseCopyExport>, submission_claimed: boolean, };
