// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubmissionProfileVersionReference } from "./SubmissionProfileVersionReference";

export type SubmissionWorkPlanContext = { plan_id: string, plan_version: number, plan_manifest_sha256: string, plan_approval_id: string, plan_approval_sha256: string, activation_id: string, authorized_profile_versions: Array<SubmissionProfileVersionReference>, };
