// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FinalReviewReviewer } from "./FinalReviewReviewer";
import type { PackageReviewFinding } from "./PackageReviewFinding";
import type { PackageReviewResult } from "./PackageReviewResult";

export type SubmissionSectionReview = { review_id: string, assignment_id: string, package_id: string, package_version: number, package_manifest_sha256: string, reviewer_run_id: string, reviewer: FinalReviewReviewer, required_capability: string, criteria: Array<string>, result: PackageReviewResult, findings: Array<PackageReviewFinding>, manifest_sha256: string, created_at: string, };
