// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubmissionPackageDependencyKind } from "./SubmissionPackageDependencyKind";

export type SubmissionPackageDependency = { kind: SubmissionPackageDependencyKind, reference_id: string, version: number, manifest_sha256: string, };
