// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubmissionValidationContextInput = { input_kind: string, reference_id: string, version: number, sha256: string, };
