// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubmissionPackageCurrentnessCode = "head_advanced" | "generation_advanced" | "baseline_changed" | "work_plan_changed" | "change_pending" | "source_changed" | "dependency_digest_changed";
