// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubmissionSectionIndependenceContext } from "./SubmissionSectionIndependenceContext";
import type { SubmissionSectionRiskContext } from "./SubmissionSectionRiskContext";

export type SubmissionPackageSection = { section_key: string, envelope_key: string, language: string, item_ids: Array<string>, requirement_ids: Array<string>, required_capabilities: Array<string>, risk_context: SubmissionSectionRiskContext, independence_context: SubmissionSectionIndependenceContext, };
