// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenerationRequirement } from "./GenerationRequirement";
import type { SubmissionCoverageBlocker } from "./SubmissionCoverageBlocker";
import type { SubmissionCoverageDisposition } from "./SubmissionCoverageDisposition";
import type { SubmissionPackageDependency } from "./SubmissionPackageDependency";

export type SubmissionCoverageRow = { requirement: GenerationRequirement, disposition: SubmissionCoverageDisposition, item_id: string | null, blockers: Array<SubmissionCoverageBlocker>, required_capabilities: Array<string>, risk_references: Array<SubmissionPackageDependency>, manual_validation_required: boolean, };
