// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenerationRequirementKind } from "./GenerationRequirementKind";
import type { SubmissionAuthorshipProvenance } from "./SubmissionAuthorshipProvenance";
import type { SubmissionItemSource } from "./SubmissionItemSource";
import type { SubmissionValidationContextInput } from "./SubmissionValidationContextInput";
import type { TenderRecordEvidence } from "./TenderRecordEvidence";

export type SubmissionPackageItem = { item_id: string, package_path: string, section_key: string, envelope_key: string, language: string, media_type: string, classifications: Array<GenerationRequirementKind>, scope_record_ids: Array<string>, content_sha256: string, size_bytes: bigint, source: SubmissionItemSource, requirement_ids: Array<string>, evidence: Array<TenderRecordEvidence>, provenance: Array<string>, calculation_references: Array<string>, review_references: Array<string>, decision_references: Array<string>, authorship: Array<SubmissionAuthorshipProvenance>, validation_context_inputs: Array<SubmissionValidationContextInput>, validation_context_sha256: string, };
