// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubmissionCoverageBlockerCode } from "./SubmissionCoverageBlockerCode";

export type SubmissionCoverageBlocker = { code: SubmissionCoverageBlockerCode, requirement_id: string, detail: string, };
