// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubmissionItemContent = { package_id: string, package_version: number, package_manifest_sha256: string, item_id: string, package_path: string, media_type: string, content_sha256: string, bytes: Array<number>, };
