// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubmissionCoverageRow } from "./SubmissionCoverageRow";
import type { SubmissionDecisionReference } from "./SubmissionDecisionReference";
import type { SubmissionPackageAssessment } from "./SubmissionPackageAssessment";
import type { SubmissionPackageCurrentnessFact } from "./SubmissionPackageCurrentnessFact";
import type { SubmissionPackageDependency } from "./SubmissionPackageDependency";
import type { SubmissionPackageItem } from "./SubmissionPackageItem";
import type { SubmissionPackageSection } from "./SubmissionPackageSection";
import type { SubmissionPackageStatus } from "./SubmissionPackageStatus";
import type { SubmissionValidationContextInput } from "./SubmissionValidationContextInput";
import type { SubmissionWorkPlanContext } from "./SubmissionWorkPlanContext";

export type SubmissionPackageVersion = { package_id: string, version: number, tender_revision: number, status: SubmissionPackageStatus, assessment: SubmissionPackageAssessment, current: boolean, currentness_facts: Array<SubmissionPackageCurrentnessFact>, generation_id: string, generation_sequence: number, generation_manifest_sha256: string, baseline_id: string, baseline_version: number, baseline_manifest_sha256: string, baseline_approval_id: string, work_plan: SubmissionWorkPlanContext, calculation_manifest_references: Array<SubmissionPackageDependency>, current_decision_references: Array<SubmissionDecisionReference>, submission_deadline: SubmissionPackageDependency | null, sections: Array<SubmissionPackageSection>, items: Array<SubmissionPackageItem>, coverage: Array<SubmissionCoverageRow>, validation_context_inputs: Array<SubmissionValidationContextInput>, validation_context_sha256: string, dependency_currentness_sha256: string, manifest_bytes: Array<number>, manifest_sha256: string, created_at: string, };
