// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRunInspection } from "./AgentRunInspection";
import type { FinalReviewInspection } from "./FinalReviewInspection";

export type SubmissionSectionReviewRunResult = { run: AgentRunInspection, final_review: FinalReviewInspection, };
