// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubmissionPackageDependency } from "./SubmissionPackageDependency";

export type SubmissionSectionRiskContext = { baseline_manifest_sha256: string, risk_references: Array<SubmissionPackageDependency>, };
