// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubmissionReleaseApproval = { approval_id: string, package_id: string, package_version: number, package_manifest_sha256: string, canonical_manifest_root: string, readiness_report_id: string, readiness_report_version: number, readiness_report_manifest_sha256: string, engineer_identity: string, acting_role: string, rationale: string, conditions: Array<string>, exceptions: Array<string>, approved_at: string, manifest_sha256: string, };
