// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubmissionArtifactContent = { artifact_id: string, version: number, media_type: string, content_sha256: string, bytes: Array<number>, };
