// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubmissionPackageDependencyKind = "baseline" | "baseline_approval" | "work_plan" | "work_plan_approval" | "production_activation" | "calculation_manifest" | "decision" | "tender_deadline" | "change_state";
