// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubmissionProfileVersionReference } from "./SubmissionProfileVersionReference";
import type { SubmissionValidationContextInput } from "./SubmissionValidationContextInput";

export type SubmissionSectionIndependenceContext = { independent_review_required: boolean, author_profile_versions: Array<SubmissionProfileVersionReference>, authorized_profile_versions: Array<SubmissionProfileVersionReference>, derivation_inputs: Array<SubmissionValidationContextInput>, };
