// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubmissionPackageCurrentnessCode } from "./SubmissionPackageCurrentnessCode";

export type SubmissionPackageCurrentnessFact = { code: SubmissionPackageCurrentnessCode, current: boolean, reference_id: string, expected_value: string, actual_value: string | null, };
