// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoordinatedBidBaselineBindingKind } from "./CoordinatedBidBaselineBindingKind";
import type { SubmissionDecisionReferenceKind } from "./SubmissionDecisionReferenceKind";

export type SubmissionDecisionReference = { kind: SubmissionDecisionReferenceKind, decision_id: string, subject_kind: CoordinatedBidBaselineBindingKind, subject_reference_id: string, subject_version: number, subject_manifest_sha256: string, };
