// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubmissionItemSource = { "kind": "generated", artifact_id: string, version: number, manifest_sha256: string, content_sha256: string, size_bytes: bigint, } | { "kind": "unchanged_source", artifact_id: string, version: number, content_sha256: string, size_bytes: bigint, };
