// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenerationAuthoringMode } from "./GenerationAuthoringMode";
import type { GenerationRequirementKind } from "./GenerationRequirementKind";
import type { TenderRecordEvidence } from "./TenderRecordEvidence";

export type TenderRecordGenerationInstruction = { kind: GenerationRequirementKind, mandatory: boolean, section_key: string, package_path: string, envelope_key: string, language: string, authoring_mode: GenerationAuthoringMode, requested_authoring_format: string | null, evidence: Array<TenderRecordEvidence>, };
