// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderQueryTreatment } from "./TenderQueryTreatment";

export type TenderQueryTreatmentProposal = { treatment: TenderQueryTreatment, rationale: string, proposed_by: string, proposed_by_run_id: string | null, };
