// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderLifecyclePhase } from "./TenderLifecyclePhase";

export type TenderSummary = { tender_id: string, name: string, revision: number, lifecycle_phase: TenderLifecyclePhase, audit_event_count: bigint, audit_chain_head: string, };
