// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderSummary } from "./TenderSummary";

export type TenderInspection = { summary: TenderSummary, content_object_count: bigint, content_version_count: bigint, };
