// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TenderErrorCode = "integrity_failed" | "invalid_command" | "not_found" | "recovery_required" | "runtime_required" | "setup_required" | "store_unavailable";
