// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRunInspection } from "./AgentRunInspection";

export type TenderRecordExtractionResult = { run: AgentRunInspection, published_record_count: number, };
