// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderRecordContradiction } from "./TenderRecordContradiction";
import type { TenderRecordField } from "./TenderRecordField";
import type { TenderRecordKind } from "./TenderRecordKind";
import type { TenderRecordReview } from "./TenderRecordReview";
import type { TenderRecordSourceRelationship } from "./TenderRecordSourceRelationship";
import type { TenderRecordTrustClass } from "./TenderRecordTrustClass";
import type { VerificationStatus } from "./VerificationStatus";

export type TenderRecordInspection = { record_id: string, stable_key: string, version: number, kind: TenderRecordKind, title: string, verification_status: VerificationStatus, trust_class: TenderRecordTrustClass, fields: Array<TenderRecordField>, contradictions: Array<TenderRecordContradiction>, source_relationships: Array<TenderRecordSourceRelationship>, reviews: Array<TenderRecordReview>, author_run_id: string, author_profile_id: string, created_at: string, };
