// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentProfileVersionView } from "./AgentProfileVersionView";
import type { TenderQuery } from "./TenderQuery";

export type TenderQueryPage = { query_register_open: boolean, owner_profiles: Array<AgentProfileVersionView>, production_task_keys: Array<string>, items: Array<TenderQuery>, next_cursor: string | null, total_current_count: number, overdue_count: number, release_blocking_count: number, };
