// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentTaskInputReference } from "./AgentTaskInputReference";
import type { ApprovedQueryTreatment } from "./ApprovedQueryTreatment";
import type { TenderQueryInvalidation } from "./TenderQueryInvalidation";
import type { TenderQueryResponse } from "./TenderQueryResponse";
import type { TenderQueryStatus } from "./TenderQueryStatus";
import type { TenderQueryTreatmentProposal } from "./TenderQueryTreatmentProposal";
import type { TenderQueryType } from "./TenderQueryType";
import type { TenderRecordVersionReference } from "./TenderRecordVersionReference";

export type TenderQuery = { query_id: string, version: number, query_type: TenderQueryType, question: string, ambiguity_or_gap: string, owner_profile_id: string, owner_profile_version: number, evidence: Array<AgentTaskInputReference>, affected_records: Array<TenderRecordVersionReference>, affected_task_keys: Array<string>, due_at: string, material: boolean, release_blocking: boolean, proposed_treatments: Array<TenderQueryTreatmentProposal>, responses: Array<TenderQueryResponse>, approved_treatment: ApprovedQueryTreatment | null, invalidations: Array<TenderQueryInvalidation>, status: TenderQueryStatus, overdue: boolean, current: boolean, source_run_id: string | null, created_by: string, manifest_sha256: string, created_at: string, };
