// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TenderIntegrityIssue = "audit_chain_invalid" | "database_integrity_invalid" | "inspection_unavailable" | "referenced_content_missing" | "referenced_content_mismatch" | "manifest_invalid" | "schema_mismatch" | "storage_layout_invalid" | "tender_identity_mismatch";
