// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderIntegrityIssue } from "./TenderIntegrityIssue";
import type { TenderIntegrityState } from "./TenderIntegrityState";
import type { TenderRecoveryChoice } from "./TenderRecoveryChoice";

export type TenderIntegrityReport = { tender_id: string, state: TenderIntegrityState, issues: Array<TenderIntegrityIssue>, recovery_choices: Array<TenderRecoveryChoice>, };
