// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentTaskInputReference } from "./AgentTaskInputReference";

export type TenderQueryResponse = { response_id: string, response: string, evidence: Array<AgentTaskInputReference>, registered_by: string, created_at: string, };
