// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderRecordAuthorityKind } from "./TenderRecordAuthorityKind";

export type TenderRecordAuthority = { authority_id: string, kind: TenderRecordAuthorityKind, value: string, description: string, manifest_sha256: string | null, tender_revision: number, created_by: string, created_at: string, };
