// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TenderLifecyclePhase = "intake" | "bid_decision" | "tender_planning" | "active_production" | "integrated_review" | "change_assessment" | "package_production" | "final_review" | "declined";
