// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TenderQueryTreatment = "internal_resolution" | "external_rfi_drafting" | "approved_assumption" | "qualification" | "exclusion" | "allowance" | "blocked";
