// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TenderErrorCode = "insufficient_space" | "integrity_failed" | "invalid_command" | "request_budget_exceeded" | "not_found" | "oauth_already_running" | "operation_timed_out" | "recovery_required" | "local_document_tools_required" | "ai_provider_required" | "setup_required" | "store_unavailable";
