// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderOfficeMessageAuthor } from "./TenderOfficeMessageAuthor";
import type { TenderOfficeMessageKind } from "./TenderOfficeMessageKind";
import type { WorkspaceMessageReference } from "./WorkspaceMessageReference";

export type TenderOfficeMessage = { message_id: string, sequence: number, author: TenderOfficeMessageAuthor, kind: TenderOfficeMessageKind, body: string, created_at: string, references: Array<WorkspaceMessageReference>, };
