// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRepairFeedback } from "./AgentRepairFeedback";
import type { AgentResourceBudget } from "./AgentResourceBudget";
import type { AgentRunPermissions } from "./AgentRunPermissions";
import type { AgentTaskInputReference } from "./AgentTaskInputReference";

export type TenderTaskView = { task_id: string, profile_id: string, profile_version: number, objective: string, exact_inputs: Array<AgentTaskInputReference>, output_contract_json: string, review_policy: string, deadline: string, permissions: AgentRunPermissions, resource_budget: AgentResourceBudget, repair_feedback: AgentRepairFeedback | null, };
