// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TenderRecordBasisKind = "evidence" | "assumption" | "tender_query" | "calculation_run" | "engineer_entry";
