// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderRecordAuthority } from "./TenderRecordAuthority";
import type { TenderRecordBasisKind } from "./TenderRecordBasisKind";
import type { TenderRecordEvidence } from "./TenderRecordEvidence";

export type TenderRecordField = { name: string, value: string | null, basis_kind: TenderRecordBasisKind, basis_reference: string | null, basis_description: string | null, basis_authority: TenderRecordAuthority | null, original_expression: string | null, normalized_value: string | null, timezone: string | null, uncertainty: string | null, evidence: Array<TenderRecordEvidence>, };
