// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderRecoveryDecisionRecord } from "./TenderRecoveryDecisionRecord";
import type { TenderRecoveryState } from "./TenderRecoveryState";
import type { TenderSummary } from "./TenderSummary";

export type TenderRecoveryRecord = { recovery_id: string, tender_id: string, backup_id: string, state: TenderRecoveryState, backup_source: TenderSummary | null, current_source: TenderSummary | null, diagnostic_code: string | null, decision_record: TenderRecoveryDecisionRecord | null, created_at: string, };
