// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderBackupState } from "./TenderBackupState";
import type { TenderSummary } from "./TenderSummary";

export type TenderBackupRecord = { backup_id: string, tender_id: string, state: TenderBackupState, source: TenderSummary | null, content_object_count: bigint, manifest_sha256: string | null, archive_size_bytes: bigint | null, diagnostic_code: string | null, created_at: string, };
