// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderRecoveryDecision } from "./TenderRecoveryDecision";

export type TenderRecoveryDecisionRecord = { decision: TenderRecoveryDecision, rationale: string, decided_by: string, manifest_sha256: string, current_audit_chain_head: string | null, decided_at: string, };
