// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TenderAiSelectionReadiness = "local_only" | "ready" | "selection_required" | "provider_unavailable" | "catalogue_stale" | "model_unavailable" | "approval_required";
