// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TenderQueryInvalidation = { invalidation_id: string, target_kind: string, target_id: string, target_version: number | null, reason: string, created_at: string, };
