// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceRelationshipKind } from "./SourceRelationshipKind";

export type TenderRecordSourceRelationship = { relationship_id: string, prior_artifact_id: string, prior_version: number, replacement_artifact_id: string, replacement_version: number, relationship_kind: SourceRelationshipKind, };
