// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TenderErrorCode = "insufficient_space" | "integrity_failed" | "invalid_command" | "not_found" | "oauth_already_running" | "oauth_port_blocked" | "operation_timed_out" | "recovery_required" | "runtime_required" | "setup_required" | "store_unavailable";
