// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentRegisterEntry } from "./DocumentRegisterEntry";
import type { TenderPackageSourceKind } from "./TenderPackageSourceKind";

export type TenderPackageImportResult = { intake_id: string, source_kind: TenderPackageSourceKind, discovered_count: number, registered_count: number, exception_count: number, query_register_open: boolean, documents: Array<DocumentRegisterEntry>, };
