// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderRecordReviewOutcome } from "./TenderRecordReviewOutcome";

export type TenderRecordReview = { review_id: string, outcome: TenderRecordReviewOutcome, rationale: string, reviewer_kind: string, reviewer_run_id: string | null, decided_by: string, created_at: string, };
