// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProductionTaskInspection } from "./ProductionTaskInspection";

export type TenderProductionInspection = { activation_id: string, plan_id: string, plan_version: number, plan_manifest_sha256: string, active: boolean, tasks: Array<ProductionTaskInspection>, activated_by: string, acting_role: string, created_at: string, };
