// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderIntegrityReport } from "./TenderIntegrityReport";
import type { TenderSummary } from "./TenderSummary";

export type TenderCatalogueEntry = { tender_id: string, summary: TenderSummary | null, integrity: TenderIntegrityReport, };
