// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiExecutionSelection } from "./AiExecutionSelection";
import type { TenderAiSelectionReadiness } from "./TenderAiSelectionReadiness";

export type TenderAiExecutionBinding = { revision: bigint, selection: AiExecutionSelection | null, readiness: TenderAiSelectionReadiness, status_summary: string, };
