// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TenderRecordTrustClass = "ai_proposal" | "deterministic_fact" | "verified" | "engineer_verified" | "approved_assumption" | "unresolved_gap" | "prior_decision";
