// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderRetentionState } from "./TenderRetentionState";

export type TenderRetentionDecisionRecord = { decision_id: string, tender_id: string, state: TenderRetentionState, rationale: string, decided_by: string, acting_role: string, manifest_sha256: string, decided_at: string, };
