// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderQueryTreatment } from "./TenderQueryTreatment";

export type TenderQueryTreatmentProposalInput = { treatment: TenderQueryTreatment, rationale: string, };
