// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderRecordInspection } from "./TenderRecordInspection";
import type { TenderRecordReview } from "./TenderRecordReview";

export type TenderRecordDecisionResult = { record: TenderRecordInspection, review: TenderRecordReview, };
