// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderRecordEvidence } from "./TenderRecordEvidence";

export type TenderRecordContradiction = { field_name: string, summary: string, evidence: Array<TenderRecordEvidence>, };
