// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderRecordInspection } from "./TenderRecordInspection";

export type TenderRecordPage = { records: Array<TenderRecordInspection>, next_cursor: string | null, };
