// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvidenceLocation } from "./EvidenceLocation";
import type { TenderEvidenceReference } from "./TenderEvidenceReference";

export type TenderRecordEvidence = { reference: TenderEvidenceReference, package_path: string, location: EvidenceLocation, };
