// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolSideEffectClass = "read_only" | "working_area_write" | "staged_output_write";
