// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderReferenceDiscoveryState } from "./ProviderReferenceDiscoveryState";
import type { TenderDeletionSourceState } from "./TenderDeletionSourceState";
import type { TrashedTenderState } from "./TrashedTenderState";

export type TrashedTenderRecord = { deletion_id: string, tender_id: string, tender_name: string, state: TrashedTenderState, relative_path: string, rationale: string, decided_by: string, acting_role: string, approval_manifest_sha256: string, diagnostic_code: string | null, created_at: string, updated_at: string, deletion_source: TenderDeletionSourceState, integrity_code: string | null, provider_reference_discovery: ProviderReferenceDiscoveryState, };
