// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataClassification } from "./DataClassification";
import type { ToolIdempotency } from "./ToolIdempotency";
import type { ToolSideEffectClass } from "./ToolSideEffectClass";
import type { TypedToolQuota } from "./TypedToolQuota";

export type TypedToolDefinition = { name: string, version: number, input_schema_json: string, output_schema_json: string, required_capability: string, required_action: string, required_data_scopes: Array<string>, allowed_data_classifications: Array<DataClassification>, side_effect_class: ToolSideEffectClass, quota: TypedToolQuota, safety_limits: Array<string>, idempotency: ToolIdempotency, audit_event_type: string, };
