// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TypedToolQuota = { maximum_calls: number, maximum_input_bytes: number, maximum_output_bytes: number, };
