// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateState = "idle" | "awaiting_approval" | "approved" | "denied" | "installing" | "restart_validation_required" | "ready" | "rejected" | "repair_required" | "rolled_back";
