// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateCompatibilityManifest = { installation_schema_version: number, tender_schema_version: number, ocr_version: string, runtime_manifest_schema_version: number, };
