// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SignedArtifactIdentity } from "./SignedArtifactIdentity";
import type { UpdateCompatibilityManifest } from "./UpdateCompatibilityManifest";
import type { UpdateImpact } from "./UpdateImpact";
import type { UpdatePlatform } from "./UpdatePlatform";
import type { UpdateReleaseInformation } from "./UpdateReleaseInformation";

export type UpdateOffer = { update_id: string, current_version: string, version: string, platform: UpdatePlatform, artifact: SignedArtifactIdentity, compatibility: UpdateCompatibilityManifest, release: UpdateReleaseInformation, impact: UpdateImpact, };
