// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateDecisionRecord } from "./UpdateDecisionRecord";
import type { UpdateDiagnostic } from "./UpdateDiagnostic";
import type { UpdateOffer } from "./UpdateOffer";
import type { UpdateState } from "./UpdateState";

export type UpdateStatus = { state: UpdateState, offer: UpdateOffer | null, decision_history: Array<UpdateDecisionRecord>, diagnostic: UpdateDiagnostic | null, };
