// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateDecision } from "./UpdateDecision";

export type UpdateDecisionRecord = { sequence: number, update_id: string, offer_sha256: string, decision: UpdateDecision, rationale: string, decided_by: string, acting_role: string, decided_at: string, preceding_hash: string, current_hash: string, };
