// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IntakeExceptionCode } from "./IntakeExceptionCode";
import type { ParseState } from "./ParseState";
import type { RegistrationState } from "./RegistrationState";

export type WorkspaceTenderDocument = { artifact_id: string, version: number, package_path: string, document_type: string, media_type: string | null, sha256: string | null, size_bytes: bigint, registration_state: RegistrationState, parse_state: ParseState, exception: IntakeExceptionCode | null, };
