// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceOutputReference = { artifact_id: string, version: number, production_task_id: string, author_run_id: string, payload_sha256: string, created_at: string, };
