// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceSearchResultKind } from "./WorkspaceSearchResultKind";

export type WorkspaceSearchHit = { kind: WorkspaceSearchResultKind, reference: string, version: number | null, title: string, detail: string, };
