// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceDoctorBlockerArea } from "./WorkspaceDoctorBlockerArea";

export type WorkspaceDoctorBlockerSummary = { code: string, area: WorkspaceDoctorBlockerArea, title: string, detail: string, };
