// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentProfileStatus } from "./AgentProfileStatus";
import type { AgentProfileVersionView } from "./AgentProfileVersionView";

export type WorkPlanProfileBinding = { archetype: string, status: AgentProfileStatus, profile: AgentProfileVersionView, };
