// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentResourceBudget } from "./AgentResourceBudget";

export type WorkPlanWorkstream = { workstream_key: string, name: string, capability: string, accountable_profile_id: string | null, dependencies: Array<string>, deadlines: Array<string>, milestones: Array<string>, resource_budget: AgentResourceBudget, };
