// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkPlanDecision } from "./WorkPlanDecision";

export type WorkPlanApprovalRecord = { approval_id: string, plan_id: string, plan_version: number, decision: WorkPlanDecision, rationale: string, plan_manifest_sha256: string, decided_by: string, acting_role: string, approval_sha256: string, created_at: string, };
