// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceFilesSummary = { tender_document_count: number, quantix_output_count: number, };
