// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceOutputReference } from "./WorkspaceOutputReference";
import type { WorkspaceTenderDocument } from "./WorkspaceTenderDocument";

export type WorkspaceFilesSummary = { tender_document_count: number, quantix_output_count: number, tender_documents: Array<WorkspaceTenderDocument>, quantix_outputs: Array<WorkspaceOutputReference>, };
