// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceMessageReferenceKind } from "./WorkspaceMessageReferenceKind";

export type WorkspaceMessageReference = { kind: WorkspaceMessageReferenceKind, reference: string, version: number, evidence_ordinal: number | null, label: string, detail: string | null, };
