// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceTaskState = "waiting" | "working" | "needs_engineer" | "paused" | "done" | "failed";
