// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceAgentReference } from "./WorkspaceAgentReference";
import type { WorkspaceTaskState } from "./WorkspaceTaskState";

export type WorkspaceTaskRow = { production_task_id: string, task_id: string | null, task_key: string, objective: string | null, state: WorkspaceTaskState, status_detail: string, dependencies: Array<string>, agent: WorkspaceAgentReference | null, current_run_id: string | null, output_count: number, };
