// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceEstimateStatus } from "./WorkspaceEstimateStatus";

export type WorkspaceEstimateSummary = { basis_id: string, version: number, status: WorkspaceEstimateStatus, boq_row_count: number, finding_count: number, calculation_run_count: number, };
