// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceActionKind } from "./WorkspaceActionKind";

export type WorkspaceCurrentAction = { kind: WorkspaceActionKind, title: string, summary: string, action_label: string, requires_engineer: boolean, };
