// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceSearchGroup } from "./WorkspaceSearchGroup";

export type WorkspaceSearchProjection = { query: string, groups: Array<WorkspaceSearchGroup>, };
