// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentResourceBudget } from "./AgentResourceBudget";

export type WorkPlanRevisionAction = { "action": "rebase_package_basis" } | { "action": "add_profile", archetype: string, identity: string, } | { "action": "remove_profile", profile_id: string, } | { "action": "split_profile", profile_id: string, identities: Array<string>, } | { "action": "combine_profiles", profile_ids: Array<string>, identity: string, } | { "action": "rename_profile", profile_id: string, identity: string, } | { "action": "adjust_profile", profile_id: string, objective: string, behavior: string, skepticism: string, risk_tolerance: string, resource_budget: AgentResourceBudget, };
