// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceSearchHit } from "./WorkspaceSearchHit";
import type { WorkspaceSearchResultKind } from "./WorkspaceSearchResultKind";

export type WorkspaceSearchGroup = { kind: WorkspaceSearchResultKind, hits: Array<WorkspaceSearchHit>, };
