// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkPlanCapabilityGap = { capability: string, reason: string, affected_work: Array<string>, };
