// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceExternalRfiStatus } from "./WorkspaceExternalRfiStatus";

export type WorkspaceExternalRfiSummary = { rfi_id: string, version: number, status: WorkspaceExternalRfiStatus, question_count: number, response_count: number, approval_pending: boolean, export_pending: boolean, interpretation_pending: boolean, };
