// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceAgentReference = { profile_id: string, profile_version: number, identity: string, profession: string, };
