// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceActionKind = "start_tender" | "add_tender_package" | "review_intake" | "observe_intake" | "answer_manager_question" | "retry_intake" | "review_bid_decision" | "prepare_work_plan" | "review_work_plan" | "review_work" | "review_integrated_work" | "review_change" | "review_submission_package" | "review_final_package" | "tender_declined";
