// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspacePricingBaselineStatus } from "./WorkspacePricingBaselineStatus";
import type { WorkspaceTenderPriceState } from "./WorkspaceTenderPriceState";

export type WorkspacePricingSummary = { baseline_id: string, baseline_version: number, baseline_current: boolean, baseline_status: WorkspacePricingBaselineStatus, baseline_finding_count: number, baseline_amount: string, baseline_currency: string, strategy_awaiting_approval: boolean, adjustments_awaiting_review: number, adjustments_awaiting_approval: number, scenario_selection_pending: boolean, selected_scenario_name: string | null, tender_price_state: WorkspaceTenderPriceState | null, tender_price_amount: string | null, tender_price_currency: string | null, };
