// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceMessageReferenceKind = "agent_run" | "manager_intake_outcome" | "tender_record" | "source_evidence";
