// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParseState } from "./ParseState";

export type WorkspaceTenderDocument = { artifact_id: string, version: number, package_path: string, document_type: string, media_type: string | null, sha256: string | null, size_bytes: bigint, parse_state: ParseState, };
