// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkPlanCapabilityGap } from "./WorkPlanCapabilityGap";
import type { WorkspaceCapabilityReadinessState } from "./WorkspaceCapabilityReadinessState";

export type WorkspaceCapabilityReadiness = { state: WorkspaceCapabilityReadinessState, gaps: Array<WorkPlanCapabilityGap>, blocker_codes: Array<string>, };
