// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceExternalRfiStatus = "awaiting_review" | "review_failed" | "awaiting_approval" | "approved_for_issue" | "response_awaiting_interpretation" | "query_basis_stale";
