// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceWorkSummary = { needs_engineer: number, working: number, waiting: number, done: number, cancelled: number, failed: number, };
