// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderOfficeMessage } from "./TenderOfficeMessage";
import type { WorkspaceAgentRunReference } from "./WorkspaceAgentRunReference";

export type WorkspaceTeamSummary = { active_agent_runs: number, waiting_tasks: number, needs_engineer: number, events: Array<TenderOfficeMessage>, agent_runs: Array<WorkspaceAgentRunReference>, };
