// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceAgentReference } from "./WorkspaceAgentReference";

export type WorkspaceAgentRunReference = { run_id: string, task_id: string, state: string, agent: WorkspaceAgentReference, started_at: string, completed_at: string | null, };
