#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10
TOTAL_MINUTES=185
ENV_FILE="${QUANTIX_RELEASE_ENV_FILE:-}"
if [[ -z "$ENV_FILE" ]]; then
  ENV_FILE=".env.release.local"
fi

REPOSITORY="kareem-sf/quantix"
WORK_DIRECTORY=".release-wizard"
mkdir -p "$WORK_DIRECTORY"

json_last_field() {
  node -e '
    const fs = require("fs");
    const lines = fs.readFileSync(process.argv[1], "utf8").split(/\r?\n/).filter(Boolean).reverse();
    for (const line of lines) {
      try {
        const value = JSON.parse(line)[process.argv[2]];
        if (value !== undefined) {
          process.stdout.write(String(value));
          process.exit(0);
        }
      } catch {}
    }
    process.exit(1);
  ' "$1" "$2"
}

require_path() {
  if [[ ! -e "$1" ]]; then
    warn "not found: $1"
    exit 1
  fi
}

banner "Quantix private Windows release setup"

stage "Verify this release workstation" 10
say "We will verify the repository, install exact dependencies, and confirm GitHub access."
for tool in git gh node npm powershell.exe; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    warn "$tool is required before continuing."
    exit 1
  fi
done
if [[ "$(gh repo view --json nameWithOwner --jq .nameWithOwner 2>/dev/null || true)" != "$REPOSITORY" ]]; then
  warn "Open Git Bash in the kareem-sf/quantix repository and authenticate gh first."
  exit 1
fi
gh auth status
if ! git diff --quiet || ! git diff --cached --quiet; then
  warn "Commit, stash, or discard tracked changes before the release wizard edits configuration."
  exit 1
fi
SAVED_CANDIDATE_RUN_ID="$(_existing CANDIDATE_RUN_ID || true)"
SAVED_SOURCE_REVISION="$(_existing SOURCE_REVISION || true)"
RESUMING_CANDIDATE="false"
if [[ -n "$SAVED_CANDIDATE_RUN_ID" || -n "$SAVED_SOURCE_REVISION" ]]; then
  if [[ -z "$SAVED_CANDIDATE_RUN_ID" || -z "$SAVED_SOURCE_REVISION" ]]; then
    warn "Saved candidate state is incomplete. Start a new attempt with a new release environment file."
    exit 1
  fi
  RESUMING_CANDIDATE="true"
  git fetch origin main
  if ! git cat-file -e "$SAVED_SOURCE_REVISION^{commit}" 2>/dev/null; then
    warn "The saved workflow source commit is not available locally."
    exit 1
  fi
  if ! git merge-base --is-ancestor "$SAVED_SOURCE_REVISION" origin/main; then
    warn "The saved workflow source is not part of the trusted main history."
    exit 1
  fi
  git switch --detach "$SAVED_SOURCE_REVISION"
  say "Qualification is pinned to saved source revision $SAVED_SOURCE_REVISION."
else
  git switch main
  git pull --ff-only
fi
npm ci
say "Workstation prerequisites are ready."

stage "Create the Tauri updater signing key" 15
say "This key proves that an update came from Quantix. It is separate from Windows Authenticode."
DEFAULT_UPDATER_KEY="$HOME/.tauri/quantix.key"
ask UPDATER_PRIVATE_KEY_PATH "Private key path [default: $DEFAULT_UPDATER_KEY]:"
if [[ -z "$UPDATER_PRIVATE_KEY_PATH" ]]; then
  UPDATER_PRIVATE_KEY_PATH="$DEFAULT_UPDATER_KEY"
fi
mkdir -p "$(dirname "$UPDATER_PRIVATE_KEY_PATH")"
if [[ ! -f "$UPDATER_PRIVATE_KEY_PATH" ]]; then
  step "The signer will ask you for a strong password twice. Save that password in your password manager."
  npm run tauri signer generate -- -w "$UPDATER_PRIVATE_KEY_PATH"
fi
require_path "$UPDATER_PRIVATE_KEY_PATH"
require_path "$UPDATER_PRIVATE_KEY_PATH.pub"
UPDATER_PUBLIC_KEY="$(tr -d '\r\n' < "$UPDATER_PRIVATE_KEY_PATH.pub")"
if [[ -z "$UPDATER_PUBLIC_KEY" ]]; then
  warn "The updater public key is empty."
  exit 1
fi
if [[ "$RESUMING_CANDIDATE" == "true" ]]; then
  PINNED_PUBLIC_KEY="$(node -e 'const c=require("./src-tauri/tauri.conf.json"); process.stdout.write(c.plugins.updater.pubkey || "")')"
  if [[ "$PINNED_PUBLIC_KEY" != "$UPDATER_PUBLIC_KEY" ]]; then
    warn "The saved candidate was built for a different updater key. Use the original key for this attempt."
    exit 1
  fi
fi
ask_secret UPDATER_KEY_PASSWORD "Enter the updater key password for GitHub Actions:"
if [[ -z "$UPDATER_KEY_PASSWORD" ]]; then
  warn "The updater key password cannot be empty."
  exit 1
fi
UPDATER_PRIVATE_KEY="$(cat "$UPDATER_PRIVATE_KEY_PATH")"
set_secret TAURI_SIGNING_PRIVATE_KEY "$UPDATER_PRIVATE_KEY"
set_secret TAURI_SIGNING_PRIVATE_KEY_PASSWORD "$UPDATER_KEY_PASSWORD"
UPDATER_SECRET_COUNT="$(gh secret list --json name --jq '[.[] | select(.name == "TAURI_SIGNING_PRIVATE_KEY" or .name == "TAURI_SIGNING_PRIVATE_KEY_PASSWORD")] | length')"
if [[ "$UPDATER_SECRET_COUNT" != "2" ]]; then
  warn "Both updater signing secrets must exist before packaging."
  exit 1
fi
write_env UPDATER_PRIVATE_KEY_PATH "$UPDATER_PRIVATE_KEY_PATH"
write_env UPDATER_PUBLIC_KEY "$UPDATER_PUBLIC_KEY"
say "The private key was sent to GitHub and was not written to the release environment file."

stage "Commit the updater public key" 15
say "The public half of the key must be compiled into Quantix before candidate packages are signed."
CURRENT_PUBLIC_KEY="$(node -e 'const c=require("./src-tauri/tauri.conf.json"); process.stdout.write(c.plugins.updater.pubkey || "")')"
if [[ "$RESUMING_CANDIDATE" == "true" ]]; then
  say "The saved candidate source already contains the matching updater public key."
else
  if [[ "$CURRENT_PUBLIC_KEY" != "$UPDATER_PUBLIC_KEY" ]]; then
    node -e '
      const fs = require("fs");
      const path = "src-tauri/tauri.conf.json";
      const config = JSON.parse(fs.readFileSync(path, "utf8"));
      config.plugins.updater.pubkey = process.argv[1];
      fs.writeFileSync(path, JSON.stringify(config, null, 2) + "\n");
    ' "$UPDATER_PUBLIC_KEY"
    npx prettier --write src-tauri/tauri.conf.json
  fi
  if ! git diff --quiet -- src-tauri/tauri.conf.json; then
    if confirm "Create and push the updater-public-key pull request now?"; then
      BRANCH="chore/configure-updater-public-key-$(printf '%s' "$UPDATER_PUBLIC_KEY" | git hash-object --stdin | cut -c1-8)"
      if git show-ref --verify --quiet "refs/heads/$BRANCH"; then
        git switch "$BRANCH"
      else
        git switch -c "$BRANCH"
      fi
      git add src-tauri/tauri.conf.json
      git commit -m "chore: configure updater public key"
      git push -u origin "$BRANCH"
      gh pr create --base main --head "$BRANCH" --title "chore: configure updater public key" --body "Configures the public half of the Tauri updater signing key. The private key remains in GitHub Actions secrets."
      gh pr view --web
    else
      warn "Candidate packaging cannot proceed until the public-key pull request is merged."
      exit 1
    fi
  fi
  step "Wait for CI to pass, review the one-file change, and merge the pull request."
  pause "Press Enter after the pull request is merged."
  git switch main
  git pull --ff-only
  MERGED_PUBLIC_KEY="$(node -e 'const c=require("./src-tauri/tauri.conf.json"); process.stdout.write(c.plugins.updater.pubkey || "")')"
  if [[ "$MERGED_PUBLIC_KEY" != "$UPDATER_PUBLIC_KEY" ]]; then
    warn "The updater public key is not on main yet."
    exit 1
  fi
fi

stage "Confirm the Quantix Application Home" 10
DEFAULT_APPLICATION_HOME="$(powershell.exe -NoProfile -NonInteractive -Command '[Environment]::GetFolderPath("UserProfile") + "\.quantix"' | tr -d '\r')"
ask APPLICATION_HOME "Application Home [default: $DEFAULT_APPLICATION_HOME]:"
if [[ -z "$APPLICATION_HOME" ]]; then
  APPLICATION_HOME="$DEFAULT_APPLICATION_HOME"
fi
if [[ "$APPLICATION_HOME" != /* && ! "$APPLICATION_HOME" =~ ^[A-Za-z]:[\\/].* ]]; then
  warn "Application Home must be an absolute path."
  exit 1
fi
mkdir -p "$APPLICATION_HOME"
write_env APPLICATION_HOME "$APPLICATION_HOME"
set_var QUANTIX_APPLICATION_HOME "$APPLICATION_HOME"
say "The release evidence database will live here. Back it up; do not share it publicly."

stage "Record the Windows code-signing status" 10
say "Updater signing protects update files. Windows Authenticode is a separate public-distribution requirement."
open_url "https://v2.tauri.app/distribute/sign/windows/"
if confirm "Do you already own an organization-validated Windows code-signing certificate?"; then
  powershell.exe -NoProfile -NonInteractive -Command 'Get-ChildItem Cert:\CurrentUser\My -CodeSigningCert | Select-Object Subject,Thumbprint,NotAfter'
  ask WINDOWS_SIGNER_THUMBPRINT "Paste the intended certificate thumbprint:"
  write_env WINDOWS_SIGNER_THUMBPRINT "$WINDOWS_SIGNER_THUMBPRINT"
  SKIPPED+=("have the signer thumbprint reviewed and added to the Rust release allowlist")
else
  SKIPPED+=("obtain an organization-validated Windows code-signing certificate before public distribution")
  say "That does not block a private draft candidate, but it does block a public Windows release."
fi

stage "Build the private Windows candidate" 25
say "This workflow produces only draft, prerelease NSIS and MSI packages. It never publishes a public release."
CANDIDATE_ID="$(_existing CANDIDATE_ID || true)"
RUN_ID="$(_existing CANDIDATE_RUN_ID || true)"
CANDIDATE_TAG="$(_existing CANDIDATE_TAG || true)"
SOURCE_REVISION="$(_existing SOURCE_REVISION || true)"
LIVE_RUN_COUNT="$(_existing LIVE_RUN_COUNT || true)"
if [[ -z "$RUN_ID" && ( -n "$CANDIDATE_ID" || -n "$CANDIDATE_TAG" || -n "$SOURCE_REVISION" || -n "$LIVE_RUN_COUNT" ) ]]; then
  warn "Candidate state is incomplete. Preserve this file for audit, then start a new attempt with a new QUANTIX_RELEASE_ENV_FILE."
  exit 1
fi
if [[ -n "$RUN_ID" ]]; then
  if [[ -z "$CANDIDATE_ID" || -z "$CANDIDATE_TAG" || -z "$SOURCE_REVISION" ]]; then
    warn "The saved candidate is missing its identity fields. Start a new attempt with a new release environment file."
    exit 1
  fi
  say "Resuming candidate $CANDIDATE_TAG from workflow run $RUN_ID."
else
  SOURCE_REVISION="$(git rev-parse HEAD)"
  CANDIDATE_ID="$(date -u +%Y%m%d%H%M%S)-$(git rev-parse --short=12 HEAD)"
  CANDIDATE_VERSION="$(node -e 'const c=require("./src-tauri/tauri.conf.json"); process.stdout.write(c.version)')"
  CANDIDATE_TAG="quantix-v$CANDIDATE_VERSION-candidate.$CANDIDATE_ID"
  gh workflow run candidate-windows.yml --ref main -f "candidate_id=$CANDIDATE_ID"
  for _ in $(seq 1 30); do
    RUN_RESULT="$(gh run list --workflow candidate-windows.yml --branch main --event workflow_dispatch --limit 50 --json databaseId,displayTitle,headSha --jq ".[] | select(.displayTitle == \"Windows candidate $CANDIDATE_ID\") | [.databaseId, .headSha] | @tsv" | head -n1)"
    if [[ -n "$RUN_RESULT" ]]; then
      IFS=$'\t' read -r RUN_ID RUN_HEAD_SHA <<< "$RUN_RESULT"
      break
    fi
    sleep 2
  done
  if [[ -z "$RUN_ID" ]]; then
    warn "The uniquely named candidate workflow did not appear within one minute."
    exit 1
  fi
  if [[ "$RUN_HEAD_SHA" != "$SOURCE_REVISION" ]]; then
    warn "The workflow source revision does not match the dispatched main revision."
    exit 1
  fi
  write_env CANDIDATE_ID "$CANDIDATE_ID"
  write_env CANDIDATE_RUN_ID "$RUN_ID"
  write_env CANDIDATE_TAG "$CANDIDATE_TAG"
  write_env SOURCE_REVISION "$SOURCE_REVISION"
fi
RUN_METADATA="$(gh run view "$RUN_ID" --json displayTitle,headSha,conclusion --jq '[.displayTitle, .headSha, .conclusion] | @tsv')"
IFS=$'\t' read -r RUN_TITLE RUN_HEAD_SHA RUN_CONCLUSION <<< "$RUN_METADATA"
if [[ "$RUN_TITLE" != "Windows candidate $CANDIDATE_ID" || "$RUN_HEAD_SHA" != "$SOURCE_REVISION" ]]; then
  warn "The saved workflow run no longer matches this candidate identity."
  exit 1
fi
if [[ -z "$RUN_CONCLUSION" ]]; then
  gh run view "$RUN_ID" --web
  gh run watch "$RUN_ID" --exit-status
elif [[ "$RUN_CONCLUSION" != "success" ]]; then
  warn "The saved candidate workflow did not succeed. Start a new candidate attempt."
  exit 1
fi
CANDIDATE_RELEASE="$(gh api "repos/$REPOSITORY/releases?per_page=100" --jq ".[] | select(.draft and .prerelease and .tag_name == \"$CANDIDATE_TAG\") | [.id, .tag_name] | @tsv")"
IFS=$'\t' read -r CANDIDATE_RELEASE_ID CANDIDATE_TAG <<< "$CANDIDATE_RELEASE"
if [[ -z "$CANDIDATE_RELEASE_ID" || -z "$CANDIDATE_TAG" || "$CANDIDATE_TAG" == "null" ]]; then
  warn "The exact draft release for workflow run $RUN_ID was not found."
  exit 1
fi
CANDIDATE_DOWNLOAD_DIRECTORY="$WORK_DIRECTORY/$CANDIDATE_TAG"
mkdir -p "$CANDIDATE_DOWNLOAD_DIRECTORY"
while IFS=$'\t' read -r ASSET_ID ASSET_NAME; do
  if [[ -n "$ASSET_ID" && ! -f "$CANDIDATE_DOWNLOAD_DIRECTORY/$ASSET_NAME" ]]; then
    ASSET_TEMP="$CANDIDATE_DOWNLOAD_DIRECTORY/$ASSET_NAME.partial"
    gh api -H "Accept: application/octet-stream" "repos/$REPOSITORY/releases/assets/$ASSET_ID" > "$ASSET_TEMP"
    mv "$ASSET_TEMP" "$CANDIDATE_DOWNLOAD_DIRECTORY/$ASSET_NAME"
  fi
done < <(gh api "repos/$REPOSITORY/releases/$CANDIDATE_RELEASE_ID/assets" --jq '.[] | [.id, .name] | @tsv')
if ! find "$CANDIDATE_DOWNLOAD_DIRECTORY" -maxdepth 1 -type f | grep -q .; then
  warn "The draft candidate has no downloadable assets."
  exit 1
fi
write_env CANDIDATE_TAG "$CANDIDATE_TAG"
write_env CANDIDATE_DOWNLOAD_DIRECTORY "$CANDIDATE_DOWNLOAD_DIRECTORY"
say "Candidate downloaded to $CANDIDATE_DOWNLOAD_DIRECTORY."

stage "Install and identify the exact candidate" 15
PRIVATE_QUALIFICATION_SHA256="$(_existing PRIVATE_QUALIFICATION_SHA256 || true)"
if [[ -n "$PRIVATE_QUALIFICATION_SHA256" ]]; then
  say "This exact candidate is already privately qualified; installation is not repeated."
else
  step "Run the downloaded NSIS setup executable. Keep the downloaded installer unchanged."
  step "Launch Quantix once, complete its local setup, then close it."
  ask APPLICATION_ARTIFACT_PATH "Absolute path to the installed Quantix executable:"
  ask APPLICATION_RESOURCE_DIRECTORY_PATH "Absolute path to the installed resource directory:"
  ask APPLICATION_UNINSTALLER_PATH "Absolute path to the installed uninstaller:"
  require_path "$APPLICATION_ARTIFACT_PATH"
  require_path "$APPLICATION_RESOURCE_DIRECTORY_PATH"
  require_path "$APPLICATION_UNINSTALLER_PATH"
  write_env APPLICATION_ARTIFACT_PATH "$APPLICATION_ARTIFACT_PATH"
  write_env APPLICATION_RESOURCE_DIRECTORY_PATH "$APPLICATION_RESOURCE_DIRECTORY_PATH"
  write_env APPLICATION_UNINSTALLER_PATH "$APPLICATION_UNINSTALLER_PATH"
fi

stage "Run deterministic Product Acceptance" 25
say "This proves the installed binary, bundled resources, schemas, fixtures, and dependency lock match the expected behavior."
DETERMINISTIC_RECORD_SHA256="$(_existing DETERMINISTIC_RECORD_SHA256 || true)"
if [[ -n "$DETERMINISTIC_RECORD_SHA256" ]]; then
  say "The deterministic record for this saved candidate already exists; reusing it."
else
DETERMINISTIC_COMMAND="$WORK_DIRECTORY/deterministic-command.json"
node -e '
  const fs = require("fs");
  fs.writeFileSync(process.argv[1], JSON.stringify({
    source_revision: process.argv[2],
    application_artifact_path: process.argv[3],
    application_resource_directory_path: process.argv[4],
    dependency_lock_path: process.argv[5]
  }, null, 2) + "\n");
' "$DETERMINISTIC_COMMAND" "$SOURCE_REVISION" "$APPLICATION_ARTIFACT_PATH" "$APPLICATION_RESOURCE_DIRECTORY_PATH" "$(pwd -W)/src-tauri/Cargo.lock"
DETERMINISTIC_LOG="$WORK_DIRECTORY/deterministic.log"
npm run acceptance:deterministic -- "$APPLICATION_HOME" "$DETERMINISTIC_COMMAND" 2>&1 | tee "$DETERMINISTIC_LOG"
DETERMINISTIC_OUTCOME="$(json_last_field "$DETERMINISTIC_LOG" outcome)"
if [[ "$DETERMINISTIC_OUTCOME" != "passed" ]]; then
  warn "Deterministic Product Acceptance did not pass."
  exit 1
fi
AGGREGATE_LOG="$WORK_DIRECTORY/deterministic-aggregate.log"
npm run acceptance:aggregate -- "$APPLICATION_HOME" "$SOURCE_REVISION" 2>&1 | tee "$AGGREGATE_LOG"
DETERMINISTIC_RECORD_SHA256="$(json_last_field "$AGGREGATE_LOG" manifest_sha256)"
write_env DETERMINISTIC_RECORD_SHA256 "$DETERMINISTIC_RECORD_SHA256"
fi

stage "Record five clean live Codex runs" 55
say "Each opted-in run uses your existing Codex login, exercises the full candidate, and then uninstalls it."
say "A failure invalidates the candidate. Fix the problem and start with a new candidate."
LIVE_COMMAND="$WORK_DIRECTORY/live-command.json"
LIVE_RUN_COUNT="$(_existing LIVE_RUN_COUNT || true)"
if [[ -z "$LIVE_RUN_COUNT" ]]; then
  LIVE_RUN_COUNT=0
fi
CANDIDATE_BINARY_SHA256="$(_existing CANDIDATE_BINARY_SHA256 || true)"
if [[ -n "$PRIVATE_QUALIFICATION_SHA256" && ( "$LIVE_RUN_COUNT" != "5" || -z "$CANDIDATE_BINARY_SHA256" ) ]]; then
  warn "The saved private qualification is not accompanied by its five-run candidate identity."
  exit 1
fi
while (( LIVE_RUN_COUNT < 5 )); do
  NEXT_RUN=$((LIVE_RUN_COUNT + 1))
  step "Install the same downloaded candidate again for live run $NEXT_RUN of 5, launch it once, then close it."
  pause "Press Enter when the exact candidate is installed."
  require_path "$APPLICATION_ARTIFACT_PATH"
  require_path "$APPLICATION_RESOURCE_DIRECTORY_PATH"
  require_path "$APPLICATION_UNINSTALLER_PATH"
  node -e '
    const fs = require("fs");
    fs.writeFileSync(process.argv[1], JSON.stringify({
      opted_in: true,
      application_artifact_path: process.argv[2],
      application_resource_directory_path: process.argv[3],
      application_uninstaller_path: process.argv[4],
      deterministic_acceptance_record_sha256: process.argv[5]
    }, null, 2) + "\n");
  ' "$LIVE_COMMAND" "$APPLICATION_ARTIFACT_PATH" "$APPLICATION_RESOURCE_DIRECTORY_PATH" "$APPLICATION_UNINSTALLER_PATH" "$DETERMINISTIC_RECORD_SHA256"
  LIVE_LOG="$WORK_DIRECTORY/live-$NEXT_RUN.log"
  npm run acceptance:live -- "$APPLICATION_HOME" "$LIVE_COMMAND" 2>&1 | tee "$LIVE_LOG"
  LIVE_OUTCOME="$(json_last_field "$LIVE_LOG" outcome)"
  LIVE_SEQUENCE="$(json_last_field "$LIVE_LOG" sequence_number)"
  MEASURED_BINARY_SHA256="$(json_last_field "$LIVE_LOG" release_candidate_sha256)"
  if [[ "$LIVE_OUTCOME" != "passed" || "$LIVE_SEQUENCE" != "$NEXT_RUN" ]]; then
    warn "Live run $NEXT_RUN did not produce the expected clean sequence."
    exit 1
  fi
  if [[ -n "$CANDIDATE_BINARY_SHA256" && "$CANDIDATE_BINARY_SHA256" != "$MEASURED_BINARY_SHA256" ]]; then
    warn "The installed executable changed between qualification runs."
    exit 1
  fi
  CANDIDATE_BINARY_SHA256="$MEASURED_BINARY_SHA256"
  LIVE_RUN_COUNT="$NEXT_RUN"
  write_env CANDIDATE_BINARY_SHA256 "$CANDIDATE_BINARY_SHA256"
  write_env LIVE_RUN_COUNT "$LIVE_RUN_COUNT"
done

stage "Authorize Private v0 and review public blockers" 10
say "Five clean runs authorize engineer-operated, non-public Windows use of this exact binary."
if [[ -n "$PRIVATE_QUALIFICATION_SHA256" ]]; then
  say "Private v0 was already authorized for this exact candidate."
else
  PRIVATE_LOG="$WORK_DIRECTORY/private-qualification.log"
  npm run acceptance:private -- "$APPLICATION_HOME" "$CANDIDATE_BINARY_SHA256" 2>&1 | tee "$PRIVATE_LOG"
  PRIVATE_QUALIFICATION_SHA256="$(json_last_field "$PRIVATE_LOG" manifest_sha256)"
  write_env PRIVATE_QUALIFICATION_SHA256 "$PRIVATE_QUALIFICATION_SHA256"
fi
SKIPPED+=("record signed native lifecycle evidence for Windows 11 x64")
SKIPPED+=("record signed native lifecycle evidence for macOS 14+ Apple Silicon")
SKIPPED+=("record signed native lifecycle evidence for Ubuntu 24.04 x64")
SKIPPED+=("implement signer-verified provenance binding the source manifest to every native binary")
SKIPPED+=("complete license-distribution review and approved signer allowlists")
SKIPPED+=("obtain production assurance and permitted subscription-integration terms for Codex app-server")
SKIPPED+=("configure and test a production updater endpoint")
say "Private v0 is qualified. Public distribution remains blocked until every item below is independently evidenced."
open_url "https://github.com/kareem-sf/quantix/blob/main/docs/adr/0010-qualify-v0-through-layered-product-acceptance.md"
git switch main
git pull --ff-only

finish
