FROM mcr.microsoft.com/playwright@sha256:eff16c30e6f3f4af0a03fa4b706120d5e9b0891c344a27d64559aff5900a4a27

WORKDIR /app
COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json
RUN npm ci --omit=dev --ignore-scripts && npm cache clean --force
COPY read-page.mjs /app/read-page.mjs
COPY public-proxy.mjs /app/public-proxy.mjs
COPY qualify.mjs /app/qualify.mjs
USER pwuser
ENTRYPOINT ["node", "/app/read-page.mjs"]
